### ISSUE TITLE
Redesign Aura

### ISSUE THREAD

**Issue by fosskers** [fosskers/aura#217]
Create a design document in `.md` format for easy viewing on github. This also allows for code snippets to be added. The main section needed is `Functional Requirements`, as many of Aura's features were tacked on later because the use cases they involve were not known about at first. As many use cases as possible should be considered before recoding begins. 

Related issues:
- Hotedit: #208 
- Install method: #213 #214 #203 #125 #114 #107 #202 
- Package signing: #211 #38 
- Help: #111 
- Colour: #102 #158 #202 
- ~~customizepkg: #93 #143 #198~~
- Dependencies: #215

**Comment by joca-bt** [comment]
Suggestion: option to pass arguments to ```makepkg```. The first example that comes to mind is to allow passing ```--skippgpcheck``` to ```makepkg```.

**Comment by fosskers** [comment]
@joca-bt This is often requested, and would be handled by the Arch-specific hooks of Aura 2.

**Comment by atondwal** [comment]
`Linux.Arch.Aur.*`  and `Linux.Debian.Rep` is very misleading. There's no reason aura shouldn't work unmodified on, say, Arch BSD, Arch Hurd, or even kFreeBSD, is there?

**Comment by joca-bt** [comment]
Cool, thanks!

**Comment by fosskers** [comment]
@atondwal I didn't know there were non-Linux versions of Arch. Provided they have `pacman` and `makepkg` installed, then yeah, `aura` should work unmodified.

**Comment by atondwal** [comment]
Maybe we could have names like `Distribution.Arch` and `Distribution.Debian` for `pacman`/`dpkg` stuff respectively?

**Comment by fosskers** [comment]
Or take an `Aura` topname?

**Comment by bb010g** [comment]
I'd be for just `Aura`.

**Comment by fosskers** [comment]
Where a hook library would be: `Aura.DistroName`.

**Comment by flamusdiu** [comment]
+1

**Comment by bb010g** [comment]
#332 brought up an interesting point. Currently, `pacman` uses both `Q` and `D` operations for local database operations (queries & changes) and `R` for local package removal, and uses `S` for remote package addition and database queries, `T` for a mix of remote and local queries (dependency testing for wanted remote packages on the local system), and `U` for local package addition. `V` is used for version testing. We'll have to find some way to unify all these into top level operations. I'd suggest a model of two operations per hook: e.g. for the main system package manager, `S` for remote and `Q` for local. `pacman`'s `R`, `D`, & `U` would then become sub-operations of `Q` and `pacman`'s `T` would become a sub-operation of `S`. I'd imagine `v` (née `V`) would become like `h` and give info on the parent hook, leaving `V` for global `aura` version info.

**Comment by fosskers** [comment]
My propositions for renaming top-level ops is covered in the Doc. I like the idea of relegating the other ones to subops of the top-level ones.

**Comment by bb010g** [comment]
The main issue with something like [a global `R` operation](http://aura.readthedocs.org/en/latest/design.html#local-package-removal) is that you can have different packages from different hooks that have the same name. What happens then? An interactive disambiguation would be my first thought, but you can't easily script that. My next thought is a sort of namespacing, and that is what the two operations per hook pattern would provide. Also, on the topic of scripting, it would be nice to have a long, unique variant of each operator (as to provide consistency across setups in scripts). E.g. on an Arch system, `-S` would also be `--alpm` and `-A` would be `--aur`. `A` is unique here, as it depends on `-L` (`--alpm-local`) for local package management and thus is an exception to the two operations per hook pattern. However, something like `--linuxbrew` would need a `--linuxbrew-local`.

**Comment by fosskers** [comment]
I have been flirting with the idea of multiple Hook sets on one machine (which you seem to be implying here). As `pacman` does now with haskell packages, could it be the domain of Aura to interface to *all* package managers on a user's system?

Then they make calls like:

* `aura -S firefox` <- the default, with no git-like command.
* `aura cabal -{S,L} lens` <- Still install/query the same way. 
* `aura npm -{S,L} grunt`
* `aura pip -{S,L} django`

**Comment by flamusdiu** [comment]
@fosskers that would probably make the day of people who use all these different package manager and would be very useful.

**Comment by fosskers** [comment]
Is it easier for someone to do `aura cabal -S lens` or `cabal install lens`? I'm thinking the later. That said, I think this functionality would really shine during querying.

Output like `aura -Ss lens` above with local packages would also be very convenient: 

```
> aura -Ls lens
haskell-core/haskell-lens 1.x.x: blah blah blah
cabal/lens 1.x.x: blah blah blah
```

**Comment by bb010g** [comment]
Relevant conversation on the Gitter on July [27th](https://gitter.im/aurapm/aura/archives/2016/07/27) and [28th](https://gitter.im/aurapm/aura/archives/2016/07/28). The direction is shifting away from "support ***ALL*** the things" to "support ALPM and the AUR well".

**Comment by fosskers** [comment]
Design then may be informed by a proper port of libalpm.
