### ISSUE TITLE
Ignore AUR package during upgrade

### ISSUE THREAD

**Issue by erbridge** [fosskers/aura#266]
It would be very useful to be able to do something like `aura -Au --ignore shellcheck`.

**Comment by mb720** [comment]
Does `--aurignore` or an equivalent option still exist?

I just ran

    sudo aura -Aua --aurignore intellij-idea-ultimate-edition-jre

and got the error

>Invalid option `--aurignore'

**Comment by fosskers** [comment]
Which Aura version are you using?

**Comment by fosskers** [comment]
In that case it should still exist. It would also be possible for you to try the Aura 4 Beta:

```
cargo install aura-pm --version 4.0.0-beta02
```

which supports `--ignore` under `-A`.
