### ISSUE TITLE
asking for sudo when run as root

### ISSUE THREAD

**Issue by justin8** [fosskers/aura#282]
When running aura within a docker image (dock0/arch) it complains that aura -A commands should be run with sudo.

```
aura -Aa nzbdrone-torrents
aura >>= You have to use `sudo` for that.
echo $EUID
0
whoami
root
```

**Comment by fosskers** [comment]
@flamusdiu Yes it would be, as all `root` business is related to working around `makepkg` behaviour. Since Aura 2 won't use `makepkg`, this will solve itself.
