### ISSUE TITLE
Where is Aura 2?

### ISSUE THREAD

**Issue by AphonicChaos** [fosskers/aura#292]
Pardon the troll bait title. As I have about 5 weeks before classes start again, I wanted to start getting back into Haskell. I know we've been doing a lot of brain storming, but I must have missed where we mentioned the base for aura2 was located. I didn't see a branch any where. Did I miss it? Is this sitting somewhere on @fosskers' hard drive?

**Comment by fosskers** [comment]
Update: At the moment I'm working through various Haskell libraries. The next one on my list is `extensible-effects`, which once I have down the Aura core can be build upon from the ground up. Mind you I'm balancing this with learning Purescript, OpenGL, and having contract work, so please be patient if the pace is slow. Things will pick up.

**Comment by bb010g** [comment]
> balancing this with learning Purescript
Coming Soon: aura.js

I've been thinking about YAPP recently, and I'm letting it mull about for a bit longer before I try to do something with it again. I think we'll be dropping Semigroupoids in favour of lens, but I'm still not sure how I want to put lens in.

**Comment by fosskers** [comment]
In the meantime let's choose an alternative prelude to work with.
[ClassyPrelude](http://hackage.haskell.org/package/classy-prelude-0.10.2/docs/ClassyPrelude.html) looks alright.

**Comment by mrak** [comment]
Has selecting an alternative prelude changed with the new Prelude in GHC 7.10.1?

**Comment by aspidites** [comment]
@fosskers , purescript is nice. I started looking at it a few months ago and did some small things with it. The two things that still feel awkward to me with it are AJAX (I was using affjax) and guis - none of the DSL's feel as "nice" as Haskell offerings, such as lucid.

**Comment by bb010g** [comment]
@mrak The GHC 8 Prelude only has AMP & FTP. Classy Prelude includes proper functions for Category (`id`, `(.)`) & Monoid (`++`).

**Comment by fosskers** [comment]
ClassyPrelude is also maintained by Michael Snoyman (the Stack/Yesod guy) so is likely to stick around.

Notes:

* CP provides: `tshow :: Show a => a -> Text` which semi-conflicts with `showt :: TextShow a => a -> Text` from the `text-show` package.
* ~~CP is full of Monad transformers~~. Semi-moot since `extensible-effects` depends on `transformers` anyway (but not `mtl`).
* CP has a lot of content we don't need. Bloat? I want to keep dependencies down.
