### ISSUE TITLE
hasRootPriv should return True if UID == 0

### ISSUE THREAD

**Issue by wereHamster** [fosskers/aura#293]
When I use `su` (not `su -`) then the `USER` env variable keeps the previous value (my normal user name) and `hasRootPriv` returns False. This check could also be moved to `isTrueRoot`.

**Comment by fosskers** [comment]
Does your `env` variable report a `UID` with and without `su`?

**Comment by wereHamster** [comment]
no, neither with nor without su.

**Comment by wereHamster** [comment]
Well, I think we can close this issue because pkgbuild can not be run as root anymore, one should use sudo instead.

**Comment by fosskers** [comment]
Not entirely true. With the fix I just made, you should be able to build as root if you specify a build username with `--builduser`.
