### ISSUE TITLE
Don't clone VCS clones over and over again

### ISSUE THREAD

**Issue by tsdh** [fosskers/aura#462]
I've noticed that `aura -Ayu --devel -x`always creates a new bare clone somewhere below `/var/cache/pacman/pkg/` which seems to be deleted after the package has been built and installed.  Obviously, when you install a VCS package, you are interested in frequent updates and don't want to clone the complete repository every time.

So is there a way not to delete the clones so that a package re-install will just run `git pull` (or whatever version control tool) in the existing clone instead of cloning anew?

**Comment by fosskers** [comment]
This would be ideal, but hasn't been implemented yet.

**Comment by jared-w** [comment]
Just out of curiosity, why is this wont-fix, @fosskers? It's something I sorely miss. Especially if I'm updating 25+ git packages and after building every single one from scratch, only 2 actually end up being installed due to the rest already being up to date.

**Comment by fosskers** [comment]
Oh, that sounds annoying. Luckily now there's a feature in the soon-to-be-released Aura 2 (i.e. the changes are already in `master`) that won't rebuild packages that already have their exact version in the cache.

A quick test on one of my own `-git` packages didn't work, so I will look into that and get back to you.

**Comment by fosskers** [comment]
Nevermind, it was a anomaly of me having the most recent version installed, yet somehow that wasn't present in my cache! So, everything does actually work as expected - if you do a `aura -Au --devel`, all your `*-git`-like packages will be queued for an update, but they won't be rebuilt if you already have the most recent version as reported by the AUR.

**Comment by tsdh** [comment]
@fosskers Well, still just the repeated cloning might take a while.  For example, consider you have a package cloning a custom linux kernel tree.

What's the problem with just keeping the checkouts and updating them instead of cloning anew?  Yaourt has this feature for example.  There you have to define some VCSDIR or something, and if that exists it'll place checkouts there and update them if they already exist.

**Comment by fosskers** [comment]
If you're already up-to-date, nothing will be cloned. If you're indeed installing a new version, it does `git clone --depth 1`. Is that still unreasonably long?

**Comment by tsdh** [comment]
@fosskers I guess we have  a different opinion what up-to-date means in the context of a VCS-based package.

- In your view, I'm up-to-date when the version of the installed package matches the latest version available in the AUR.
- In my view, I'm up-to-date when the package is built with the latest upstream sources, so `some-app-git-1` from yesterday and `some-app-git-1` from today might differ.

Therefore, I always use `--force` because there could be some new commits upstreams.  With yaourt, if you configure that VCS checkouts are not deleted, it'll run a `git pull` (or whatever) in there, and only rebuild if there is a new commit on the branch.  Else it tells you that you are really up-to-date.
With aura, I can't even tell if a forced build is different from a previous build.

**Comment by fosskers** [comment]
It's true that Aura doesn't currently manage / save git-based code sources. For the time being, I'll reopen this.

**Comment by fosskers** [comment]
Thanks for your patience, this will be included in the upcoming release.
