### ISSUE TITLE
Aura 2 release tag for AUR?

### ISSUE THREAD

**Issue by leshow** [fosskers/aura#489]
Thank you so much for your continued work maintaining and improving this piece of software. I see you've finished your v2 milestones and closed many bugs. Is there a release of v2 available? I'm installing from AUR and the only version available there is 1.4, whereas if I was to build from source, I'd be building v2 I think.

Are there plans to tag a v2 release so it can be built from AUR?

**Comment by fosskers** [comment]
Very soon! I'm not *quite* done with improvements.

**Comment by AladW** [comment]
You're sure that's a realistic assement? That be'd like replicating both `shellcheck` and an anti-virus client in an AUR helper. (I nearly had an aneurysm writing this sentence)

**Comment by fosskers** [comment]
At the moment, it's perfect bash parsing thanks to [language-bash](https://hackage.haskell.org/package/language-bash) and traversal of the parsed AST to detect black-listed terms.

I've flirted with jailing builds somehow, but decided not to include that in 2.0.

**Comment by fosskers** [comment]
@knrafto asserts that `language-bash` should parse any bash we could throw at it - but in the event that it can't for some given PKGBUILD, that's good information too. What wizardry are they attempting such that the parser breaks? PKGBUILDs in general shouldn't require advanced bash.

**Comment by leshow** [comment]
Detecting malicious behaviour would be a wonderful feature. Can't wait to use v2!

**Comment by fosskers** [comment]
Soon :)

**Comment by AladW** [comment]
Are there some binaries from git master we can test? That or a better AUR package - the current requires building over 100 Haskell libraries and takes longer to build than Arch's Linux kernel. :confused:

**Comment by fosskers** [comment]
Very soon.

**Comment by kgizdov** [comment]
@AladW I've been using the `stack` builds which are very quick for me (on my laptop).
@fosskers I've been using the master branch for a while now and I'm very happy with it. To be honest, after you finish #511 I don't see anything else that would bother me as a user. So maybe you can push something as an `aura-bin-git` package to have people enjoy it while you finish up improving the code.

**Comment by beatgammit** [comment]
I'd love to have an updated AUR package even righ without #511. I have random issues with the current aura, so I've been building a lot of packages with makepkg. I'd love to play with this release, and updating the package will make it easier for me and others to do so.

**Comment by fosskers** [comment]
Aura 2 is already on Hackage, it's just a matter of packaging things up nicely for the AUR.

**Comment by beatgammit** [comment]
Any update on this?

**Comment by fosskers** [comment]
Thanks!

**Comment by beatgammit** [comment]
Sorry to be *that guy*, but is there any update on this? I'm having issues installing random AUR packages, and would prefer to try them out on the new release instead of adding bugs for the current release.

I hope the new job is working out!

**Comment by fosskers** [comment]
Blah, forgive me for also being *that guy* (in the other direction) and not getting off my ass to release this.

**Comment by fosskers** [comment]
Done a while ago!
