### ISSUE TITLE
aur-security: ability to check local PKGBUILD

### ISSUE THREAD

**Issue by maximbaz** [fosskers/aura#509]
I'd like to use `aur-security` to check PKGBUILD on local file system.

Here's the basic need:

1. Accept path to folder with PKGBUILD via CLI argument, e.g. `$ aur-security --path /tmp/mypackage/`
2. Return 0 exit code if no security issues are found and non-zero exit code if there are issues
3. Print the list of issues on stdout

If it's not too much trouble to maintain yet another AUR package, consider publishing this tool separately as `aur-security-bin`, otherwise just bundle it together with `aura-bin`.

Initial discussion started here: https://github.com/aurapm/aura/pull/508#issuecomment-419677661

**Comment by fosskers** [comment]
I will tackle this as soon as I can. The Aura 2.0 release comes first, of course, but that's [on it's way](http://hackage.haskell.org/package/aura-2.0.0).

**Comment by fosskers** [comment]
I'm going to implement this directly in Aura via a new `-P` command.

**Comment by fosskers** [comment]
Hi there, this is finally complete. I'm sorry that "as soon as I can" became a year and a half. 

I've put the requested functionality into the `-P` command, directly in Aura:
  - `-Pf` accepts a path to a PKGBUILD.
  - `-Pd` accepts a path to a directory containing a PKGBUILD.
  - `-P` on its own will read from stdin. Combine this with `-Ap` to pull from the AUR:
```
> aura -Ap myget | aura -P

    sudo pacman -S aurvote

aura >>= sudo indicates that someone may be trying to gain root access to your machine.
aura >>= Potential PKGBUILD vulnerabilities detected.
```
