### ISSUE TITLE
Mix in implicit Prelude

### ISSUE THREAD

**Issue by fosskers** [fosskers/aura#518]
To avoid needing to explicitely import `BasePrelude` into every module, consider this: https://www.reddit.com/r/haskelltil/comments/9qa366/easy_way_to_replace_default_prelude_with_the/

It would probably mean switching to an explicit `.cabal` file, and pinning `cabal-version` to `2.2`. Can hpack handle mixins?

**Comment by jared-w** [comment]
[Looks like hpack can handle mixins as of v0.31.0](https://www.reddit.com/r/haskelltil/comments/9qa366/easy_way_to_replace_default_prelude_with_the/e8ji3vv/)

**Comment by fosskers** [comment]
Nice find!
