### ISSUE TITLE
Fakeroot as dependency

### ISSUE THREAD

**Issue by leliamesteban** [fosskers/aura#525]
Cannot compile without fakeroot. It should be listed as a dependency

**Comment by fosskers** [comment]
Can you elaborate?

**Comment by leliamesteban** [comment]
Sure, sorry

I followed the instructions in the readme for the manual installation on a fresh Arch installation and it wouldn't compile unless I installed fakeroot. I assumed from this that fakeroot is a dependency for aura so it should be made explicit.
Is that ok?

**Comment by AladW** [comment]
Every AUR user is expected to have `base-devel` installed, of which `fakeroot` is part.
