### ISSUE TITLE
Test failure on NixOS

### ISSUE THREAD

**Issue by nh2** [fosskers/aura#526]
In [`static-haskell-nix`](https://github.com/nh2/static-haskell-nix/) I see the following test failure of `aur` `6.1.0`, only when I run on a proper NixOS machine with sandboxing enabled (not when running nix on Ubuntu without sandbox):

```
[1 of 1] Compiling Main             ( tests/Test.hs, dist/build/aur-test/aur-test-tmp/Main.o )
Linking dist/build/aur-test/aur-test ...
running tests
Running 1 test suites...
Test suite aur-test: RUNNING...
RPC Calls
  info on existing package:    FAIL (5.03s)
    tests/Test.hs:21:
    expected: Just True
     but got: Nothing
  info on nonexistant package: FAIL (5.03s)
    tests/Test.hs:24:
    expected: Just True
     but got: Nothing
  search:                      FAIL (5.03s)
    tests/Test.hs:27:
    Good search

3 out of 3 tests failed (5.03s)
Test suite aur-test: FAIL
Test suite logged to: dist/test/aur-6.1.0-aur-test.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for '/nix/store/q4m2k9vahqaa803i39h5h8j594mxr85h-aur-6.1.0.drv' failed with exit code 1
```

What might be reasons for this?

Could it be that the `aura` executable is called but not seen in the sandbox because it isn't a properly-declared runtime dependency somehow?

**Comment by nh2** [comment]
`strace -fye execve nix-build /nix/store/q4m2k9vahqaa803i39h5h8j594mxr85h-aur-6.1.0.drv`:

```
[pid  2015] execve("dist/build/aur-test/aur-test", ["dist/build/aur-test/aur-test"], 0x4200081770 /* 122 vars */) = 0
strace: Process 2018 attached
strace: Process 2023 attached
strace: Process 2022 attached
strace: Process 2020 attached
strace: Process 2017 attached
strace: Process 2016 attached
strace: Process 2019 attached
strace: Process 2021 attached
strace: Process 2024 attached
strace: Process 2034 attached
strace: Process 2032 attached
strace: Process 2031 attached
strace: Process 2033 attached
strace: Process 2035 attached
strace: Process 2036 attached
strace: Process 2037 attached
strace: Process 2039 attached
strace: Process 2038 attached
strace: Process 2040 attached
strace: Process 2042 attached
strace: Process 2041 attached
[pid  2039] +++ exited with 0 +++
[pid  2031] +++ exited with 0 +++
[pid  2024] +++ exited with 0 +++
[pid  2033] +++ exited with 0 +++
[pid  2041] +++ exited with 0 +++
[pid  2017] +++ exited with 0 +++
[pid  2040] +++ exited with 0 +++
[pid  2034] +++ exited with 0 +++
[pid  2018] +++ exited with 0 +++
[pid  2042] +++ exited with 0 +++
[pid  2035] +++ exited with 0 +++
[pid  2019] +++ exited with 0 +++
[pid  2020] +++ exited with 0 +++
[pid  2036] +++ exited with 0 +++
[pid  2037] +++ exited with 0 +++
[pid  2021] +++ exited with 0 +++
[pid  2038] +++ exited with 0 +++
[pid  2022] +++ exited with 0 +++
[pid  2016] +++ exited with 0 +++
[pid  2032] +++ exited with 0 +++
[pid  2023] +++ exited with 0 +++
[pid  2015] +++ exited with 1 +++
[pid  2014] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=8576, si_uid=1000, si_status=1, si_utime=6, si_stime=1} ---
RPC Calls
  info on existing package:    FAIL (5.03s)
    tests/Test.hs:21:
    expected: Just True
     but got: Nothing
  info on nonexistant package: FAIL (5.01s)
    tests/Test.hs:24:
    expected: Just True
     but got: Nothing
  search:                      FAIL (5.01s)
    tests/Test.hs:27:
    Good search

3 out of 3 tests failed (5.03s)
```

This suggests that it didn't try to `execve` anything; perhaps the test suite checks something else first?

**Comment by fosskers** [comment]
Is this still an issue?

**Comment by nh2** [comment]
Yes, this still fails with `aur-6.1.0.1`.

Was there any code change that would suggest this would not fail any more?

In general, I would recommend making whatever function returns `Nothing` here return an `Either` so that it is shown what the problem is.

I also still recommend to put your packages on Stackage, because currently `aur` doesn't compile in nixpkgs because it has `aur-6.1.0` which has a cabal bounds problem, and I had to manually override its `src` to check its state. This would not be necessary if `aur*` was on Stackage, as then the version that's in nixpkgs would be guaranteed to not have these problems.

**Comment by fosskers** [comment]
Yes, I've been planning to update the list of my packages that are in Stackage. I recently went through the lot of them and made sure their bounds all made sense, so the next step should be easy.

**Comment by fosskers** [comment]
I've published `aur-6.2.0`. We'll see what happens.

I'll also get my Stackage packages up to date soon.

**Comment by fosskers** [comment]
https://github.com/commercialhaskell/stackage/pull/4574

**Comment by fosskers** [comment]
The above PR was just merged.

**Comment by nh2** [comment]
Nice! With the next update to `nixpkgs`'s `haskellPackages`, aura should be easily statically built via `static-haskell-nix`.

**Comment by fosskers** [comment]
Although I did not submit `aura` itself to Stackage, only one of its sublibs, `aur`.

**Comment by nh2** [comment]
I think so. The more is on there, the more the tooling will get you for free :)

**Comment by fosskers** [comment]
Cool. I'll do that once I release `2.0.1`.

**Comment by fosskers** [comment]
I believe we fixed this.
