### ISSUE TITLE
Setting PACMAN environment variable to `aura` cause fork bomb

### ISSUE THREAD

**Issue by damienflament** [fosskers/aura#527]
As stated by the [makepkg manual page](https://www.archlinux.org/pacman/makepkg.8.html#_environment_variables), the `PACMAN` environment variable is used to tell `makepkg` to use a different package manager than `pacman`.

But setting it to `aura` makes aura itself create a infinite amount of sub-processes.

### Steps to reproduce

```console
> export PACMAN=aura
> aura -Sy
```

### Expected result

```console
> aura -Sy
error: you cannot perform this operation unless you are root.
aura >>= Please check your input.
```

### Actual result

Output from Htop:

```console
└─ zsh
   └─ aura -Sy
      └─ aura -S -y
         └─ aura -S -y
            └─ aura -S -y
               └─ aura -S -y
                  └─ aura -S -y
                     └─ aura -S -y
                        └─ aura -S -y
                           └─ aura -S -y
                              └─ aura -S -y
                                 └─ ...
```

### Note

Performing this action while being root works perfectly:

```console
> export PACMAN=aura
> sudo aura -Sy
In order to do as root, please give its password:
:: Synchronizing package databases...
```

### Environment
| Package | Version |
| ------  | ------: |
| pacman  |  5.1.3  |
| libalpm | 11.0.3  |
| aura    |  1.4.0  |
| zsh     |  5.7.1  |

**Comment by fosskers** [comment]
Nice corner case you've found! `aura` definitely expects `PACMAN` to be `pacman`, which we should document in the README.

**Comment by damienflament** [comment]
@fosskers
> `aura` definitely expects `PACMAN` to be `pacman` 

It can be problematic. I set `PACMAN` to `aura` in my shell profile in order to make `makepkg` use aura instead of pacman.

Why not ignore the `PACMAN` environment variable ? Or, if `makepkg` is used by `aura`, set the `PACMAN=pacman` internally.

**Comment by fosskers** [comment]
> ... in order to make makepkg use aura instead of pacman.

What's the specific use-case, here?

**Comment by damienflament** [comment]
I was thinking about using `powerpill` automatically when `makepkg` download dependencies (while building packages locally). But this use case should be easily covered by setting `PACMAN=powerpill`.

**Comment by fosskers** [comment]
Is this still an issue for you?

**Comment by fosskers** [comment]
Please feel free to reopen if this is still an issue for you.
