### ISSUE TITLE
Dependencies for building aura is not clearly listed

### ISSUE THREAD

**Issue by Ciantic** [fosskers/aura#540]
The instructions at the README does not list the dependencies (file, binutils, awk and fakeroot).

I have found them, but I think they should be listed, here is my docker image at the moment:

```Dockerfile
FROM archlinux/base as aurabin

RUN pacman --noconfirm -Syu git sudo binutils fakeroot file awk
RUN useradd builduser -m
RUN sudo -u builduser bash -c 'cd ~ && git clone https://aur.archlinux.org/aura-bin.git aura-pkgbuild'
RUN sudo -u builduser bash -c 'cd ~/aura-pkgbuild && makepkg -s --noconfirm'

# Example for a clean archlinux/base with just aura added, e.g. installing haskell-ide-engine
FROM archlinux/base
COPY --from=aurabin /home/builduser/aura-pkgbuild/pkg/aura-bin/ /
RUN pacman --noconfirm -Syu sudo
RUN sudo aura --noconfirm -A haskell-ide-engine
```

Above image is a good aura starting point image, because it builds aura and copies just it to the new fresh image.

**Comment by fosskers** [comment]
It's not enough for `pacman` to be installed?

**Comment by Ciantic** [comment]
@fosskers I don't know. But back then I could not get aura installed with just pacman.

**Comment by fosskers** [comment]
Ah, `aura` isn't available from the official repos. None of the "AUR Helpers" are, actually. You'd have to clone the [`aura-bin`](https://aur.archlinux.org/packages/aura-bin/) package and do `makepkg` manually. Make sure you have `base-devel` installed too!

**Comment by fosskers** [comment]
You'll also need to have made a non-root user, since `makepkg` can't be ran as `root`.

**Comment by fosskers** [comment]
... and it seems like the Arch docker image doesn't set the `USER` env variable, which `aura` requires to run.

**Comment by fosskers** [comment]
Any luck?

**Comment by Ciantic** [comment]
Sir, it works with my original Dockerfile, but it requires those dependencies I listed.

**Comment by fosskers** [comment]
Right, then our finding match up. Depending on `base-devel` would probably be easier than listing most of those individually, too.
