### ISSUE TITLE
Issues with multiple package selection 

### ISSUE THREAD

**Issue by ghost-420** [fosskers/aura#541]
![aura](https://user-images.githubusercontent.com/29991266/62820779-d1a0c000-bb58-11e9-88a6-70de2ef17b0f.png)

List from Aura is likely inaccurate, judging off what pacman outputted.
Kwin-lowlatency only adds a build requirement for git, compared to kwin.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kwin-lowlatency
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/kwin

---
The selection is confusing, and appears to be non-responsive since >> doesn't move. Going a newline too far will accidentally abort installation.

This is what I had in mind for selection, focused on taking advantage of horizontal space.
```
aura >>= Determining dependencies...

2 providers available for qt5-sensors, xcb-util-cursor, qt5-tools, extra-cmake-modules
1 - Repository world, 2 - Repository extra

2 providers available for example-dependency
1 - Repository world, 2 - Repository gremlins

(Default is 1, 1, 1, 1) >> 2, 1, 2, 1
(Default is 1) >> 2
```
** You can do 2,1,2,1 if desired, spaces aren't required.

**Comment by fosskers** [comment]
Ah ha, this finally became a problem. Alright, I know what the fix is.

**Comment by fosskers** [comment]
Oh wait a minute, it's quite strange that you're given the same selection twice. At any rate, dependency solving currently works for `kwin-lowlatency`. I'll have to try and reproduce this issue another way.
