### ISSUE TITLE
Cannot run aura from root w/ sudo as user who can sudo...

### ISSUE THREAD

**Issue by f0ff886f** [fosskers/aura#556]
This might be the wrong way of holding aura, but this worked OK for aurget :)

```bash
root@box ~# sudo -u someuser aura -Au
aura >>= As of makepkg v4.2, building as root is no longer possible.
root@box ~# 
```

Where someuser is in the sudoers, and aura works fine from a shell under that user:
```bash
[somuser@box ~]$ sudo aura -Au
aura >>= Fetching package information...
aura >>= Comparing package versions..
...
```

Is there a way to launch aura from a root shell? It's just a convenience thing, no worries if not.

**Comment by fosskers** [comment]
By design, this is unfortunately not possible. Non-installation commands (say like `-Ai`) work fine, but anything permanent that requires `sudo` is blocked.
