### ISSUE TITLE
Add manually installed package to aura

### ISSUE THREAD

**Issue by mb720** [fosskers/aura#564]
Hi!

Thanks a lot for aura, I love your software! 👍

I have installed a package from AUR without aura, using `git clone` and `makepkg -cs && sudo pacman -U *.xz`.

Afterwards, I've installed aura and would now like to integrate that package with aura. For example to have the package updated when calling `aura -Au`.

Is there a way to do this?

**Comment by fosskers** [comment]
It already should be! Does the package appear when you do `aura -Qm`? If so, then Aura can see it, and will attempt to update it when you do `-Au`.

**Comment by mb720** [comment]
Oh wow, it does show up! :-)
Thanks for clearing this up and thanks again for your great work!

**Comment by fosskers** [comment]
My pleasure, please let me know if anything else comes up.
