### ISSUE TITLE
Seems that aura -Sc doesn't work.

### ISSUE THREAD

**Issue by Quadronick** [fosskers/aura#575]
**Expected Behavior:**
`aura -Sc` will remove all files in `/var/cache/pacman/pkg`

**Current Behavior:**
`aura -Sc` prints `removing old packages from cache...` but they are still there.

**Steps to Reproduce:**
1. aura -Syu
2. aura -Sc
3. ls /var/cache/pacman/pkg
4. done

**Context (Environment):**
pacman: 5.2.1
aura: 2.0.2
linux: 5.5.6

**Comment by fosskers** [comment]
Can you try the latest version, `2.2.1`?

**Comment by Quadronick** [comment]
Hi. Sure.

**Comment by Quadronick** [comment]
I still can reproduce it even in version 2.2.1.

**Comment by fosskers** [comment]
Can you paste the exact output from the terminal? I'd like to see what you see.

**Comment by Quadronick** [comment]
`➜ aura -Syu
[sudo] password for quad: 
aura >>= Saved package state.
:: Synchronizing package databases...
 core is up to date
 extra                                 1642.8 KiB  1286 KiB/s 00:01 [#####################################] 100%
 community                                4.8 MiB  1283 KiB/s 00:04 [#####################################] 100%
 multilib is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) libinput-1.15.3-1

Total Download Size:   0.23 MiB
Total Installed Size:  0.88 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
warning: no /var/cache/pacman/pkg/ cache exists, creating...
:: Retrieving packages...
 libinput-1.15.3-1-x86_64               239.7 KiB  2.13 MiB/s 00:00 [#####################################] 100%
(1/1) checking keys in keyring                                      [#####################################] 100%
(1/1) checking package integrity                                    [#####################################] 100%
(1/1) loading package files                                         [#####################################] 100%
(1/1) checking for file conflicts                                   [#####################################] 100%
(1/1) checking available disk space                                 [#####################################] 100%
:: Processing package changes...
(1/1) upgrading libinput                                            [#####################################] 100%
:: Running post-transaction hooks...
(1/2) Reloading device manager configuration...
(2/2) Arming ConditionNeedsUpdate...

➜ aura -Sc 
Packages to keep:
  All locally installed packages

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove all other packages from cache? [Y/n] 
removing old packages from cache...

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] 
removing unused sync repositories...


➜ ls -la /var/cache/pacman/pkg/
total 240
drwxr-xr-x 2 root root     50 Mar  8 17:50 .
drwxr-xr-x 3 root root     17 Mar  8 17:50 ..
-rw-r--r-- 1 root root 245422 Mar  7 23:59 libinput-1.15.3-1-x86_64.pkg.tar.zst
`

**Comment by Quadronick** [comment]
WAIDW?

**Comment by fosskers** [comment]
What's all this about?
```
warning: no /var/cache/pacman/pkg/ cache exists, creating...
```
Do you have a special cache location set in your `pacman.conf`?

**Comment by Quadronick** [comment]
I just removed that dir before updating for clean experiment. 
It was created but not cleaned with -Sc key.

**Comment by fosskers** [comment]
Gotcha, thanks for the data. I'll do some investigation.

**Comment by fosskers** [comment]
Is this still an issue for you?

**Comment by Quadronick** [comment]
```~ took 4s 
➜ ll /var/cache/pacman/pkg 
total 30M
-rw-r--r-- 1 root root 1.8M Apr 29 15:44 glslang-8.13.3743-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 217K Mar 30 17:01 ldb-1:2.1.1-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 188K Apr 29 17:37 libplacebo-1.29.1-3-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 2.6M Apr 29 16:33 libva-mesa-driver-20.0.5-3-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root  14M Apr 29 16:33 mesa-20.0.5-3-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 1.3M Apr 29 17:40 mpv-1:0.32.0-4-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 285K Feb 25 00:18 python-astroid-2.3.3-2-any.pkg.tar.zst
-rw-r--r-- 1 root root  63K Oct 31 20:45 python-isort-4.3.21.2-3-any.pkg.tar.xz
-rw-r--r-- 1 root root  23K Nov  6 12:07 python-lazy-object-proxy-1.4.3-1-x86_64.pkg.tar.xz
-rw-r--r-- 1 root root  14K Nov  4 00:15 python-mccabe-0.6.1-4-any.pkg.tar.xz
-rw-r--r-- 1 root root 437K Nov 15 09:07 python-pylint-2.4.4-1-any.pkg.tar.xz
-rw-r--r-- 1 root root  44K Mar  9 13:49 python-wrapt-1.12.1-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 125K Apr 29 17:19 shaderc-2020.0-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 6.3M Apr 17 22:31 smbclient-4.12.1-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 1.4M Apr 26 13:55 texinfo-6.7-3-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 112K Apr 29 12:52 vulkan-icd-loader-1.2.137-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 1.6M Apr 29 16:34 vulkan-radeon-20.0.5-3-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root  46K Feb 19 02:11 whois-5.5.6-1-x86_64.pkg.tar.zst

~ 
➜ aura -Sc
Packages to keep:
  All locally installed packages

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove all other packages from cache? [Y/n] Y
removing old packages from cache...

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] Y
removing unused sync repositories...

~ took 2s 
➜ ll /var/cache/pacman/pkg
total 30M
-rw-r--r-- 1 root root 1.8M Apr 29 15:44 glslang-8.13.3743-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 217K Mar 30 17:01 ldb-1:2.1.1-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 188K Apr 29 17:37 libplacebo-1.29.1-3-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 2.6M Apr 29 16:33 libva-mesa-driver-20.0.5-3-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root  14M Apr 29 16:33 mesa-20.0.5-3-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 1.3M Apr 29 17:40 mpv-1:0.32.0-4-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 285K Feb 25 00:18 python-astroid-2.3.3-2-any.pkg.tar.zst
-rw-r--r-- 1 root root  63K Oct 31 20:45 python-isort-4.3.21.2-3-any.pkg.tar.xz
-rw-r--r-- 1 root root  23K Nov  6 12:07 python-lazy-object-proxy-1.4.3-1-x86_64.pkg.tar.xz
-rw-r--r-- 1 root root  14K Nov  4 00:15 python-mccabe-0.6.1-4-any.pkg.tar.xz
-rw-r--r-- 1 root root 437K Nov 15 09:07 python-pylint-2.4.4-1-any.pkg.tar.xz
-rw-r--r-- 1 root root  44K Mar  9 13:49 python-wrapt-1.12.1-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 125K Apr 29 17:19 shaderc-2020.0-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 6.3M Apr 17 22:31 smbclient-4.12.1-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 1.4M Apr 26 13:55 texinfo-6.7-3-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 112K Apr 29 12:52 vulkan-icd-loader-1.2.137-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 1.6M Apr 29 16:34 vulkan-radeon-20.0.5-3-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root  46K Feb 19 02:11 whois-5.5.6-1-x86_64.pkg.tar.zst

~ 
➜ 
```

Aura v 2.3.0

Yes, it is still here.

**Comment by fosskers** [comment]
Thanks.

**Comment by fosskers** [comment]
```
colin@yumi ~/c/h/aura (master) [1]> ls /var/cache/pacman/pkg | wc -l
3120
colin@yumi ~/c/h/aura (master)> sudo aura -Sc
[sudo] password for colin: 
Packages to keep:
  All locally installed packages

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove all other packages from cache? [Y/n] 
removing old packages from cache...
error: missing package metadata in /var/cache/pacman/pkg/mpv-1:0.32.0-1-x86_64.pkg.tar.zst.part

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] 
removing unused sync repositories...
colin@yumi ~/c/h/aura (master)> ls /var/cache/pacman/pkg | wc -l
1165
```
This seems to work as expected. Notice the line in both of our outputs:
```
Packages to keep:
  All locally installed packages
```
So, as long as we have packages installed, this directory will never truly be empty. I believe `-Scc` does a complete clean.

**Comment by Quadronick** [comment]
I'll double check this.

**Comment by Quadronick** [comment]
Yeah. The issue is solved. Thank you!

**Comment by fosskers** [comment]
Excellent, thanks!
