### ISSUE TITLE
aura -Ay not working

### ISSUE THREAD

**Issue by sridhars** [fosskers/aura#578]
aura version 2.2.1
Is Ay not required? Is Au sufficient (to upgrade to the latest packages). This is what I see:

linux$ sudo aura -Ay
Invalid option `-y'

Did you mean one of these?
    -d
    -i
    -p
    -s
    -u
    -w
    -q
    -a
    -x
    -k
    -h

Usage: aura ((-A|--aursync) PACKAGES | (-B|--save) | (-C|--downgrade) PACKAGES |
              (-L|--viewlog) | (-O|--orphans) | (-V|--version) | --languages |
              --viewconf |
              ((-D|--database) PACKAGES | (-F|--files) | (-Q|--query)
                [[PACKAGES]] |
                (-R|--remove) PACKAGES | (-S|--sync) [PACKAGES] | (-T|--deptest)
                PACKAGES |
                (-U|--upgrade) PACKAGES)) [--log-level debug|info|warn|error]

**Comment by fosskers** [comment]
If you want to update your snapshot of repo packages, you can do `aura -Sy` once. Something like `aura -Au` or `aura -Auax` (my favourite) will perform the actual upgrades.

Would you like `-y` to be recognized with `-A` too?

**Comment by sridhars** [comment]
Currently, -S applies to the main repos not AUR and -A only applies to AUR, not the main arch repos. Would be nice if this applied to -y as well if that makes sense.
Thank you.

**Comment by fosskers** [comment]
`-y` syncs the official package info databases, which is useful to do before doing any `-A` operation anyway. Let's keep this issue open and I'll look into allowing `-Ay` to do the helpful thing you were expecting.

**Comment by sridhars** [comment]
Makes sense to me. Thank you.

**Comment by fosskers** [comment]
The fix for this will be included in the next release.
