### ISSUE TITLE
[Enhancement] A logo and basic branding for the project

### ISSUE THREAD

**Issue by cristianovitorino** [fosskers/aura#585]
Hello again @fosskers! Here's the logo proposal I told you before, hope you like it!

I went to an overall shape of a "A", drinking from **Arch Linux** and **Aura** concepts. I tried to convey a spiritual vibe through it all, either with layered shaded blades or aura-like rims.

The `pacman` aspect was really hard to integrate because of the need to avoid copyright issues, so I decided to represent it through color.

Please click on both images to see in full size. The smaller image is so you can have a better perception of scale.

That's all I got for now. If you enjoy the work so far, I can develop a minimalist branding further, so you can use on the website you intend to make and other places.

But first let me know if you like it or not, why yes, why no, if you have any ideas, need more iterations or want me to change something on the current proposal.

**P.S.** I discovered Aura recently and fell in love with it! I've used AUR helpers since... let's just say more than 10 years :joy: from `Yaourt` (RIP) in the old days, and passing through `Yay` which is popular with kids these days. Gave `trizen` a try also. Good tools, but man **Aura** hits home : ) What a well designed piece of software. It's simple, very elegant, purposeful, cohesive, it feels like art. And code that looks and feels like art deserves a proper logo/branding : )

I wanted to contribute somehow, so take this as a _thank you_ for your awesome work.

![aura](https://user-images.githubusercontent.com/57003922/79547260-09f28980-806a-11ea-8959-96f60e774685.png)

![aura-2](https://user-images.githubusercontent.com/57003922/79547273-0e1ea700-806a-11ea-9330-d97c5af10f29.png)

**Comment by fosskers** [comment]
Wow man, fantastic!! Let me meditate on all of these... because once we pick a logo, there's almost no going back. It would be the logo likely forever.

**Comment by fosskers** [comment]
Thank you again for this. Here are my first impressions, before I forget them:

1. I like the round edges. The colours match both the Arch logo and Pacman's yellow.
2. The sharp edges feel more hostile.
3. A little too much "radiation".
4. I like the actual "aura" here! The colour white might be hard to see on many backgrounds, though.
5. The legs are a bit skinny.
6. I like the colours, but it feels "busy" somehow.
7. Nice colour, but feels a bit dim overall.

Do those thoughts help?

**Comment by cristianovitorino** [comment]
> Thank you again for this.

No problem, glad to help! : )

> Here are my first impressions, before I forget them:
> 
> 1. I like the round edges. The colours match both the Arch logo and Pacman's yellow.
> 2. The sharp edges feel more hostile.
> 3. A little too much "radiation".
> 4. I like the actual "aura" here! The colour white might be hard to see on many backgrounds, though.
> 5. The legs are a bit skinny.
> 6. I like the colours, but it feels "busy" somehow.
> 7. Nice colour, but feels a bit dim overall.

> If you put a gun to my head and said "pick one now", I'd go with (1).

:joy: 

> Do those thoughts help?

Definitely! They help a lot! Thank you! I'll see if I can improve them a bit based on your input, let's see where it takes us, I might combine 1 with 4 with a better "aura" maybe, will see.

**Comment by cristianovitorino** [comment]
Hey @fosskers Done! I tried to adapt them according to your feedback. See what you think. I forgot to mention that that inverted "V" in the middle is meant to represent both an "A" from **A**rch Linux and **A**ura : )

Click for full view.

![aura-proposal-v2](https://user-images.githubusercontent.com/57003922/79626398-4d9ad100-8106-11ea-81f1-5c586e68ad2e.png)

**Comment by cristianovitorino** [comment]
Round 3!

![aura-logo-proposal-3](https://user-images.githubusercontent.com/57003922/79681881-536ee000-81f4-11ea-8668-d29364465c0d.png)

**Comment by cristianovitorino** [comment]
Round 4!

![aura-logo-proposal-4](https://user-images.githubusercontent.com/57003922/79681886-5e297500-81f4-11ea-9526-5d7f627190e8.png)

**Comment by cristianovitorino** [comment]
OK, fifth and final round!

![aura-proposal-5](https://user-images.githubusercontent.com/57003922/79709575-e6f9ec80-8298-11ea-94dd-39445bb18795.png)

**Comment by fosskers** [comment]
Wow!! So much to consider... I'll get back to you.

**Comment by cristianovitorino** [comment]
> Wow!! So much to consider... I'll get back to you.

Haha take your time : ) 

And please don't feel obligated to do feedback on each and every one of them, pick what most interests you, what makes most sense, what you **feel** that matches Aura and is deserving of representing it, and we can move forward from there.

**Comment by fosskers** [comment]
(2) and (3) of Round 5 are calling to me. (2) has the aura, but (3) has the Arch colours. Is there a way to combine the two?

**Comment by cristianovitorino** [comment]
> (2) and (3) of Round 5 are calling to me. (2) has the aura, but (3) has the Arch colours. Is there a way to combine the two?

For sure! Like this? On the right is the official Arch Linux HEX colors, on the left is my custom colors from previous iterations.

#round6

![aura-logo-proposal-6](https://user-images.githubusercontent.com/57003922/79772029-f6634f00-8305-11ea-9492-884ba248c254.png)

**Comment by cristianovitorino** [comment]
Round 7.

More radiance, **_very_** aura like, more intense.

![aura-logo-proposal-7](https://user-images.githubusercontent.com/57003922/79773689-227fcf80-8308-11ea-9d49-b06615cca605.png)

**Comment by fosskers** [comment]
In terms of the aura, I think the Round 6 ones looks better. There seems to be something significant about the aura itself only appearing on the outside.

**Comment by cristianovitorino** [comment]
> In terms of the aura, I think the Round 6 ones looks better. There seems to be something significant about the aura itself only appearing on the outside.

I see. Again, take your time, let me know if you need some more tweaks in any of the proposals to help you reach a eventual final decision.

**Comment by cristianovitorino** [comment]
And please feel free to reject all of them if you feel like it. No point in adopting something that you don legitimately enjoy and don't represent your project well. If that becomes the case, please let me know why, sometimes what you get it's not the right artist/style for the job, happens, normal.

I really don't mind, I'm having fun on my free time on this quarantine, plus this will be nice pieces for my portfolio : )

**Comment by fosskers** [comment]
I think Round 6, top-left and middle-left are the best. I'd consider those the same actual logo - since who knows what background the logo itself will be placed on.

**Comment by cristianovitorino** [comment]
> I think Round 6, top-left and middle-left are the best. I'd consider those the same actual logo - since who knows what background the logo itself will be placed on.

Cool. BTW, top-left and bottom-left are exactly the same, but in different backgrounds. I think what you may want in fact is middle-left. I can work on that and make everything inside transparent, so it can fit any background, since the actual content would be always this hot blue.

Here's a quick mockup to giver perspective:

![aura-mockup](https://user-images.githubusercontent.com/57003922/79820585-fcd3e400-8362-11ea-886d-5410a38c4648.png)

**Comment by fosskers** [comment]
What does it look like if we reduce the flare a little bit?

**Comment by cristianovitorino** [comment]
> What does it look like if we reduce the flare a little bit?

Radiance -50%:

![aura-73hdf](https://user-images.githubusercontent.com/57003922/80055706-badca680-84f8-11ea-94bc-f85da0c0e5ab.png)

**Comment by fosskers** [comment]
Lots to choose from once again, thank you!

**Comment by cristianovitorino** [comment]
> Lots to choose from once again, thank you!

No problem! I'm aware that that's bad design, giving too many options, but I think I'm finally happy with the iterations and will focus only on changes for the existing proposals from now on, if you need it.

**Comment by fosskers** [comment]
I like the top one after all, but with perhaps a flare amount between this and what it used to be.

**Comment by cristianovitorino** [comment]
> I like the top one after all, but with perhaps a flare amount between this and what it used to be.

That would be a radiance of about -75%. Gonna produce it and make a side-by-side comparison with the other amounts for comparison.

> What will happen once I "accept"? I assume you'll have a range of dimensions to choose from [...]

I'll PR a folder into the project containing a SVG of the chosen logo and whatever standalone PNGs you require, any sizes you require.

[...] and of course I'll be crediting you in both the README and in Aura's soon-to-be website.

Thank you, appreciate that : )

**Comment by cristianovitorino** [comment]
- Left: 100%
- Middle: 75%
- Right: 50%

![c84f](https://user-images.githubusercontent.com/57003922/80173267-aa463200-85c5-11ea-859d-16a299c39ee8.png)

**Comment by fosskers** [comment]
I take it back! 100% flare (especially when the image is small) looks the best. Let's go with that one! Finalized!

**Comment by cristianovitorino** [comment]
> I take it back! 100% flare (especially when the image is small) looks the best. Let's go with that one! Finalized!

Cool! How many PNG sizes do you need?

**Comment by fosskers** [comment]
Forgive me for being inexact:

- Favicon size
- Smallish for the topbar of a website
- Mediumish for the top of a README
- Huge, just in case

**Comment by cristianovitorino** [comment]
> Forgive me for being inexact:
> 
> * Favicon size
> * Smallish for the topbar of a website
> * Mediumish for the top of a README
> * Huge, just in case

Done! [PR is ready](https://github.com/fosskers/aura/pull/588).

**Comment by fosskers** [comment]
Merged!
