### ISSUE TITLE
ResponseTimeoutDefault for any aur.archlinux.org requests

### ISSUE THREAD

**Issue by ellsclytn** [fosskers/aura#594]
Tried a few different commands, all giving a similar body:

```
$ sudo aura -Ax zoxide
[sudo] password for ellis:
aura: HttpExceptionRequest Request {
  host                 = "aur.archlinux.org"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/rpc"
  queryString          = "?v=5&type=info&arg%5B%5D=zoxide"
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 ConnectionTimeout
```

Also `sudo aura -Aux`, `sudo aura -As zoxide` were attempted, all giving similar timeouts. Using the error info, I was able to recreate the requests in Curl and Firefox, which both resolved fine, leaving me to believe it's something going on with Aura.

Any chance you'd be able to help me look into this?

**Comment by fosskers** [comment]
Hi there, thanks for reporting. What version of Aura are you using?

**Comment by ellsclytn** [comment]
Knew I forgot something important: `2.3.0`

**Comment by fosskers** [comment]
Hm...
```
colin@yumi ~/c/g/active (master)> sudo aura -Ax zoxide
[sudo] password for colin: 
aura >>= Determining dependencies...
aura >>= AUR Packages:
zoxide
aura >>= Continue? [Y/n] n
aura >>= Installation manually aborted.
```
Let me look into what the default timeout is. Perhaps you're legitimately hitting it.

**Comment by ellsclytn** [comment]
I've no idea what changed (given I've performed no package updates on my system, nor messed with my env), but it's suddenly working again! Thanks nonetheless for the quick responses.

**Comment by fosskers** [comment]
Ah, ok! Cheers!

**Comment by ronanyeah** [comment]
I've been getting this for a few days. Got a successful response last night, but the timeouts are back today. Curl-ing the url works ok.
`$ curl "https://aur.archlinux.org/rpc?v=5&type=info&arg%5B%5D=aura-bin"`

**Comment by fosskers** [comment]
Perhaps this was the cause? https://lists.archlinux.org/pipermail/aur-general/2020-July/035838.html

**Comment by ronanyeah** [comment]
Yeah maybe, though not sure why curl consistently works.

**Comment by ronanyeah** [comment]
I see. Well thank you for the responses, and thanks for making the project. :+1:

**Comment by JackCuthbert** [comment]
Sorry to necro an old issue again but interestingly this is happening for me again but on one system and not another. Both on the same network with the same kernel version (5.11.5-arch1-1), aura version (3.2.4), and both use systemd networking. The difference between the 2 machines is one is a desktop with wired network (_not_ working) the other is a laptop on wifi (working).

**Comment by fosskers** [comment]
@JackCuthbert By next week I will have advanced Aura's [Rust port](https://github.com/fosskers/aura/pull/671) to the point of communicating with the AUR. All such interaction will be through Rust's `curl` library, which if my statement above was correct, should solve this issue "for free". When I get to that point next week, would you be interesting/willing to test it?

**Comment by fosskers** [comment]
Wait... https://bugs.archlinux.org/task/69963?project=1&order=lastedit&sort=desc

**Comment by JackCuthbert** [comment]
@fosskers

> When I get to that point next week, would you be interesting/willing to test it? I'd love to fly to Australia myself, but...

For sure!

> Wait... https://bugs.archlinux.org/task/69963?project=1&order=lastedit&sort=desc

That issue seems to occur with systemd `247.4-1`, I'm on `247.3-1` and I can resolve hosts just fine :slightly_smiling_face:

**Comment by JackCuthbert** [comment]
aaaand it's fixed... still on the systemd version above no other system changes or updates :thinking:  :thinking:  :thinking: WAT

**Comment by fosskers** [comment]
Must have been a crab pinching the fibre-optic cables on the seafloor?

**Comment by ellsclytn** [comment]
I've just had this happen to me again over the past day or two. One thing I tried was to copy the URL which Aura attempts to hit straight into my browser (Firefox), to see how it behaves. Works fine there, which leaves me wondering if AUR might be doing some user agent blocking (it works in `curl`, it does _not_ work in [xh](https://github.com/ducaale/xh), but if I manually specify a user agent header in xh, the request ends up working).

**Comment by fosskers** [comment]
Sorry about this coming up again. It won't be present in the Rust port (see my comment above).

**Comment by tau-dev** [comment]
Hi! Is the Rust port already in place in the current version(3.2.7)? I've been getting this problem for a few weeks, tcpdump suggests an incorrect checksum of 0x7a27 independent of the issued request.

**Comment by fosskers** [comment]
The Rust port isn't yet the main version, no. I'm still working on it, and it will solve all such problems as this Issue presents.
