### ISSUE TITLE
Searching doesn't handle spaces like Pacman would

### ISSUE THREAD

**Issue by Sirmentio** [fosskers/aura#599]
Hello, I've noticed a discrepency between Aura and Pacman that's somewhat handicapped my usage if I search packages with it.
For example (This is just an example, I could easily just search hedgewars), if I did ``pacman -Ss hedge wars``:
> community/hedgewars 1.0.0-62 [installed]
>     Turn-based strategy artillery game similiar to Worms
> 

This would be my output, simple enough. However, if I use something such as Aura, like, ``aura -Ss hedge wars``:

>Invalid argument `wars'
>
> 
> Usage: aura ((-A|--aursync) PACKAGES | (-B|--save) | (-C|--downgrade) PACKAGES |
>             (-L|--viewlog) | (-O|--orphans) | (-V|--version) | --languages |
>             --viewconf | ((-D|--database) PACKAGES | (-F|--files) | (-Q|--query)
>             [PACKAGES] | (-R|--remove) PACKAGES | (-S|--sync) [PACKAGES] |
>             (-T|--deptest) PACKAGES | (-U|--upgrade) PACKAGES))

I think it would be more beneficial if it worked more like Pacman, in that it could accept input such as that, in order to search through something like descriptions so one could say "turn based" instead of turn-based without having to use the exact wording for searching.

**Comment by fosskers** [comment]
Ah ha, I'd call this a bug. Should be an easy fix, which I'm going to take care of tomorrow.

**Comment by fosskers** [comment]
That's strange, my error is different:
```
colin@yumi ~> aura -Ss hedge wars
Missing:

Usage: aura ((-A|--aursync) PACKAGES | (-B|--save) | (-C|--downgrade) PACKAGES |
              (-L|--viewlog) | (-O|--orphans) | (-V|--version) | --languages | 
              --viewconf | 
              ((-D|--database) PACKAGES | (-F|--files) | (-Q|--query) 
                [[PACKAGES]] |
                (-R|--remove) PACKAGES | (-S|--sync) [PACKAGES] | (-T|--deptest)
                PACKAGES |
                (-U|--upgrade) PACKAGES)) [--log-level debug|info|warn|error]
```

**Comment by fosskers** [comment]
Fixed! This will be included in Aura's upcoming release.
