### ISSUE TITLE
--hotedit may not be used to change dependencies

### ISSUE THREAD

**Issue by ultimatespirit** [fosskers/aura#605]
It would appear that in the event a package's PKGBUILD requires dependency modifications at `aura` installation time it is not possible to do so via the `--hotedit` option. Current `aura` behaviour resolves dependencies of the specified package and proceeds to installation of any required dependencies *before* attempting to prompt the user to edit the PKGBUILD of the specified package.

While `--hotedit` is not the intended use case, it would be helpful to be able to edit a PKGBUILD's dependencies for ease of installation via `aura` directly, for example while waiting for an offending package's PKGBUILD to be updated.

Sample case: `aura -A --hotedit aura`

Expected behaviour: Being able to edit package `aura`'s PKGBUILD before hand to change a dependency (in this case `stack-bin` to `stack`) *before* dependency resolution and installation occurs.

Actual behaviour: Aura proceeds to dependency resolution, attempts to install `stack-bin`, and *then* requests if the user would like to edit the PKGBUILD of `stack-bin`.

(For what it's worth, it would appear the previous aura versions' behaviour *did* allow you to edit the PKGBUILD of the intended target first, but would silently ignore such edits / dependency specific edits, as I found out when attempting to upgrade aura in the first place)

(P.S. If there's a more intended route here, besides falling back on pure `git clone <pkglink>; <edit>; makepkg -i` that I simply missed in the documentation my apologies for the spurious issue)

**Comment by fosskers** [comment]
> For what it's worth, it would appear the previous aura versions' behaviour did allow you to edit the PKGBUILD of the intended target first, but would silently ignore such edits / dependency specific edits, as I found out when attempting to upgrade aura in the first place

Exactly. Way back in the day when I did dependency solving via PKGBUILD parsing, using `--hotedit` in the way you were trying to was possible. With Aura 2.0 the solving behaviour changed, and with it, the ability to change deps via `--hotedit` silently disappeared. 

Here's what we could do: I could introduce a few flag `--skip-dep-solving` that does what it sounds like. Then with `--hotedit` you could change whatever you want in the PKGBUILD, since in the end that's what `makepkg` cares about.

Oh and while you're here, I just updated the `aura` AUR package to fix this use with choice of `stack` dep :)

**Comment by fosskers** [comment]
The liked PR closed this issue, but do please let me know if this isn't the solution you were looking for.

`--skipdevcheck` will be included in the next release.

**Comment by ultimatespirit** [comment]
That sounds great! Thanks for the quick response :)

One question, before I come up with some specific way to test this, would editing the dependencies in this manner still allow for aura to resolve missing dependencies? For example, if for some reason you modified the dependencies, but did not actually *have* the new dependencies. My assumption here is that is *not* going to be the new behaviour, and it sounds like making that the new behaviour is probably non-trivial (as it sounds like dependency solving is no longer done via the PKGBUILD at all).

If that is *not* the case, technically that is still an "unexpected" edge case, but honestly it does sound fairly niche enough that I doubt it should be much an issue if it's indeed a non-trivial change to make. Not to mention if someone indeed knew enough to change the dependencies with aura... they could always just invoke aura before hand with the required dependencies.

P.S. Thanks for the speedy change on the AUR side too ;)

**Comment by fosskers** [comment]
>  it sounds like making that the new behaviour is probably non-trivial 

Correct. At a certain point, it becomes more efficient to just clone the AUR package manually, tweak the PKGBUILD locally, and run `makepkg -s`.
