### ISSUE TITLE
aura -A leaves built packages behind

### ISSUE THREAD

**Issue by rraval** [fosskers/aura#609]
Not sure if this is working as intended, but I'm hoping for at least a flag that makes `aura` clean up after itself.

Demonstration of the issue:

```
$ sudo pacman -Scc  # clear the built package cache
... snip output ...

$ sudo aura -A aura-bin
aura >>= Determining dependencies...
aura >>= AUR Packages:
aura-bin
aura >>= Continue? [Y/n] 
aura >>= Building aura-bin...
loading packages...
warning: aura-bin-3.1.1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) aura-bin-3.1.1-1

Total Installed Size:  25.52 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] Y
... snip output ...

$ ls -ld /tmp/aura-bin-*
drwxr-xr-x 3 rraval root 60 Jun  3 09:11 /tmp/aura-bin-4760268676474553401/

$ du -hs /tmp/aura-bin-4760268676474553401
83M	/tmp/aura-bin-4760268676474553401
```

As you can see, this leaves 83Mb behind and I've taken to manually `rm -rf` those directories to clean up.

This becomes especially cumbersome when combined with `aura -Au` and some of the larger packages on AUR (`android-studio-bin`, `slack-desktop`, etc.)

**Comment by fosskers** [comment]
This is intended, yeah. `/tmp` is cleared automatically whenever you restart your system.

**Comment by rraval** [comment]
Thanks for the response. I can appreciate having the package directory there and sometimes it's useful when `makepkg` fails.

However the combination of rare system restarts and tiny laptop SSD make this particularly bothersome.

Is there any appetite for cleanup behind a flag? If not, feel free to close this issue out and I'll look to doing cleanup in a wrapper script that invokes `aura`.

**Comment by fosskers** [comment]
Since you'd benefit from such a flag, you're probably not the only one. I'll add a `-c`/`--clean` to `-A` that deletes the entire build dir (for each package) after the built tarball has been copied.

**Comment by rraval** [comment]
I appreciate the quick turnaround, I'll bide my time till the next stable release.

Thanks for this (and `aura` in general)!
