### ISSUE TITLE
Build ignoring package cache

### ISSUE THREAD

**Issue by leshow** [fosskers/aura#619]
After an update, I sometimes need to rebuild AUR deps to get everything properly linked again. If the package is cached though, it just installs from the cache and doesn't rebuild anything. It would be helpful if I could pass a flag to have it ignore the cache and do a build.

Is there a way to do this? I looked through the readme and didn't see anything. If not, I'd be willing to do a PR if you're interested?

**Comment by fosskers** [comment]
Perhaps `--force` what do what you need?

**Comment by leshow** [comment]
Ah, I suppose that'll do it. My bad

**Comment by fosskers** [comment]
No problem, thanks for the report.
