### ISSUE TITLE
aura >>= No valid packages specified.

### ISSUE THREAD

**Issue by simonbcn** [fosskers/aura#622]
```
Pacman v5.2.2 - libalpm v12.0.2
AURA Version 3.1.6
```

```
$ sudo aura -A --sysupgrade --devel --hotedit --needed --delmakedeps --clean --diff
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
cht.sh-git
octopi-git

aura >>= Saved package state.
aura >>= No valid packages specified.
```

Those devel packages (`cht.sh-git` and `octopi-git`) are updated but first it tells me to update them and then it tells me `No valid packages specified.`.

**Comment by fosskers** [comment]
What happens when you take out `--needed`?

**Comment by simonbcn** [comment]
It doesn't alert me now about `octopi-git` because I've uninstalled. But it tries to "_upgrade_" the other git package `cht.sh-git`:

```
sudo aura -A --sysupgrade --devel --hotedit --delmakedeps --clean --diff
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
cht.sh-git

aura >>= Saved package state.
aura >>= cht.sh-git PKGBUILD changes:
aura >>= Determining dependencies...
aura >>= AUR Packages:
cht.sh-git
aura >>= Continue? [Y/n]
aura >>= Building cht.sh-git...
aura >>= Would you like to edit the PKGBUILD of cht.sh-git? [Y/n] n
loading packages...
warning: cht.sh-git-r674.38edd23-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) cht.sh-git-r674.38edd23-1

Total Installed Size:  0.02 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
....
```

**Comment by fosskers** [comment]
That's the expected behaviour of `--devel`, yeah. What kind of workflow are you looking for? It's almost certainly possible.

**Comment by simonbcn** [comment]
The application shows 2 messages that, in my opinion, are confusing or inaccurate:
```
...
aura >>= AUR Packages to upgrade:
cht.sh-git
octopi-git
...
```
In the case of AUR devel packages, before announcing them as upgradeable, wouldn't it be better to check if they really are?
     
      
```
...
aura >>= No valid packages specified.
```
Wouldn't it be better here: `there's nothing to upgrade`?

**Comment by fosskers** [comment]
Sure that's reasonable, let me take a look.

**Comment by fosskers** [comment]
It turns out that that message covers multiple scenarios, not just upgrading, so I think it's okay to leave it the way it is.

**Comment by fosskers** [comment]
I've looked back through the code. If there is an update naturally available for `-git` packages, that should be detected even without `--devel`. Adding `--devel` _forces_ those to be rebuilt, which was a requested usecase some time in the past for people wanting to, say, rebuild a kernel or driver packages they got out of the AUR.

**Comment by simonbcn** [comment]
ok, I've tested without `--devel` and `--needed`:
```
$ sudo aura -A --sysupgrade --hotedit --delmakedeps --clean --diff
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= No AUR package upgrades necessary.
```
:+1:

**Comment by fosskers** [comment]
Cool, thanks for reporting!
