### ISSUE TITLE
[Enhancement] Absence of informative messages

### ISSUE THREAD

**Issue by simonbcn** [fosskers/aura#623]
```
Arch Linux
Pacman v5.2.2 - libalpm v12.0.2
AURA Version 3.1.6
```
I've executed this:
```
$ sudo aura -A --hotedit --needed --delmakedeps --clean --diff ttf-ms-fonts
aura >>= ttf-ms-fonts has no stored PKGBUILD yet.
aura >>= Determining dependencies...
aura >>= AUR Packages:
ttf-ms-fonts
aura >>= Continue? [Y/n]
aura >>= Building ttf-ms-fonts...
aura >>= Would you like to edit the PKGBUILD of ttf-ms-fonts? [Y/n]
????????????????????????????????????
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) ttf-ms-fonts-2.0-12

Total Installed Size:  5.40 MiB

:: Proceed with installation? [Y/n]
```
At the moment of the installation that I indicate with the symbols `?` nothing is shown, it is the `makepkg` process. In this case it is a long process and (_especially for those new to this program_) gives the impression that the program has been left stuck.
I think a simple message like `aura >>= Creating the package...` would help quite a bit.

I see there is an option `--unsuppress` to show the `makepkg` output, but I don't think it would be necessary either if the running process is indicated.

On the other hand, I have a doubt, there are `PKGBUILD`s that show important messages for the user (_for example [r8168-dkms](https://aur.archlinux.org/packages/r8168-dkms/) in its `.install` file_), are they shown with `aura` without the `--unsuppress` option?

**Comment by fosskers** [comment]
`-x` (`--unsuppress`) is that option you're looking for, yeah. You're right that there are certain packages that do require mid-build interaction from the user, and that these prompts would be blocked if not using `-x`. Luckily these packages are rare enough that I think it's sufficient to ask people to use `-x` while upgrading those (or just `-x` all the time, as I do).

**Comment by simonbcn** [comment]
I think adding a message to inform that the makepkg process is running costs hardly anything.

**Comment by fosskers** [comment]
It's implied by the `aura >>= Building ttf-ms-fonts...`, wouldn't you say?

**Comment by simonbcn** [comment]
> It's implied by the `aura >>= Building ttf-ms-fonts...`, wouldn't you say?

Look at this output: 
```
$ sudo aura -A --hotedit --needed --delmakedeps --clean --diff ttf-ms-fonts
aura >>= ttf-ms-fonts has no stored PKGBUILD yet.
aura >>= Determining dependencies...
aura >>= AUR Packages:
ttf-ms-fonts
aura >>= Continue? [Y/n]
aura >>= Building ttf-ms-fonts...
aura >>= Would you like to edit the PKGBUILD of ttf-ms-fonts? [Y/n]
????????????????????????????????????
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) ttf-ms-fonts-2.0-12

Total Installed Size:  5.40 MiB

:: Proceed with installation? [Y/n]
```
It is at the moment I put the `?` line that the makepkg process is actually performed and it is where there is a rather long pause in time (_it all depends on the package_) that no information is seen.
The `aura >>= Building...` message should be shown after editing (or not) the `PKGBUILD`, it should be shown when the `makepkg` process is actually running.
If the `--hotedit` option is not indicated there is no difference, but if it is there is a noticeable difference.

**Comment by fosskers** [comment]
You're free to use the `-x` option in this case if you'd like to see output.
