### ISSUE TITLE
Remove uninstalled packages from cache?

### ISSUE THREAD

**Issue by xircon** [fosskers/aura#628]
How do I remove just the uninstalled packages from the cache?

e.g. I install something, doesn't do what I expected, I remove it, it stays in the cache forever.

The equivalent of `sudo paccache -Ruk0`

**Comment by fosskers** [comment]
`aura -Scc` should do it.

**Comment by xircon** [comment]
```
sudo aura -Scc

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove ALL files from cache? [y/N]

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n]
removing unused sync repositories...
```
It appears to want to wipe the whole cache?

**Comment by fosskers** [comment]
My mistake, it was just `aura -Sc`.

**Comment by xircon** [comment]
That wipes all but one, I would like to leave 3.  Example (I downgraded deadbeef twice)
```
lls -lah deadbeef*
-rw-r--r-- 1 root root 3.1M Aug 17  2019 deadbeef-1.8.2-1-x86_64.pkg.tar.xz
-rw-r--r-- 1 root root  566 Aug 17  2019 deadbeef-1.8.2-1-x86_64.pkg.tar.xz.sig
-rw-r--r-- 1 root root 3.5M Mar 21 18:10 deadbeef-1.8.3-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root  566 Mar 21 18:10 deadbeef-1.8.3-1-x86_64.pkg.tar.zst.sig
-rw-r--r-- 1 root root 3.6M Jul  1 18:01 deadbeef-1.8.4-1-x86_64.pkg.tar.zst
```
Run aura:
```
sudo aura -Sc

Packages to keep:
  All locally installed packages

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove all other packages from cache? [Y/n]
removing old packages from cache...

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n]
removing unused sync repositories...

ls -lah deadbeef*
Alias tip: lh deadbeef*
-rw-r--r-- 1 root root 3.1M Aug 17  2019 deadbeef-1.8.2-1-x86_64.pkg.tar.xz
-rw-r--r-- 1 root root  566 Aug 17  2019 deadbeef-1.8.2-1-x86_64.pkg.tar.xz.sig
```
Just one left.

**Comment by fosskers** [comment]
Right, that's the behaviour of the underlying `pacman` process that's being called. Usually `aura -Cc <some-number>` is what we use for clearing the cache in a controlled way, but I don't think I've ever put the two together, namely "Retain X of installed things, and remove everything else." To confirm, that's the feature you're looking for?

**Comment by xircon** [comment]
Yes, basically the ability to get rid of packages that have been uninstalled, but leave 3 ("n") of the packages installed for safety.

**Comment by fosskers** [comment]
Good suggestion, I'll add it.

**Comment by xircon** [comment]
Thanks, that's brilliant.

**Comment by fosskers** [comment]
Released `3.1.9` with this included.

**Comment by xircon** [comment]
Instructions?z

**Comment by fosskers** [comment]
https://github.com/fosskers/aura/releases/tag/v3.1.9

**Comment by xircon** [comment]
Seems to work, but there is a little strangeness:
```
sudo aura -Cc 3 -u
Alias tip: _ aura -Cc 3 -u
aura >>= The cache contains 2159 packages, consuming 8153 megabytes.
aura >>= 3 versions of each installed package will be kept.
aura >>= The rest will be deleted. Okay? [Y/n]
aura >>= Cleaning package cache...
aura >>= 18446744073709551613 megabytes freed.
```
18446744073709551613 mb ! What I did:
+ Removed deadbeef
+ Ran aura with -u flag
+ Re-installed deabeef, downgraded twice using downgrade.

First time it released 178 mb which is conceivable.

**Comment by fosskers** [comment]
Amazing! Perhaps that's a `Word` underflow? I'll check.

**Comment by fosskers** [comment]
```
Prelude> import Data.Word
Prelude Data.Word> maxBound :: Word
18446744073709551615
```
Your value is 2 less than `maxBound`, so somehow an underflow is occuring.

**Comment by fosskers** [comment]
Are you still able to reproduce this? I tried via your steps but still get `0` when there's nothing to remove.

**Comment by xircon** [comment]
Apologies for the late reply, been dealing with a family emergency.

Nope, just the first time I ran it, tried again twice, no issues.  As I said - strangeness :smile:

**Comment by fosskers** [comment]
No problem at all! Things happen. Perhaps we'll consider the issue fixed then, but do feel free to reopen this if you see it again.

**Comment by xircon** [comment]
Yes, I think it is solved.
