### ISSUE TITLE
aura fails to update eclipse-cpp

### ISSUE THREAD

**Issue by mkoloberdin** [fosskers/aura#629]
Unrelated packages are omitted in the output below (`...`):
```
$ sudo aura -Akxau
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
...
eclipse-common :: 4.15-1                       -> 4.16-6
eclipse-cpp    :: 4.15-1                       -> 4.16-6
...
```
...
```
aura >>= AUR Packages:
...
eclipse-common
...
aura >>= Continue? [Y/n] 
loading packages...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing eclipse-common (4.16-6) breaks dependency 'eclipse-common=4.15-1' required by eclipse-cpp
aura >>= Please check your input.
```
Note that `eclipse-cpp` is missing in the second part of the output above, under `aura >>= AUR Packages:`.
This looks like it has to do with the logic of dealing with multi-package `PKGBUILD`s.

**Comment by fosskers** [comment]
Thanks for reporting this, I'm going to look into it in detail tomorrow.

**Comment by fosskers** [comment]
Forgive me, "tomorrow" became "next month". 

There seem to have been to have been updates to this package recently, and people are having issues seemingly unrelated to Aura. Do you have any insight here? Were you able to get this installed? 

https://aur.archlinux.org/packages/eclipse-cpp/

**Comment by fosskers** [comment]
Yes, that worked. I used `--hotedit` to remove the unneeded extra packages and their checksums from the PKGBUILD.

**Comment by fosskers** [comment]
Hi there, thanks for the original report. This package no longer seems to exist on the AUR, so I'm going to close this ticket.
