### ISSUE TITLE
Aura can't find libc++ even though it's an AUR package

### ISSUE THREAD

**Issue by feroldi** [fosskers/aura#630]
Running the following gives an error:

```shell
$ sudo aura -A libc++ libc++abi
aura >>= The following are not AUR packages:
libc++
libc++abi
aura >>= No valid packages specified.
```

Aura says `libc++` and `libc++abi` aren't AUR packages. They actually are:

* https://aur.archlinux.org/packages/libc%2B%2B/
* https://aur.archlinux.org/packages/libc%2B%2Babi/

However, when I use the `%2B` encoded character instead of `+`, aura then is able to find those packages.

**Comment by fosskers** [comment]
Ah, it looks like this was fixed for official packages but not for AUR lookups:
```haskell
-- | If given a virtual package, try to find a real package to install.
resolveName :: MVar () -> Settings -> PkgName -> IO (Either PkgName (PkgName, Provides))
resolveName mv ss pn = do
  provs <- map PkgName <$> pacmanLines (envOf ss) ["-Ssq", "^" <> escape (pnName pn) <> "$"]
  case provs of
    [] -> pure $ Left pn
    _  -> Right . (, Provides pn) <$> chooseProvider mv ss pn provs
  where
    escape :: Text -> Text
    escape = T.foldl' f ""

    f :: Text -> Char -> Text
    f acc '+' = acc <> "\\+"
    f acc c   = T.snoc acc c
```

**Comment by fosskers** [comment]
I'm going to call this a bug in the underlying `aur` lib and fix it there.

**Comment by fosskers** [comment]
I'm able to build `libc++` now.

**Comment by fosskers** [comment]
This fix for this will be included in the upcoming release.
