### ISSUE TITLE
aura problem with dependencies

### ISSUE THREAD

**Issue by simonbcn** [fosskers/aura#635]
```
Arch Linux
Pacman v5.2.2 - libalpm v12.0.2
AURA Version 3.1.9
```

I'm trying to install the Aur app [yacreaderlibraryserver](https://aur.archlinux.org/packages/yacreaderlibraryserver/) but:
```
$ sudo aura -A yacreaderlibraryserver
aura >>= Determining dependencies...

aura >>= The dependency libpdfium of yacreaderlibraryserver couldn't be found.
```
`libpdfium`  doesn't exist but [`libpdfium-nojs`](https://aur.archlinux.org/packages/libpdfium-nojs/) yes and it provides the same.

**Comment by fosskers** [comment]
Aura in general doesn't try to find the source of "provides" when the "provide" itself isn't a real package. We could look into adding that feature, I'd have to review the AUR API docs.

For now, installing `libpdfium-nojs` manually would solve the issue.

**Comment by fosskers** [comment]
Hi there, I'm sorry that this took so long to fully address. This is now fixed on `master` and will be included in the upcoming Aura 4 release. Cheers.
