### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by sridhars** [fosskers/aura#636]
"aura -Slq" does not give the same output as "pacman -Slq"
similarly for -Sg and Sl. This breaks autocomplete
Replacing \aura with \pacman in the completion file fixes this as a workaround but aura -A autocomplete seems broken still.

**Comment by fosskers** [comment]
Which shell do you use?

**Comment by sridhars** [comment]
bash

**Comment by fosskers** [comment]
Looks like `q` itself is broken, I will fix that first. Thanks for reporting.

**Comment by fosskers** [comment]
`-l` was the problem afterall.

**Comment by fosskers** [comment]
`-Sl` has been fixed. The autocompletions are a known issue and are being tracked in another issue.
