### ISSUE TITLE
Zsh autocompletes package names only after repository name

### ISSUE THREAD

**Issue by ratijas** [fosskers/aura#640]
In zsh, aura auto-completion for `aura -S` only works with on a per-repository level.

When I type in `aura -S` and press Tab, it only shows repositories. Furthermore, If I narrow it down to `aura -S lib32` and press Tab, it won't show anything, despite the fact there's a huge amount of packages in `multilib/` repository named like `lib32-*`.

It doesn't make any sense to disable autocomplete by package names, because after all you are able to install them without a `repository/` prefix: `aura -S lib32-gcc-libs` (btw, despite its name, this one is from `core/`).

### Expected behavior

Autocomplete both repositories and individual packages on a top level (`aura -S abc<Tab>`). Possibly, group repos and packages into separate autocompletion categories (to the best of my knowledge, it is possible, e.g. in docker).

### Actual behavior

Autocompletion for package names is not provided, or provided only with "repository/" prefix.

### Alternatives

Consider suggestions from pacaur:
```
% pacaur -S lib32-<Tab>
zsh: do you wish to see all 754 possibilities (378 lines)?
<Tab anyway>
% pacaur -S lib32-86box-nightly-bin
>lib32-86box-nightly-bin<             lib32-libpaper                      
 lib32-a52dec                          lib32-libpciaccess-git              
 lib32-allegro                         lib32-libplacebo                    
 lib32-allegro4                        lib32-libplacebo-git                
 lib32-alsaequal                       lib32-libpng14                      
 lib32-alure                           lib32-libpng15                      
 lib32-amdgpu-pro-libgl                lib32-libprotobuf                   
 lib32-amdvlk-git                      lib32-libprotobuf-git               
 ...
Scrolling active: current selection at Top
```

**Comment by ratijas** [comment]
Fun fact: `aura -Qi` autocompletes packages with both empty search term, and with package name's starting letters.

**Comment by fosskers** [comment]
I will have to revisit these completions.

**Comment by ratijas** [comment]
...or leave zsh to me — I'm actively diving into its depths lately.

**Comment by fosskers** [comment]
That would actually help quite a lot. I use Fish so would have to do a lot of background work to fix the zsh completions myself.

**Comment by ratijas** [comment]
Can you 'assign' it to me, so I won't forget it, please?

**Comment by fosskers** [comment]
I will be revisiting zsh completions soon.

**Comment by fosskers** [comment]
zsh completions have been reworked.

**Comment by UnkwUsr** [comment]
> zsh completions have been reworked.

I'm on version `aura 4.0.1`, and for me `aura -S <tab>` gives repository names list (core, extra, multilib), while for `aura -Q <tab>` it gives package names list. Is it intended?

zsh version `5.9`

**Comment by fosskers** [comment]
Perhaps not. When you try the same with `pacman`, what happens?

**Comment by UnkwUsr** [comment]
`pacman -S <tab>` gives package names list (14266 options), `pacman -Q <tab>` also gives package names list (1341 in my case)

**Comment by UnkwUsr** [comment]
You can try yourself:
1. Install zsh.
2. Open zsh and run `autoload -Uz compinit && compinit` to enable completion functions.
3. Type `aura -S ` and press `<tab>`.

**Comment by fosskers** [comment]
Fixed again on `master`.
