### ISSUE TITLE
Git Packages -- Versions

### ISSUE THREAD

**Issue by stef204** [fosskers/aura#646]
Why does Aura want to force an update on this git-package? Is there some issue with detecting needed upgrade with git versioning?

```
$ aura -Akuax 
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
searx-git :: 0.17.0+r157+g584760cf-1 -> 0.17.0+r8+gc41db5f1-1

aura >>= Saved package state.
aura >>= searx-git PKGBUILD changes:
aura >>= Determining dependencies...
aura >>= AUR Packages:
searx-git
aura >>= Continue? [Y/n] n
aura >>= Installation manually aborted
```

**Comment by Vogel612** [comment]
note that the versions are in fact different. What's more interesting is the fact that this is a net downgrade. 584760c was commited yesterday, according to the [source repo history](/searx/searx/commits/master) and c41db5f1 was commited in July. You seem to have installed a newer version than is available from AUR

**Comment by fosskers** [comment]
This may be an edge case in my version comparison library. These two versions would both be classified as "messes", although they occupy a gray-zone of being very close to SemVer. Such cases have special comparison logic, and perhaps I made an oversight there. Thanks for reporting.

**Comment by fosskers** [comment]
Yes, specifically the `r8` section is being compared to `r157`. But this is a string-based comparison, and clearly `8 > 1`, hence the weirdness.

**Comment by fosskers** [comment]
I could perhaps extend the `Mess` parser to specifically consider the `rNNN` case, as this is common in software versions.

**Comment by stef204** [comment]
That would seem to make sense and be a potential solution.

**Comment by fosskers** [comment]
From the beginning `Mess` was considered chaotic and it has been extended before to help with such edge-cases. Reports like these are very helpful and help make comparisons between ambiguous version schemes more accurate.

**Comment by fosskers** [comment]
The `versions` library is now smart enough to detect this case. I should be able to make a release of it soon, at which point I can depend on it from `aura` and this issue can be closed.

**Comment by fosskers** [comment]
Aura now depends on the latest `versions`, and so Aura's next release will include the fixes for the original issue.
