### ISSUE TITLE
Aura doesn't like that: zsh-theme-powerlevel10k-git

### ISSUE THREAD

**Issue by ratijas** [fosskers/aura#674]
## Summary

Aura issues a huge WARNING while auditing PKGBUILD of `zsh-theme-powerlevel10k-git`.

## Description

I guess that's just their way of "just doing it", without introducing external makefiles or complicated build systems. But somehow aura just doesn't like that.

```
$ aura -A zsh-theme-powerlevel10k-git
aura >>= Determining dependencies...
aura >>= WARNING: The PKGBUILD of zsh-theme-powerlevel10k-git contains blacklisted bash expressions.

    zsh -fc '
    emulate zsh -o no_aliases
    unset -m "GITSTATUS_*"
    GITSTATUS_CACHE_DIR="$PWD"/gitstatus/usrbin ./gitstatus/install -f'

aura >>= zsh can be used to execute arbitrary code not tracked by this PKGBUILD.

    zsh -fc "emulate zsh -o no_aliases && zcompile -R -- $file.zwc $file"

aura >>= zsh can be used to execute arbitrary code not tracked by this PKGBUILD.
aura >>= Do you wish to quit the build process? [Y/n] 
```

## Additional information

- Aura's version: 3.2.2-1 (aura-bin)
- [powerlevel10k](https://aur.archlinux.org/packages/zsh-theme-powerlevel10k-git/)<sup>^AUR</sup>
- [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=zsh-theme-powerlevel10k-git)

**Comment by fosskers** [comment]
Thanks for the report. This is expected. Them doing it this way isn't considered best practice, so Aura is right to flag it. If you see the code lines here and don't have an issue with it, then you're free to continue the installation. If such warnings become too frequent / are generally irritating, you're able to turn them off with flags or config.

**Comment by ratijas** [comment]
I see why is this happening, and probably I shouldn't be too concerned about it. But a security warning sure makes people like feel uneasy.

I'm in no way affiliated with developers of p10k. But just as an end-user, I'm not sure what's the best course of actions from here.

But then again, if that's considered normal situation — feel free to close this issue.

**Comment by fosskers** [comment]
There's the pinch, I suppose. You would want a tool to warn you when a PKGBUILD is doing weird stuff, so that you can manually confirm it. At the same time, making people worry unnecessarily isn't good either. How about this - in my Rust rewrite, I will choose different wording here that asks the user to confirm the suspicious bit, without raising too many alarm bells.

**Comment by ratijas** [comment]
Maintainer of powerlevel10k has moved package script into [Makefile](https://github.com/romkatv/powerlevel10k/commits/master/Makefile). I guess this resolves the issue.

**Comment by fosskers** [comment]
Thanks for the update.
