### ISSUE TITLE
aura doesn't work with `doas`

### ISSUE THREAD

**Issue by adam-devel** [fosskers/aura#680]
i use `doas`  instead of `sudo` (and [opendoas-sudo](https://aur.archlinux.org/packages/opendoas-sudo), which symlink `sudo` to doas) this have been working forever for all of my programs (including `pacman`).

aura seem to be the only program that complain
```
$ aura -Au
aura >>= You cannot perform this operation without using sudo.
```
```
$ doas aura -Au
aura >>= As of makepkg v4.2, building as root is no longer possible.
```

**Comment by adam-devel** [comment]
#556 is probably related

**Comment by ratijas** [comment]
Should be rewritten to ask permissions on demand, rather than in advance. Related: https://github.com/fosskers/aura/issues/675#issuecomment-733394408.

**Comment by adam-devel** [comment]
and/or giving users the ability to modify the `sudo` binary path to an arbitrary value in the configuration, or adding support for multiple ways to gain super user privileges, by choosing one of `sudo`, `doas`, or `su` in the configuration (this mean that aura have to manage that internally, the user doesn't have to prefix the command with `sudo` or `doas` or anything, like `yay` do it)

**Comment by fosskers** [comment]
Aura's Rust rewrite already does permission-on-demand, so this will be an autofix once that (version 4.0) is released.

**Comment by zmrocze** [comment]
Uhm, so for me the issue persists on `AURA Version 3.2.7`. Is this fix included?

**Comment by fosskers** [comment]
Until Aura 4, `doas` won't be supported.

**Comment by GandelXIV** [comment]
> The current Aura 3.x series doesn't support `doas`, but it won't matter once Aura 4 is released.

Do you have an estimate as to when will that be?

**Comment by fosskers** [comment]
In the new year, thanks for your patience.
