### ISSUE TITLE
aura -Au --devel don't see chaotic-aur packages

### ISSUE THREAD

**Issue by rtentser** [fosskers/aura#681]
I'm using [chaotic-aur](https://lonewolf.pedrohlc.com/chaotic-aur/) repository for some pre-built aur packages. But sometimes i rebuilt those packages. For example, i modify `openscenegraph-openmw-git`, so it uses more recent branch, and rebuilt `openmw-git` with it. I want to rebuilt `openmw-git` with `aura -Au --devel`, but the problem is it doesn't do that, probably because binary version is prefered (which i ignore in `pacman.conf`).

An option to make aura see and manage specific chaotic-aur packages (not all of them) would be the best, probably.

**Comment by fosskers** [comment]
Yes by default if a particular package is found in both some prebuilt repo and the AUR, the prebuilt one will be installed. I'll see what I can do about this.

**Comment by fosskers** [comment]
Hi there, I'm sorry that this took so long to get back to. For specific cases like this, I'd recommend you manage the custom builds yourself with manual calls to `makepkg`. A package tarball can be downloaded with `aura -Aw`. Please let me know if you have any other issues.
