### ISSUE TITLE
it seems there's no `pacman -Qu` equivalent for aur packages

### ISSUE THREAD

**Issue by adam-devel** [fosskers/aura#682]
i would suggest adding `-a`, `--aur` flag to the `-Q` (query operation) which do the aur equivalent of what pacman does

```sh
aura -Qua
```

**Comment by micwoj92** [comment]
Is that not the same as `aura -Qmu'?

**Comment by adam-devel** [comment]
according to pacman, `-m` show foreign packages (≈ aur packages)
but it obviously can't be combined with `-u`, because pacman can't check aur packages (it return with an error code of 1, and no error messages in my machine)
and since the -m flag is not mentioned in aura's man page, i assumed that it just pass the job to pacman (which can't do the job), but i tried running `aura -Qmu` anyways, it existed with an error code and without an error message, i assume it passed the job to pacman

pacman can't accept `-Qmu` but aura should do it, and once implemented it should be added to the man page  

using `-m` would be better than adding a new flag like `-a`

**Comment by micwoj92** [comment]
Thank you for explanation. I only tested is by doing `aura -Qmu` and it didnt show any error messages so I assumed it was working (all my aur packages were up to date). Do you know if any aur helper has this functionality?

**Comment by fosskers** [comment]
While not as minimal as the output of `-Qu`, `-Au --dryrun` can display a lot of the information you're looking for.

**Comment by adam-devel** [comment]
thank you, but do you plan on implementing `-Qmu` and `Qu` so that they include aur updates?

**Comment by fosskers** [comment]
It has been Aura policy to not manipulate the native Pacman commands (e.g. `-S`, `-Q`, etc) or add any new suboptions to them. If you like, I could add a subflag to `-Au` that does specifically what you're asking and matches the output of `-Qu`.

**Comment by adam-devel** [comment]
yes please, and thank you

**Comment by fosskers** [comment]
This has been implemented as `
