### ISSUE TITLE
Use vcs folder for non -git,svn etc. packages from aur if they use git to download sources.

### ISSUE THREAD

**Issue by micwoj92** [fosskers/aura#689]
There are some non vcs packages which use git to download, every time there is  update(or delete package and rebuild), it redownloads whole repo and takes much more network and disk usage.
So I mean that aura should detect download agent used and place in vcs folder based on that.

Example packages from aur: gtk-frdp, palemoon

**Comment by ratijas** [comment]
Are you referring to [these lines](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=palemoon#n30) in `prepare()` step?

```bash
prepare() {
  sed 's#%SRCDIR%#'"${srcdir}"'#g' mozconfig.in > mozconfig
  cd ${_repo}
  git submodule init
  git config submodule.platform.url "${srcdir}/UXP"
  git submodule update
}
```

I wonder, if that's even a good practice. If they are "non vcs", then why using git in the first place?

**Comment by micwoj92** [comment]
No, im not referring to these lines. Just that in build directory, every `aura -Ax packagename` will do this:
![image](https://user-images.githubusercontent.com/45581170/105703600-c63c8280-5f0d-11eb-980f-da9459ae8fc8.png)

For vcs packages it's just one folder for a package: example
![image](https://user-images.githubusercontent.com/45581170/105703722-f1bf6d00-5f0d-11eb-90c0-bf652125d079.png)


> I wonder, if that's even a good practice. 

That is official build instructions. I have no idea if that is good build practice. 

> If they are "non vcs", then why using git in the first place?

Even official arch packages use that, example is many gnome packages. It just downloads much less data in long run.
example, gnome-autoar
https://github.com/archlinux/svntogit-packages/blob/packages/gnome-autoar/trunk/PKGBUILD#L14

**Comment by fosskers** [comment]
Official packages can be built/named however the Arch guys please. Were `gnome-autoar` an AUR package I would call that a packaging mistake.

Looking at `palemoon` that's the judgment I'll have to make too.

**Comment by fosskers** [comment]
Hey guys, thanks for the original discussion. Aura 4 is coming out soon, and I'm going through old issues. I'm going to close this, but please let me know if you have any other issues. git handling has been improved, in general, in Aura 4. Cheers.
