### ISSUE TITLE
Proxy issue with aura-bin

### ISSUE THREAD

**Issue by ecool** [fosskers/aura#695]
So, I have reviewed the old issue with proxy issues #352 and still seem to be experiencing problems.
This also showcases another old issue with `^C` and aura not removing the db.lck file #455.

Example:
```
> sudo pacman -Sy
:: Synchronizing package databases...
 core is up to date         0.0   B  0.00   B/s 00:00 [----------------------------]   0%
 extra is up to date        0.0   B  0.00   B/s 00:00 [----------------------------]   0%
 community is up to date    0.0   B  0.00   B/s 00:00 [----------------------------]   0%

> sudo -E aura -Sy
:: Synchronizing package databases...
error: failed retrieving file 'core.db' from mirrors.evowise.com :
    Failed to connect to mirrors.evowise.com port 80: Connection refused
^C

> sudo aura -Sy
:: Synchronizing package databases...
error: failed to update core (unable to lock database)
error: failed to update extra (unable to lock database)
error: failed to update community (unable to lock database)
error: failed to synchronize all databases

> sudo rm /var/lib/pacman/db.lck

> echo $http_proxy $https_proxy
http://192.168.2.10:80 http://192.168.2.10:80
```

I have also set `Defaults env_keep += "*_proxy *_PROXY"` in `sudoers`.

```
> sudo aura --version

 __ _ _  _ _ _ __ _    Pacman v5.2.2 - libalpm v12.0.2
/ _` | || | '_/ _` |   Copyright (C) 2006-2020 Pacman Development Team
\__,_|\_,_|_| \__,_|   Copyright (C) 2002-2006 Judd Vinet
AURA Version 3.2.2
```

If there is additional information that is required, please let me know and I will do my best to get it. I can work around the issue with manually managing my AUR packages but aura is an amazing wrapper and AUR helper and I would like to be able to use it with my proxy settings.

edit 1: I will also note that this is a new Arch Linux install.

Respectfully,
- Eric

**Comment by fosskers** [comment]
I suspect this is due to Aura `su`ing back down into the build user during actual building. When it does this, it looses the environment variables that were passed through with `-E`. Someone else reported that general issue before and the fix I had for it fixed that single case but broke things in a worse way for others. In the end I had to revert that fix.

The Aura Rust port handles `sudo` a bit differently. I suspect this will "just work", if you're willing to wait for the port :)

**Comment by ecool** [comment]
I see. Thanks for the reply.

Is there any ETA on the port timeline?
I don't mind waiting for it, in any case :)

**Comment by fosskers** [comment]
At earliest I could see it being done in a month with the new schedule that I have.

**Comment by fosskers** [comment]
Hi, thanks for the original report. I'm sorry it took so long to get back to you on this.

Aura 4 handles environment variables properly while building, so this should no longer be an issue. I'll be releasing Aura 4 soon. Please let me know if you have any other issues!
