### ISSUE TITLE
zsh completion broken

### ISSUE THREAD

**Issue by zoickx** [fosskers/aura#696]
`aura 3.2.3-1`(installed from AUR [aura-bin](https://aur.archlinux.org/packages/aura-bin/))
`zsh 5.8` + `oh-my-zsh 6fbad5b`

zsh auto-completion appears to be completely broken.
Pressing tab (with any sub-command) produces an error:
```zsh command_line
$ aura
_aura:129: bad pattern: PKGBUILD]\n    {-s,--search}[Search
_aura:129: bad pattern: PKGBUILD]\n    {-s,--search}[Search
_aura:129: bad pattern: PKGBUILD]\n    {-s,--search}[Search
```

I believe this was introduced by 4e35dcc, which added mismatched single quotes in the completions file.
In fact, this "reversion" introduces quotes which [were not there in the first place](https://github.com/fosskers/aura/commits/master/aura/doc/completions/_aura).

**`git diff c49e4d3 HEAD aura/doc/completions/_aura`**:
```diff
@@ -128,9 +128,9 @@ _aura_opts_sync_modifiers=(
 # options for passing to _arguments: options for --aursync command
 _aura_opts_aursync_actions=(
     '(-A --aursync)'{-A,--aursync}
-    {-p,--pkgbuild}'[Display an AUR package PKGBUILD]'
+    {-p,--pkgbuild}'[Display an AUR package's PKGBUILD]'
     {-s,--search}'[Search AUR package names and descriptions]'
-    {-w,--downloadonly}'[Download an AUR package source tarball]'
+    {-w,--downloadonly}'[Download an AUR package's source tarball]'
 )
```

Simply removing the extra quotes fixes the issue.
Perhaps do a proper revert with `git checkout c49e4d3 aura/doc/completions/_aura`?

**Comment by zoickx** [comment]
I can submit a PR, but this seems too trivial.

**Comment by fosskers** [comment]
Thanks, I'll take care of this ASAP.
