### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by Kwpolska** [fosskers/aura#7]
``` haskell
-- This should be at ~/.config/aura/aura-conf.hs
-- How do I get it there? And what about `.pacnew`s?
```

This is how I do it in PB and Trashman*, and how 99% of the universe does that:
1. check if `~/.config/`, `~/.config/aura/` exist.  If not, create.  Bonus points if you check the env variable `XDG_CONFIG_HOME` and work according to it, falling back on `~/.config/`.
2. check if `~/.config/aura/aura-conf.hs` exists.  If not, copy over from an existing file somewhere in the system (I suggest somewhere like `/etc/`)
3. Finally, read the file.  Bonus points if you use `/etc/` as a global config file.

Also, I don't think you need to bother with pacnews, but if you do, `man PKGBUILD`.

\* I actually do XDG_CONFIG_HOME/kwpolska/{pkgbuilder,trashman}.

**Comment by Dummyc0m** [comment]
An alternative solution would be to edit the sudoers file via ```sudo visudo```.
Adding the following line would work:

    Defaults env_keep += "EDITOR"
