### ISSUE TITLE
Aura doesn't work when aurweb is down

### ISSUE THREAD

**Issue by micwoj92** [fosskers/aura#704]
Currently the website is down and I can't use aura to install packages, manual git clone/git pushes still work so I think that it should fall back to just cloning the repo instead of searching it

```
[micwoj92@desktop]: ~>$ sudo aura -Ax aura
aura: HttpExceptionRequest Request {
  host                 = "aur.archlinux.org"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/rpc"
  queryString          = "?v=5&type=info&arg%5B%5D=aura"
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 ResponseTimeout
```

Doing manual way
```
[micwoj92@desktop]: ~>$ git clone https://aur.archlinux.org/aura.git
Cloning into 'aura'...
remote: Enumerating objects: 140, done.
remote: Counting objects: 100% (140/140), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 140 (delta 35), reused 140 (delta 35), pack-reused 0
Receiving objects: 100% (140/140), 47.02 KiB | 1.04 MiB/s, done.
Resolving deltas: 100% (35/35), done.
```
it works without issues.

**Comment by ratijas** [comment]
What are the costs of implementing extra logic vs. chances that AUR website would hit its downtime?

Not sure if metadata is needed before attempting to build an AUR package, so won't comment on that one.

**Comment by micwoj92** [comment]
> Not sure if metadata is needed before attempting to build an AUR package, so won't comment on that one.

What would the metadata be?

**Comment by ratijas** [comment]
> What would the metadata be?

Name, Description, Dependencies and all sorts of info you could otherwise get only *after* cloning and processing relevant PKGBUILD.

I mean aura is an AUR helper, like an offline client for online API. Think of it as a Dropbox, or Telegram or whatever — if a server is down, then what the heck do you expect from a mere client? :)

Besides, it's just a miracle that git mirrors are still online even though API and website are down. Could've been the other way around.

**Comment by micwoj92** [comment]
> Name, Description, Dependencies and all sorts of info you could otherwise get only _after_ cloning and processing relevant PKGBUILD.

I understand that but if I only want to build then just parsing .SRCINFO/PKGBUILD should be enough, all information needed for building can be obtained from there. 

> Besides, it's just a miracle that git mirrors are still online even though API and website are down. Could've been the other way around.

Well yeah, they are separate service.

**Comment by fosskers** [comment]
I have considered in the past having Aura do shallow clones of any package it needs during the installation process, and pulling metadata from that. Kind of like how Pacman works with the official packages.

**Comment by Morganamilo** [comment]
That won't work for split packages.

**Comment by fosskers** [comment]
Right, it wouldn't. You'd basically have to do what aurweb already done, but locally, keeping a managed database of what split packages belonged to what package base. Probably out-of-scope for now.

**Comment by fosskers** [comment]
Thanks for the original report. As Aura no longer calls aurweb, I'm going to close this.
