### ISSUE TITLE
[feature request] separate makepkg.conf for some (regex/glob matched?) packages

### ISSUE THREAD

**Issue by CapSel** [fosskers/aura#712]
As a use case take a look at arm-linux-gnueabihf-gcc.
It requires that in makepkg.conf:
- `lto` is removed from `OPTIONS`
- `-Wformat -Wformat-security` is removed from `CFLAGS`

This package depends on several other packages (glibc, glibc-headers, gcc-stage1, gcc-stage2, binutils) that require same modifications to makepkg.conf. In addition I would like to add `staticlibs` to `OPTIONS` only for this set of packages.

It would be possible to solve problem in this use case by adding some kind of option like `-C /etc/makepkg-gcc.conf` but then `aura` should remember which configuration file was used for which package so that when upgrading with `-Aux` same configuration file is used.

A configuration file with mapping "package-glob -> file" would be a better option.

**Comment by fosskers** [comment]
Hi there, I'm sorry that this took so long to address. I really have no excuse to never have answered.

As for the request at hand, note that this is already possible with `makepkg --config <file>`. For such a complicated build, I'd recommend to manage it manually, calling `makepkg` yourself.

Please let me know if you have any other issues.
