### ISSUE TITLE
--noconfirm does not suppress interaction in case of blacklisted bash expressions

### ISSUE THREAD

**Issue by ferkulat** [fosskers/aura#714]
I would like to use aura in a docker environment.
If I saw this warning when trying to install the first time and decided "Its ok", I would like to have a way to install the package without confirmation.
To make this explicit I could imagine an option like --noblacklistedexpressioncheck.
Its a bit long. For sure there is a better way to name it.

Thank you very much

**Comment by ferkulat** [comment]
never mind. found in the configuration /etc/aura.conf
 analyse = False

**Comment by fosskers** [comment]
Thanks for reporting, let me know if you need anything else.
