### ISSUE TITLE
"There was an issue during recursive dependency lookup"

### ISSUE THREAD

**Issue by mkoloberdin** [fosskers/aura#717]
```$ sudo aura -Akxua kwinft disman-kwinft kdisplay-kwinft```:
```
...
aura >>= Determining dependencies...
aura >>= There was an issue during recursive dependency lookup:
UnliftIO.Exception.throwString called with:

Non-existant deps: disman kdisplay
Called from:
  throwString (lib/Aura/Dependencies.hs:114:13 in aura-3.2.5-HaGfBefGmo59Jd4lT1QNv3:Aura.Dependencies)
```

**Comment by fosskers** [comment]
Thank you.

**Comment by Nicholas-Baron** [comment]
```
[I] 12:10 nick@archbox ~> sudo aura -A discord-canary-electron-bin
aura >>= Determining dependencies...
aura >>= There was an issue during recursive dependency lookup:
UnliftIO.Exception.throwString called with:

Non-existant deps: asar
Called from:
  throwString (lib/Aura/Dependencies.hs:114:13 in aura-3.2.9-FXHz7RkaaqHGNygiuPDPYh:Aura.Dependencies)
```

Same error
Different version and command

It seems to be caused by try to update an AUR package that has “mainline Arch” dependencies.

**Comment by fosskers** [comment]
@Nicholas-Baron this shouldn't happen on [Aura 4](https://crates.io/crates/aura-pm). Are you able to test it?

**Comment by Nicholas-Baron** [comment]
Ran the same command today and it worked fine.
This seems like a Hiesenbug.
If/when it comes up next time, I will try Aura 4 ?on the same day?

**Comment by fosskers** [comment]
I will release Aura 4 as soon as possible so that you won't have to worry about this in the future.

**Comment by fosskers** [comment]
Hi there, as the Aura 4 release approaches, I'm clearing out old issues. I double-checked just now and the dependencies for these packages seem to resolve, so I'm going to close this.

Please let me know if you have any other issues.
