### ISSUE TITLE
[feature request] Use same locale as aura in pacman commands

### ISSUE THREAD

**Issue by augustin64** [fosskers/aura#720]
When I use pacman to do a full system upgrade, it is displayed in French [fr_FR] (which is my locale)
```
➜  ~ sudo pacman -Syu
:: Synchronisation des bases de données de paquets…
 core est à jour
 extra est à jour
 community est à jour
 multilib est à jour
:: Début de la mise à jour complète du système…
 il n’y a rien à faire
```
When I use aura for this, aura's prompt is in French `aura >>= État des paquets sauvegardé.`, but pacman isn't
```
➜  ~ sudo aura -Syu
aura >>= État des paquets sauvegardé.
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
```

**Comment by fosskers** [comment]
Thank you for reporting this! Aura prides itself on being multilingual, and I'm surprised it took so long for this issue to crop up. I will look into this.

**Comment by PRESFIL** [comment]
Is the reason on this [line][line]?

I have checked the calls of this function, basically, the output of `pacman` is
used only in `pacmanOutput`/`pacmanLines`, the result of which is the names of
packages, from dependencies or versions of packages/dependencies. Even in
`SimplePkg` there is no place for other information.

It seems like package names are always ASCII characters. Does it make sense to
switch the locale?

[line]: https://github.com/fosskers/aura/blob/4f4417c9c7cdda83f8634f90991d0f166a12fb2b/haskell/aura/lib/Aura/Pacman.hs#L102

**Comment by fosskers** [comment]
This will be something to revisit in the Rust code.

**Comment by fosskers** [comment]
Yes, once the Rust version is complete. An alpha is available here: https://crates.io/crates/aura-pm

**Comment by fosskers** [comment]
Using Aura 4 (soon to be released), I just built several packages with my system locale set to `fr_CA.UTF-8`, and everything worked without issue. I recently ported all the localisations from Aura 3 to 4, including [French](https://github.com/fosskers/aura/commit/c71d6a8a4009f4a7a47483df66ebad76db164e27).

I'm sorry that it took me so long to address this.
