### ISSUE TITLE
[feature request] "--needed" switch in aura.conf

### ISSUE THREAD

**Issue by Earthling-Z3R0** [fosskers/aura#721]
Since I don't want to re-install packages/dependencies that are already present on the system, I keep appending "--needed" to my -S commands. Is it possible to add this as a toggle in aura.conf, since there is no such option in pacman.conf ?!

**Comment by D0nnieD4rk0** [comment]
just add those commands as aliases in your .bashrc

**Comment by Earthling-Z3R0** [comment]
I didn't realize I can do "aura -needed -S appname".
I always appeneded "--needed" at the end of line.
So yes, I can now indeed alias "aura" to "aura --needed" and then append the actualy operators I want to use.

I hope the "--needed" bit doesn't interfere with operators other than "-A" or "-S".
(In that case I would have to name the alias different from "aura" which I would like to avoid.)

Thanks for the hint.

Anyway, I still think this switch would be nice to have on aura.conf :)

**Comment by fosskers** [comment]
This is a reason request, I can check the current config settings and add it.

**Comment by Earthling-Z3R0** [comment]
Awesome!_!_ :+1:

**Comment by fosskers** [comment]
Hi there, I'm sorry it took so long to get back around to this. Is this use of `--needed` still necessary for you?

**Comment by fosskers** [comment]
Closing this for now. Please feel free to reopen if this is still an issue for you.
