### ISSUE TITLE
add a BottomUp flag to config

### ISSUE THREAD

**Issue by D0nnieD4rk0** [fosskers/aura#722]
ive read the manpage there is no option yet pls add

**Comment by fosskers** [comment]
Are you trying to order search results?

**Comment by D0nnieD4rk0** [comment]
yes since your thing is supposed to be the end all be all

**Comment by fosskers** [comment]
At current it's possible to sort the results of `-As` in various ways, you can find them in man page. Let me know if those don't suffice.

**Comment by D0nnieD4rk0** [comment]
i cant find anything other than the aura -As --head[=N] thingy which just limits the results. i just need the top results to show at the bottom so i dont have to scroll 100 lines up just to find what i need

**Comment by fosskers** [comment]
By default results are sorted by vote count, so if you use `--head=5` etc. you'll see what you're looking for.

**Comment by fosskers** [comment]
Aura 4 provides `--reverse` alongside `-As` to accomplish this.

**Comment by fosskers** [comment]
Done.
