### ISSUE TITLE
add doas support to "-A"

### ISSUE THREAD

**Issue by D0nnieD4rk0** [fosskers/aura#723]

**Comment by fosskers** [comment]
As opposed to just `sudo`?

**Comment by D0nnieD4rk0** [comment]
yup

**Comment by fosskers** [comment]
That's a reasonable request, I will look into it.

**Comment by array-in-a-matrix** [comment]
`doas` works like `sudo` when downloading packages from the official repo, however `makepkg` errors out when upgrading/downloading from the aur. `sudo` does not have this problem.
```
$doas aura -Au
...
aura >>= As of makepkg v4.2, building as root is no longer possible.
```
```
$sudo aura -Au
aura >>= Fetching package information...
...
```

**Comment by array-in-a-matrix** [comment]
The rust rewrite should fix this https://github.com/fosskers/aura/issues/680#issuecomment-749157976

**Comment by D0nnieD4rk0** [comment]
> The rust rewrite should fix this [#680 (comment)](https://github.com/fosskers/aura/issues/680#issuecomment-749157976).

cool when that happening

**Comment by fosskers** [comment]
It's on-going, there's an open PR for it.

**Comment by pc00per** [comment]
Is this still in works? I'mma a longtime doas user. Requesting to merge the essential PRs.
```
$ aura -A gnome-text-editor
aura >>= You cannot perform this operation without using sudo.

$ doas aura -A gnome-text-editor
doas (cooper@arch) password:
aura >>= As of makepkg v4.2, building as root is no longer possible.
```
There's no way to use Aura if you dont have sudo....

**Comment by fosskers** [comment]
Aura 4 is almost ready!

**Comment by pc00per** [comment]
Atleast release 4.0 as alpha mate ;{)

**Comment by fosskers** [comment]
The Alpha is technically out, although I haven't packaged it. You're free to build `master` within the `rust/` directory. But really I should put out the alpha on crates.io and the AUR anyway.

**Comment by pc00per** [comment]
If people are that intelligent, I bet they would code their own wrappers instead of using others 😂

**Comment by fosskers** [comment]
Aura is quite more than a wrapper at this point.

**Comment by pc00per** [comment]
> Aura is quite more than a wrapper at this point.

But I assume majority of the users use this to only install AUR packages (not just aura, but any other AUR helper in general).
