### ISSUE TITLE
If vi isn't installed --hotedit fails

### ISSUE THREAD

**Issue by Stig124** [fosskers/aura#724]
I encountered this error when trying to hotedit a pkgbuild :
```
aura: vi: startProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

`vi` isn't installed and EDITOR/VISUAL are set to `nvim`, doing `editor` works

A workaroud is to make a `vi` symlink to an editor (`nano` and `nvim` works)

Aura `3.2.5` |  Pacman `6.0.0` but CR ar  ef4528c

**Comment by xtrahigh** [comment]
`sudo nvim /etc/aura.conf`
Then just change the editor parameter to `nvim` or `editor`

**Comment by fosskers** [comment]
Thanks @xtrahigh .
