### ISSUE TITLE
Feature Request: "--asdeps" adding to aura

### ISSUE THREAD

**Issue by Zemrod** [fosskers/aura#729]
If i try to install a package as a dependency aura doesn't seem to parse the option `--asdeps` to pacman.
The command `sudo aura -S --asdeps dnsmasq` results in dnsmasq optaining the reason "explicitly installed",
by that i assume aura doesn't support this option, which is why I'd like to ask if it would be possible to add this and its counter part `--asexplicit`, since pacman tries to preserve the install reason if you re-install a package, to aura.

**Comment by fosskers** [comment]
`--asdeps` is supported, but let me double-check this particular use case.

**Comment by fosskers** [comment]
Confirmed fixed on Aura 4. Thanks again for the report, and I'm sorry that it took so long to confirm this.
