### ISSUE TITLE
Feature request: add support for $EDITOR environment variable.

### ISSUE THREAD

**Issue by AakashSharma7269** [fosskers/aura#730]
Having the hotedit flag automatically pick up on $EDITOR environment variable unless a specific editor is set in /etc/aura.conf would be a really nice feature.

**Comment by fosskers** [comment]
It is supposed to already, but perhaps something is wrong here. I do know that there have been issues with environment variables interacting with `sudo`. Either way, `sudo` won't be required after the Rust port is finished, so your `EDITOR` will always be respected.

**Comment by AakashSharma7269** [comment]
Oh I didn't know that aura is moving to rust. Really happy with the package manager, thank you for your work ❤️.

**Comment by fosskers** [comment]
My pleasure!
