### ISSUE TITLE
Conflict with pacman's -A

### ISSUE THREAD

**Issue by Morganamilo** [fosskers/aura#731]
Pacman is likely to get an -A operation at some point. Seem's as aura is built upon -A this may cause some conflict.

I assume the answer is to just not wrap that operation but thought I'd give a heads up.

**Comment by fosskers** [comment]
Yup, I had heard mention of `-A` on the mailing list some time ago. What are the chances of us convincing them to change it on their end?

**Comment by Morganamilo** [comment]
-A is the most appropriate flag. It's not going to be changed for the sake of other programs.

Just thought I'd give you a heads up.

**Comment by fosskers** [comment]
Yup, that seems to be the Pacman dev policy. Well, Aura's `-A` will not be Pacman's `-A`, I'll have to provide another option for it.

**Comment by Morganamilo** [comment]
Probably best to just support the long flag for -A, --alternatives.

**Comment by fosskers** [comment]
Yeah that's totally reasonable.

**Comment by fosskers** [comment]
`pacman` still doesn't have `-A`, so I'll go with `--alternatives` like we discussed above, if it ever gets implemented.
