### ISSUE TITLE
Skip dependency checks with `aura -A --nodeps`?

### ISSUE THREAD

**Issue by ratijas** [fosskers/aura#732]
### Summary

Aura's AUR(`-A`) mode does not support `--nodeps` flag, which (in `-S` repositories mode and in pacman itself) allows to install packages without their dependencies. It is marginally useful, because software packagers/maintainers sometimes mess up all the `conflicts` and `provides` sections.

### Steps to reproduce

1. Install [plocate](https://archlinux.org/packages/community/x86_64/plocate/) instead of [mlocate](https://archlinux.org/packages/core/x86_64/mlocate/). They conflict with each other, while not providing a full alternative.
2. Try to install [pacman-updatedb-hook](https://aur.archlinux.org/packages/pacman-updatedb-hook/)<sup>^AUR</sup> with this command: `$ aura -A --nodeps pacman-updatedb-hook`

### Expected result

Should work, just as for `$ aura -S --nodeps …`

### Actual result

```
$ aura -A --nodeps pacman-updatedb-hook
Invalid option `--nodeps'

Did you mean one of these?
    --deps
    --asdeps

Usage: aura ((-A|--aursync) PACKAGES | (-B|--save) | (-C|--downgrade) 
...
```

**Comment by fosskers** [comment]
Does `--skipdepcheck` do what you're looking for?

**Comment by ratijas** [comment]
However, wait a just a second here.

```
$ aura -A --skipdepcheck pacman-updatedb-hook
aura >>= Determining dependencies...
aura >>= AUR Packages:
pacman-updatedb-hook
aura >>= Continue? [Y/n] Y
aura >>= Building pacman-updatedb-hook...
aura >>= Building failed. Would you like to see the error? [Y/n] Y
==> ERROR: Could not resolve all dependencies.

aura >>= There was a makepkg failure.
aura >>= Would you like to continue anyway? [Y/n] 
```

**Comment by fosskers** [comment]
Right. `--skipdepcheck` assumes you're otherwise providing the dependencies somehow, at least at the pacman-level. Here pacman is still getting mad due to the missing dep. So either:

1. `--skipdepcheck` should imply `--nodeps` to pacman automatically, or;
2. I should implement a `--nodeps` passthrough for you.

**Comment by ratijas** [comment]
Maybe both, for fine-grained control. Since aura is a wrapper for another tool, it naturally exposes wider API anyway.

**Comment by Morganamilo** [comment]
> Right. --skipdepcheck assumes you're otherwise providing the dependencies somehow, at least at the pacman-level. Here pacman is still getting mad due to the missing dep. So either:

Honestly I don't see what use this would have on its own.

**Comment by fosskers** [comment]
Sorry its has taken so long to get around to this. Is this still desired?

**Comment by fosskers** [comment]
I restored `--skipdepcheck` in Aura 4 today, so I'm going to close this. Please let me know if anything else comes up.
