### ISSUE TITLE
Error while upgrading a `*-git` package

### ISSUE THREAD

**Issue by mkoloberdin** [fosskers/aura#736]
While upgrading `subtitlecomposer-git` (0.7.0.296.c45f3239-1 -> 0.7.1+git34.dba4b820-1):
```aura >>= Building subtitlecomposer-git...
==> Making package: subtitlecomposer-git 0.7.1+git34.dba4b820-1 (Tue 09 Nov 2021 02:25:38 PM EET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
==> ERROR: /var/cache/aura/vcs/subtitlecomposer-git/subtitlecomposer-git/subtitlecomposer is not a clone of https://gitlab.com/subtitlecomposer/subtitlecomposer.git
    Aborting...
```

**Comment by mkoloberdin** [comment]
The cause seems to be that the location of the repo did indeed change as the error message suggests (`https://invent.kde.org/kde/subtitlecomposer` -> `https://invent.kde.org/multimedia/subtitlecomposer`).
Removing the cached tree fixes the issue but I guess this should be handled by `aura` automatically.

**Comment by fosskers** [comment]
Thanks for the report. Doom Emacs does handle repo changes like this automatically, so it's not unreasonable that Aura could too. I'll leave this open.

**Comment by fosskers** [comment]
Thanks for the original report. I'm sorry it took so long to circle back around to this. 

With Aura 4, this would be fixed by deleting this package's entry in `~/.cache/aura/packages/`.
