### ISSUE TITLE
Add flatpak flag

### ISSUE THREAD

**Issue by lil5** [fosskers/aura#737]
For example use `-F` as the argument to identify flatpak commands

Here is a list of usage examples:
- `-Fu` -> `flatpak update` 
- `-Fr` -> `flatpak uninstall`
- `-F <name>` -> `flatpak install <name>`
- `-Fi <name>` -> `flatpak info <name>`
- `-Fs <glob>` -> `flatpak search <glob>`

**Comment by fosskers** [comment]
I will consider this, thank you for the suggestion.

**Comment by fosskers** [comment]
Sorry that it took so long to circle back around to this. Unfortunately `-F` is already taken by `pacman`. I also think it's fine to keep `aura` and `flatpak` separate. If you'd like a sort of fused usage like this, I'm sure something is possible with shell commands. Cheers.
