### ISSUE TITLE
Exact version match dependency for main version does not work for subreleases

### ISSUE THREAD

**Issue by bartlibert** [fosskers/aura#738]
I'm trying to install [cryptomator](https://aur.archlinux.org/packages/cryptomator/) from aur and I get the following error:

`The package cryptomator depends on version =17 of jdk-openjdk, but the most recent version is 17.0.1.u12.`

The PKGBUILD for this package contains the line:
`makedepends=('java-environment=17' 'maven')`
According to the code, this version of the jdk should be accepted, but it is not: https://github.com/fosskers/aura/blob/77778f46fd79c2cd6528199f11f5ddf8558aa73c/aura/lib/Aura/Dependencies.hs#L182-L183

**Comment by fosskers** [comment]
Thanks for the report. This will be fixed automatically by the upcoming Rust port.

**Comment by fosskers** [comment]
At the moment this package appears to resolve its dependencies without issue. That said, I would be [wary about building it](https://aur.archlinux.org/packages/cryptomator#comment-980465) regardless.

I'm sorry that this took so long to address. If you have any other issues, please let me know.
