### ISSUE TITLE
Explain the Rust code

### ISSUE THREAD

**Issue by ShalokShalom** [fosskers/aura#751]
Hi 👋

I just read through the Readme, and at the end I could see 30% of your code is written in Rust.

The Readme explains nothing of it, describing it purely as a Haskell project.

It seems also not nessecery to build it.

Mind you, sharing its meaning - and eventually doing so in the Readme?

Thanks 🙏

**Comment by fosskers** [comment]
https://github.com/fosskers/aura/discussions/657 :)
