### ISSUE TITLE
Add ARM binary support

### ISSUE THREAD

**Issue by ShalokShalom** [fosskers/aura#752]
It would be lovely, to add ARM pre-builds for my phone and Raspberry PI, etc. 

Compiling Haskell on these devices can be daunting. 

Thanks.

**Comment by fosskers** [comment]
This is actually one of the reasons why I've been porting Aura to Rust. I hope to be released by April!

**Comment by fosskers** [comment]
Hi there, I'm going to close this for now as I prepare for the Aura 4 release. There should be no issues going forward on building this on ARM systems. Thank you for your patience and I'm sorry that this took so long to readdress.
