### ISSUE TITLE
Installing any package from AUR fails

### ISSUE THREAD

**Issue by samokosik** [fosskers/aura#757]
Hello, I am having issues with aura trying to build package from AUR. No matter what package I try to install, it fails:
![image](https://user-images.githubusercontent.com/73645764/162633261-06524959-65d0-47af-ba4d-3e5e9dd3e463.png)
I have the newest version of aura which I manually built but it was also an issue with aura 3.6

However, updating from regular repositories works just fine.

Thank you

**Comment by fosskers** [comment]
Hi there, thanks for the report. Does `aura -Ai onlyoffice-bin` work?

**Comment by samokosik** [comment]
That shows me the information about the current package

**Comment by fosskers** [comment]
I am able to install `onlyoffice-bin` without issue. Is it still not working for you?

**Comment by samokosik** [comment]
The issue still persists :/
Is there maybe a way of
completely resetting aura/sth else?
Thank you

**Comment by fosskers** [comment]
I wonder if there's a permissions issue with where `aura` is trying to pull the git repo of the package. You could try building the package in another folder by setting the following in your `/etc/aura.conf`:
```
buildpath = <SOME-OTHER-PATH>
```

**Comment by samokosik** [comment]
Hm, can I set it to a any directory, will the temp files be deleted afterwards?

**Comment by fosskers** [comment]
Actually, this might be intimately related to #758 . Solving that will probably solve this at the same time.

**Comment by samokosik** [comment]
Yea, the mentioned
solution worked ;)
