### ISSUE TITLE
UTF-8 problems

### ISSUE THREAD

**Issue by ratijas** [fosskers/aura#761]
Package description is cut off at the first non-ASCII character. Only happens for repositories, but not for ^AUR packages.
```
aur/mingw-w64-djvulibre 3.5.28-1 (0 | 0.00)
    Suite to create, manipulate and view DjVu ('déjà vu') documents (mingw-w64)
extra/djvulibre 3.5.28-3
    Suite to create, manipulate and view DjVu ('d
```

https://archlinux.org/packages/extra/x86_64/djvulibre/

**Comment by fosskers** [comment]
That's odd. I can reproduce it in `aura`, and I see that it doesn't happen with `pacman`. Either way this is an Aura 4 autofix, since all Rust strings are UTF-8 no matter what.

**Comment by ratijas** [comment]
> News on that front: I overcame a big hurdle last night with respect to "provides" and multi-term search, so work on the Rust port's -A functionality can continue.

Cool! You need any help on it? It's been a while since I've written any Rust though.

**Comment by fosskers** [comment]
Thanks! The answer to that will definitely be Yes once I release an initial alpha, which will be Soon™ .

**Comment by fosskers** [comment]
Confirmed that this does not occur in Aura 4. Thanks again!
