### ISSUE TITLE
Constantly Wants to Upgrade Git Packages

### ISSUE THREAD

**Issue by stef204** [fosskers/aura#773]
Not sure I am getting this right but `aura` wants to constantly "upgrade" a git package even when installed version seems to be higher than what is in `PKGBUILD`.

Example:
```  
% sudo aura -Akuax
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
fastlbry-terminal-git :: v0.8.r1.ge051939-1 -> 0.5.r207.g11e4d0d-1
 ```   

`v0.8.r1.ge051939-1` seems to be more recent than `0.5.r207.g11e4d0d-1` but am I getting this wrong?

Also, even if I accept this rebuild, it will want to rebuild on the next check anyway.....

**Comment by fosskers** [comment]
It's a quirk of this specific package, having changed its versioning scheme. Notice the `v0` on the left vs the `0` on the right. So in this case Aura thinks there's an upgrade to be made. The fault is with the package packager in this case.
