### ISSUE TITLE
Revision from `aeson ^>=2.0` to `aeson ^>=2.1` broke cabal builds

### ISSUE THREAD

**Issue by phadej** [fosskers/aura#774]
Did you mind to do `aeson ^>= 2.0 || ^>= 2.1` revision?

https://hackage.haskell.org/package/aura-3.2.9/revisions/

(EDIT: Fwiw, it probably "broke" stackage nightly builds as well, as `aura-3.2.9` cannot be included in next nightly before `aeson-2.1` is there; even `aura-3.2.9` is in current nightly).

**Comment by fosskers** [comment]
Sure, one moment.

**Comment by fosskers** [comment]
Done.
