### ISSUE TITLE
Support building as `root` for systems with no other user

### ISSUE THREAD

**Issue by ghost** [fosskers/aura#776]
I can still able to install AUR packages manually under root...
```
git clone <repo>
chown -R nobody <package-dir>
cd <package-dir>
sudo -u nobody makepkg
pacman -U *.zst
```
**Note:** On missing dependencies, I could able to fix that by installing  missing dependencies
`pacman -S --asdeps <missing-dep-list>`
And then trying makepkg process again with success.

This method will overcome makepkg root limitations. And I would love to see this incorporating into aura.

**Comment by fosskers** [comment]
Aura 4 no longer has limitations involving `root`, so this should be an auto-fix as soon as it's released.

**Comment by pc00per** [comment]
So... Is there any reason you're holding up 4.0 release mate?

**Comment by fosskers** [comment]
Because I moved across the world and just started a new job. It will come as soon as I'm able.

**Comment by pc00per** [comment]
> Because I moved across the world and just started a new job. It will come as soon as I'm able.

Amazing. Offtopic, but congrats. Hope you enjoy your new job mate.

**Comment by fosskers** [comment]
Thanks for your patience :pray: Getting this out as soon as possible is obvious still big in my mind.

**Comment by fosskers** [comment]
Give it a shot!
```
cargo install aura-pm --version 4.0.0-alpha3
```

**Comment by pc00per** [comment]
```
#[/home/mpk/.cargo/bin]# ./aura -A extension-manager
aura :: Resolving dependencies...
aura :: AUR packages:
 extension-manager
aura :: Proceed? [Y/n] 
aura :: Preparing build directories...
aura :: Building extension-manager...
==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.
aura :: Package failed to build, citing:

  makepkg failed.

aura :: Action cancelled.
```

**Comment by fosskers** [comment]
Yup, `-A` is not expected to be ran with root.

**Comment by pc00per** [comment]
> Yup, `-A` is not expected to be ran with root.

You can actually de-elivate privilege escalations through -u nobody. It should then work as it is not on root.

**Comment by fosskers** [comment]
I still need to as some "true" `root` detection in general.

**Comment by pc00per** [comment]
> I still need to as some "true" `root` detection in general.

Welp, for pushing compiled binaries or shared libraries, ofc I can understand. But to compile from source via AUR pkgbuilds, programs like makepkg won't function, is what I'm saying.
Atleast they need de-escalation of privilege.

**Comment by fosskers** [comment]
You mean only when managing a system with only a `root` user on it, yeah?

**Comment by pc00per** [comment]
> You mean when managing a system with only a `root` user on it, yeah?

Yep. My ultimate scenario / goal is to build & install AUR packages even on chrooted Arch ISO
Currently, I can do that manually ([1st comment](https://github.com/fosskers/aura/issues/776#issue-1284934931))

**Comment by fosskers** [comment]
Understood, I'll make sure this is possible.

**Comment by fosskers** [comment]
It is now possible to build packages as `root` using `nobody` as a proxy.
