### ISSUE TITLE
invalid option `--verbose`

### ISSUE THREAD

**Issue by pc00per** [fosskers/aura#778]
$ `sudo aura -A extension-manager --verbose`
[sudo] password for default: 
Invalid option `--verbose'

**Comment by fosskers** [comment]
Hi, thanks for the report. If you'd like to "unsuppress" build output, try the `-x` option with `-A`, like:
```
sudo aura -Ax extension-manager
``
**Note that this isn't necessary with Aura 4, currently in Alpha.**
