### ISSUE TITLE
Incomplete error message about unfulfilled deps

### ISSUE THREAD

**Issue by ShalokShalom** [fosskers/aura#781]
That error message does _not_ tell me, **WHICH** dependency failed, and not **WHY** it/they failed or **WHAT** I could do to solve it. 

![Screenshot_19](https://user-images.githubusercontent.com/6344099/184643113-7abb7b88-6064-43bd-af47-2dddf7988af2.png)

**Comment by fosskers** [comment]
Aura 4 is much clearer about this. I actually tried to build `ruby-pry` to see the error, but it succeeded in resolving the deps, haha. I'm going to mark this as auto-fix.

**Comment by ShalokShalom** [comment]
Can you let me use 4? You already announce an Alpha a few days ago :)
