### ISSUE TITLE
Dependency cycles?

### ISSUE THREAD

**Issue by mkoloberdin** [fosskers/aura#782]
```
$ sudo aura -Akxa mingw-w64-qt5-base-static
...
aura >>= Determining dependencies...

aura >>= The following dependency cycles were detected:
mingw-w64-cairo => mingw-w64-fontconfig => mingw-w64-freetype2 => mingw-w64-harfbuzz => mingw-w64-librsvg => mingw-w64-pango => mingw-w64-poppler
```
What _cycles_ is it referring to?

**Comment by Kritiqual** [comment]
It shows what packages need to be installed first

**Comment by mkoloberdin** [comment]
The thing it that it does not install them after spitting out that message. It is a fatal error in other words.

**Comment by fosskers** [comment]
Congratulations, this is actually the first time I've seen a user report this in 10 years :laughing: It would be interesting to see what the new version of Aura would output for this. I will be fixing it up tomorrow.

**Comment by micwoj92** [comment]
I don't think this is possible, there are 2 -bootstrap packages that need to be built first before attempting to build with normal packages. Unless aura would be smart enough to build these 2 first
https://aur.archlinux.org/packages/mingw-w64-freetype2-bootstrap
https://aur.archlinux.org/packages/mingw-w64-cairo-bootstrap

**Comment by fosskers** [comment]
I haven't gotten to this yet but will soon.

**Comment by fosskers** [comment]
Hi there, I apologize for taking so long to return to this.

In the originally posted case, Aura 4 now displays:
```
aura :: Dependency cycle detected: mingw-w64-pango => mingw-w64-cairo => mingw-w64-librsvg => mingw-w64-pango
```
Resolving this cycle is beyond Aura's scope, but [as posted above](https://github.com/fosskers/aura/issues/782#issuecomment-1246715756) there seems to be a workaround.

This improvement will become available with Aura 4's upcoming release. Please let me know if you have any other issues.
