### ISSUE TITLE
Error backtrace

### ISSUE THREAD

**Issue by gagbo** [fosskers/aura#786]
I have a curl error when trying to isntall any package right now (doesn't seem to come from Aura, so not the matter here), but it'd be nice if I had the exact error in the final message without needing to pass the `debug` log-level, so that I know there's nothing I can do for now:

```
aura :: Resolving dependencies...
16:01:18 [DEBUG] (1) aura_core::aur::dependencies: amdgpu-clocks-git
16:01:18 [DEBUG] (1) aura_core::aur::dependencies: Trying to get ALPM handle (12 idle connections)
16:01:18 [DEBUG] (1) aura_core::aur::dependencies: Got a handle.
16:01:18 [DEBUG] (1) aura_core::aur::dependencies: Satisfaction (false) for amdgpu-clocks-git.
16:01:18 [DEBUG] (1) aura_core::aur::dependencies: amdgpu-clocks-git is an AUR package.
16:01:18 [ERROR] [60] SSL peer certificate or SSH remote key was not OK (SSL certificate problem: certificate has expired)
aura :: There were multiple errors during dependency resolution.

 - A CURL transaction failed.
 ```

**Comment by fosskers** [comment]
Thanks for the report - I'm surprised that the inner error isn't being reported already. Let me check.

**Comment by fosskers** [comment]
In general my [Faur](https://git.sr.ht/~fosskers/faur) server had busted itself, but it's now fixed. `-A` functionality is restored.

**Comment by fosskers** [comment]
Such an error now looks like:
```
aura :: A CURL transaction failed: [6] Couldn't resolve host name (Could not resolve host: aur.fosskers.ca)
```
