### ISSUE TITLE
"aura: Failure There was some failure." inside Docker container

### ISSUE THREAD

**Issue by AlexandreCarlton** [fosskers/aura#790]
### Bug
Hi! I am currently trying to use `aura` as part of an [Ansible](https://www.ansible.com/) playbook, tested using [Molecule](https://molecule.readthedocs.io/en/latest/)'s Docker driver.

However, I am seeing the following when trying to run `aura` inside the container:

```
aura: Failure There was some failure.
```

This error message makes it very hard to understand what went wrong and how it can be fixed.

### Reproduction
This can be reproduced using a simple docker image:

```dockerfile
FROM archlinux:latest

RUN pacman -Sy \
	&& pacman -S --noconfirm wget \
	&& wget https://github.com/fosskers/aura/releases/download/v3.2.9/aura-3.2.9-x86_64.tar.gz \
	&& tar xzvf aura-3.2.9-x86_64.tar.gz \
	&& mv aura /usr/local/bin

ENTRYPOINT ["/usr/local/bin/aura"]
```

And by running the following:
```shell
docker build . -t archlinux-aura
docker run --rm -it archlinux-aura --version
```
Or also by running (after having built the image):
```
docker run --rm -it --entrypoint=/bin/bash archlinux-aura
# aura --version
```

### Request
This isn't a request to fix the underlying problem (as it is entirely possible what is breaking in Ansible is different to the minimum reproducible example), but instead to surface what is breaking.

Thanks!

**Comment by AlexandreCarlton** [comment]
In case others hit this in future - running with `sudo` allows `aura` to work as normal. That said, it would be very appreciated if this could be surfaced to the user.

**Comment by fosskers** [comment]
That's a very strange error. Either way, you're better off getting Aura 4 (the new Rust port) working. As it's still technially alpha I don't have binary releases for it yet, but I will as soon as I'm able.

**Comment by fosskers** [comment]
Thanks for this. As I'm nearing the official release of Aura 4, I'm sweeping through old Issues here. I'm going to close this for now, but please let me know if you have similar issues after the release, or if there are any other problems in the future. Cheers!
