### ISSUE TITLE
download does not continue after network failure

### ISSUE THREAD

**Issue by Verneri** [fosskers/aura#794]
Hi,

I'm currently using my laptop with a bad hospital wifi with a captive portal. The wifi keeps cutting of and i need to go through the captive portal again and again. While using `sudo aura -Ax <package>` i noticed that when the wifi cuts of and i restart it the download never continues.

**Comment by fosskers** [comment]
Thanks for reporting your interesting situation! Are you using Aura 3 or Aura 4?

**Comment by fosskers** [comment]
Thanks for the original report. I'll close this for now, but please let me know if you have any further issues.
