### ISSUE TITLE
Error building a package due to unset variable

### ISSUE THREAD

**Issue by covertg** [fosskers/aura#804]
I recently tried to use `aura` to install the package [backintime](https://aur.archlinux.org/packages/backintime) from the AUR. Building that package failed due to what seems to be an issue with environment variables. A unit test (run upon package building) for that particular package expects the variable XDG_RUNTIME_DIR to be set.

I'm not entirely sure whatever environment that aura is running the unit test in, but it appears the variable is not set in that environment. Excerpt from package building:

```python
python -m unittest  -b test/test_backintime.py
WARNING: Failed to connect to Udev serviceHelper daemon via D-Bus: org.freedesktop.DBus.Error.ServiceUnknown
WARNING: D-Bus message: The name net.launchpad.backintime.serviceHelper was not provided by any .service files
WARNING: Udev-based profiles cannot be changed or checked due to Udev serviceHelper connection failure
.Fs
======================================================================
FAIL: test_local_snapshot_is_successful (test.test_backintime.TestBackInTime)
end to end test - from BIT initialization through snapshot
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/backintime-8278299993025593526/backintime/src/backintime-1.3.3/common/test/test_backintime.py", line 147, in test_local_snapshot_is_successful
    self.assertRegex(filtered_log_output, re.compile(r'''INFO: Lock
AssertionError: Regex didn't match: 'INFO: Lock\nINFO: Take a new snapshot. Profile: 1 Main profile\nINFO: Call rsync to take the snapshot\nINFO: Save config file\nINFO: Save permissions\nINFO: Create info file\nINFO: Unlock\n' not found in "INFO: Lock\nINFO: Take a new snapshot. Profile: 1 Main profile\nINFO: Call rsync to take the snapshot\nINFO: Save config file\nINFO: Save permissions\nINFO: Create info file\nQStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-cove'\nINFO: Unlock\n"
```

XDG_RUNTIME_DIR is set in my normal shell session (from which I'm running aura). Installing the package manually using `makepkg` works a-okay.

I thought it'd be prescient to report the issue here first, since you're probably best positioned to diagnose whether this is an aura issue, an issue with backintime, or user error.

Thanks in advance!

**Comment by fosskers** [comment]
I'm very sorry it took so long to respond to this. 

I just testing building `backintime` with the Aura 4 Beta, and it built without issue. Aura 3 had various issues with environment variables, all of which are now fixed. I will be releasing Aura 4 soon, after which you should see this solved.

Thanks again for the report.
