### ISSUE TITLE
Config template link in documentation leads to 404 error

### ISSUE THREAD

**Issue by HealerLFG** [fosskers/aura#805]
Config template link in github documentation Configuration > Aura "can be found here" leads to 404 error
[](https://github.com/fosskers/aura/blob/master/aura/doc/aura.conf)

**Comment by fosskers** [comment]
Fixed! Thanks for the report and sorry for the delay.

**Comment by fosskers** [comment]
Fixed! Thanks for the report and sorry for the delay.
