### ISSUE TITLE
aura seems not respecting proxy setting of curl?

### ISSUE THREAD

**Issue by jsomedon** [fosskers/aura#809]
I have proxy config on my `~/.curlrc` file, and by looking at the download speed(`-Ax`) I can tell that proxy is not working. I tried setting the proxy environment variables but still no luck.

FYI, I use `aura-bin` `3.2.9-1`, on arch linux(duh)

**Comment by fosskers** [comment]
Interesting issue, thank you for reporting. Would you be willing to try [the current state of the rewrite](https://crates.io/crates/aura-pm)?

**Comment by jsomedon** [comment]
Tried it and it seems to work with proxy config. Though this version seems to lack some command options like `-x` and `--force`?

**Comment by jsomedon** [comment]
btw, where is the source code for this 4.0 version?

**Comment by fosskers** [comment]
`-Ax` exists but is automatic - it doesn't actually do anything anymore. `--force` (a `makepkg` option) is also currently the default and happens automatically, but I may change this.

**Comment by jsomedon** [comment]
In that case, yeah let's close it.
