### ISSUE TITLE
 aura >>= As of makepkg v4.2, building as root is no longer possible.

### ISSUE THREAD

**Issue by rogue-agent** [fosskers/aura#815]
Hello world,

I didn't find anything similar? So I'll post it here.
I'm trying to install a package from aur but I get the following error. What can we do?

`➜  ~ doas aura -A js8call
aura >>= As of makepkg v4.2, building as root is no longer possible.       
➜  ~ aura -A js8call
aura >>= You cannot perform this operation without using sudo.`

**Comment by CowCowFuture** [comment]
#680

**Comment by fosskers** [comment]
Unfortunately Aura does not yet support `doas`. We hope to rectify this in Aura 4.

**Comment by fosskers** [comment]
Closing as a duplicate of #680
