### ISSUE TITLE
Aura 4 config parsing

### ISSUE THREAD

**Issue by nyaahilism** [fosskers/aura#819]
`aura :: Aura Configuration
  [✓] Aura config file exists?
  [✕] Aura config file can be parsed?
`
Hi, sorry is this is a silly question I’m still getting the hang of all this…

I’d hate to waste your time on such a small thing like this ( ˊᵕˋ ; ) but any answer you could give me I will appreciate greatly

Sincerely τнanκ чouﻌﻌﻌ♥

**Comment by fosskers** [comment]
Hi, it seems like you're trying out Aura 4? Thanks!

So it looks like you have a conflg file... but perhaps it can't be parsed? Can you paste your current config to me?

**Comment by nyaahilism** [comment]
I copied the config template the Aura Guide suggested, and saved it into .config as aura.toml as the man page suggested…

# --- Aura Config --- #
#
# Template updated on: Mon 11 May 2020
#
# You can uncomment the various settings below in order to activate them.
# Otherwise, Aura will use its internal defaults.

# --- Language --- #
# Aura can be used in different human languages. This field must be a 2-letter
# language code, similar to those used in LOCALE. The available codes are:
#
# |------+------------|
# | Code | Language   |
# |------+------------|
# | nl   | Dutch      |
# | en   | English    |
# | de   | German     |
# | nb   | Norwegian  |
# | sv   | Swedish    |
# |------+------------|
# | fr   | French     |
# | it   | Italian    |
# | pt   | Portuguese |
# | es   | Spanish    |
# | ro   | Romanian   |
# |------+------------|
# | ar   | Arabic     |
# |------+------------|
# | hr   | Croatian   |
# | cs   | Czech      |
# | pl   | Polish     |
# | ru   | Russian    |
# | sr   | Serbian    |
# | uk   | Ukrainian  |
# |------+------------|
# | zh   | Chinese    |
# | id   | Indonesian |
# | ja   | Japanese   |
# | vi   | Vietnamese |
# |------+------------|
# | eo   | Esperanto  |
# |------+------------|

# Uncomment to activate:
# language = en

# --- Build Settings --- #
# Aura runs via `sudo` but builds packages as the underlying non-root user.
# Here, you can alter who that user is, and where packages are built.

# Uncomment to activate:
 user = YOU
# buildpath = /tmp
# allsourcepath = /var/cache/aura/src
# vcspath = /var/cache/aura/vcs

# --- PKGBUILD Analysis --- #
# Aura automatically scans PKGBUILDs for malicious bash usage and other "bad
# practices". Here, you can turn those scans off.

# Uncomment to activate:
# analyse = True

# --- Misc. --- #

# The editor to use with `--hotedit`.
# Uncomment to activate:
# editor = vi

but here’s my current config.

Do you think I’d have an easier time using your older haskell Aura? I’m absolutely in love with Aura seeing as I’m a brand new user to Endeavor OS, it’s helped me immensely. Or should I download it via the AUR instead?

Thank you for all your help, again I greatly appreciate it!

**Comment by fosskers** [comment]
Ah, that's the Aura 3 config. Aura 4's config can be generated by doing:
```
aura conf --gen > ~/.config/aura.toml
```

You're free to use either 3 or 4, both should work fine! Using 4 helps me out with debugging new issues, though!

**Comment by nyaahilism** [comment]
Oh okay, thank you so much!
Seems everything checks out now!
```
　 ∩  ∩
　(｡･ᴗ･)♡
 ┏━━┓｡･ﾟﾟ･｡｡ﾟ♡
 ┗┓┏┛♬｡.｡. ☆
  ┃┃HANK　♡♬
  ┗┛ *YOU !!*ﾟ
```

**Comment by fosskers** [comment]
Enjoy, and please let me know if there are any other issues.
