### ISSUE TITLE
Regression? "Failed to 'git pull' the latest updates"

### ISSUE THREAD

**Issue by muchgitsuchwow** [fosskers/aura#824]
Hey guys,

first of all thanks for the first/only pacman/AUR thingy that is just great.

I might have some regression or something related to #615. 

```
# via aura-bin package
aura -V
```

```                  
 __ _ _  _ _ _ __ _    Pacman v6.0.2 - libalpm v13.0.2
/ _` | || | '_/ _` |   Copyright (C) 2006-2021 Pacman Development Team
\__,_|\_,_|_| \__,_|   Copyright (C) 2002-2006 Judd Vinet
AURA Version 3.2.9     
 by Colin Woodbury     This program may be freely redistributed under
                       the terms of the GNU General Public License.
```
* /etc/aura.conf

```
# --- Aura Config --- #

user = my_unprivileged_user
buildpath = /tmp
allsourcepath = /var/cache/aura/src
vcspath = /var/cache/aura/vcs
```

## broken

Assumption: `/var/cache/aura/vcs` is non-existent.

```
sudo aura -Ax niri-git
```

```
sudo aura -Ax libumem-git
```

## working

Unprivileged user in $HOME.

```
aura -Aw libumem-git
tar xzf libumem-git*
cd libumem-git/
makepkg
```

```
sudo aura -Aackux  # this one updated e.g. ungoogled-chromium-bin
```

From `strace` it looks like that a repository has been cloned and removed again before the `"Failed to 'git pull' …"` message. Not a "how to read strace" expert here! No idea what's going on here. Note that the error comes up quite quickly, e.g.

```
sudo strace -o /tmp/aura.strace -- aura --noconfirm -Ax libumem-git  0.00s user 0.01s system 1% cpu 0.619 total
```

**Comment by fosskers** [comment]
Hi, thanks for the report.

As you've shown here, `-Aw` is mostly unrelated to the pulling occurring during builds. And you were able to build it on another machine. I myself just built it successfully here too, albeit with [the 4.0 alpha](https://crates.io/crates/aura-pm). 

Is the issue still occurring on your first machine?

**Comment by fosskers** [comment]
Thanks, let me know. One thing you can try it double-checking the permissions on the `vcs` directory that gets created.

Luckily in Aura 4 all such directories are done under the user's home, so a lot of permission-related problems go away.

**Comment by fosskers** [comment]
> When can I have aura 4? 

Right now!

```
cargo install aura-pm --version 4.0.0-alpha9
```
