### ISSUE TITLE
4.0 config file location not following XDG recommendations

### ISSUE THREAD

**Issue by muchgitsuchwow** [fosskers/aura#825]
Hi, 

```
~/.cargo/bin/aura conf --help|rg toml
```

```
-a, --aura               View the contents of ~/.config/aura.toml
```

From my understanding of XDG and a huge bunch of other tools, ... shouldn't that be `~/.config/aura/config.toml`?

**Comment by fosskers** [comment]
Many do but not all. I'm happy to switch it and make the previous location a backup for existing Alpha users.
