### ISSUE TITLE
aura rust - fails on every AUR package it doesn't recognize

### ISSUE THREAD

**Issue by stef204** [fosskers/aura#827]
Just compiled `aura rust`.
version = `aura-pm 4.0.0-alpha10`

````
sudo aura -Akuax                                      
aura :: Fetching package information...
aura :: Unknown package: python2-zc.lockfile
````
It fails here.

If I then use `--ignore python2-zc.lockfile`, it goes on to the next package it doesn't recognize or is no longer in the AUR and fails.

````
sudo aura -Akuax --ignore python2-zc.lockfile
aura :: Fetching package information...
aura :: Unknown package: dircolors-solarized-git
````
_NOTE: `aura haskell` does not have this problem_

_NOTE2: I see your comment about not needing to use `sudo` systematically with `aura` anymore._

NOTE3: I tried to get more info with `--log-level debug` but that crashes.

````
aura --log-level=debug -Akuax                                                   
thread 'main' panicked at /home/$USER/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.18/src/parser/error.rs:32:9:
Mismatch between definition and access of `log_level`. Could not downcast to TypeId { t: 61039940106262814190964159314373753670 }, need to downcast to TypeId { t: 105828227954140907518310272932909830069 }

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: IOT instruction (core dumped)  /home/$USER/.cargo/bin/aura --log-level=debug -Akuax
````

**Comment by fosskers** [comment]
Thanks for the report. I've experienced this as well and it's quite annoying. It seems to happen often with Python libraries; perhaps when they get promoted to `community` or something.

Perhaps in this case we should log a warning and then continue.

**Comment by fosskers** [comment]
Normally dependency checking has to occur first, so we confirm the "identity" of all packages up-front. But yes installed-yet-where-the-heck-did-you-come-from packages should be otherwise ignored.

**Comment by fosskers** [comment]
This has been solved on `master`.
