### ISSUE TITLE
Figure out how to give users the option of reviewing pkgbuild before building, to make Arch Wiki's analysis of Aur Helpers show this with no red categories

### ISSUE THREAD

**Issue by Star-X555** [fosskers/aura#840]
So, assuming this site is correct:
https://wiki.archlinux.org/title/AUR_helpers

Aura avoids almost all of the possibly unsafe behaviors of most AUR Pacman wrappers, EXCEPT one, which is File Review.

Arch Wiki describes File Review as such:

> File review
>    Does not source the PKGBUILD at all by default; or alerts the user and offers the opportunity to inspect the PKGBUILD manually before it is sourced. Some helpers are known to source PKGBUILDs before the user can inspect them, allowing malicious code to be executed.

This sounds like a bit of a dangerous thing potentially, so I think it'd be a good idea to figure out how to make Aura support this functionality properly, so that it's all green or yellow.

I did search issues for "file review" and didn't see any, so I'm assuming no one else has come forward with this issue.  If they have and I'm too much of a Linux noob to notice, please go ahead and delete the issue.  Mostly I just want to see my preferred AUR software actually have all needed functionality for proper security and etc.

**Comment by fosskers** [comment]
Aura does already allow this via `--hotedit`. I would say the chart on the Wiki is incorrect.

**Comment by ultimatespirit** [comment]
As I recall `aura` already runs some checkers looking for potentially malicious code in `PKGBUILD`s too, before sourcing it. So making `--hotedit` a default would be overkill in my opinion. That being said, it could be worthwhile to have some sort of `AURA_ALWAYS_HOTEDIT=...` environment variable, or configuration option in a `~/.config/...` area, that enables a user to more easily always be able to scrutinise the `PKGBUILD` for this issue?

**Comment by fosskers** [comment]
Luckily there is such a setting! In the [Aura 4](https://crates.io/crates/aura-pm) Beta, that looks like:
```
[aur]
hotedit = true
```
located at `~/.config/aura/config.toml`.

**Comment by fosskers** [comment]
Closing, thanks for the report.
