### ISSUE TITLE
Am I able to skip some AUR packages like what yay do?

### ISSUE THREAD

**Issue by Nambers** [fosskers/aura#842]
I had a `java17-openjfx` in AUR as dependency of [autopsy](https://aur.archlinux.org/packages/autopsy) and it is pretty annoying in updating it. So I decide to just skip that every time I used `yay` to update all packages.

**Comment by fosskers** [comment]
Yes, in Aura 3, you can add `autopsy` to the `IgnorePkg` field in your `/etc/pacman.conf`.

In [Aura 4](https://crates.io/crates/aura-pm), you can first generate a config file:
```
aura conf --gen > ~/.config/aura/config.toml
```
and then set the `ignores` list:
```
[aur]
ignores = ["autopsy"]
```
In either case, this package will be completely ignored when you do `-Au`.

**Comment by Nambers** [comment]
Gotcha
@fosskers but I met a issue when I `cargo install` 
```
> cargo install --path .
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/eritquearcus/github/aura/rust/aura-pm/Cargo.toml
workspace: /home/eritquearcus/github/aura/rust/Cargo.toml
error: found a virtual manifest at `aura/rust/Cargo.toml` instead of a package manifest
```

**Comment by fosskers** [comment]
You'll want to do `cargo install --path aura-pm` instead from within `rust/`, not the `aura-pm/` directory.

**Comment by Nambers** [comment]
> You'll want to do `cargo install --path aura-pm` instead from within `rust/`, not the `aura-pm/` directory.

This works. Can you fix it in the readme as well?

> The "unknown package" thing I already fixed yesterday when another user pointed it out to me.

Yes it turns into warning.

One more issue: I faces a difficulty in upgrading aur package `xray-geoip`:
```log
aura :: Building xray-geoip...
==> Making package: xray-geoip 202406060042-1 (Wed 12 Jun 2024 05:04:45 PM MST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading geoip-202406060042.dat...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 10.8M  100 10.8M    0     0  11.3M      0 --:--:-- --:--:-- --:--:-- 16.4M
  -> Downloading LICENSE...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 20137  100 20137    0     0  42487      0 --:--:-- --:--:-- --:--:--     0
==> Validating source files with sha256sums...
    geoip-202406060042.dat ... Passed
    LICENSE ... Passed
==> Extracting sources...
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "xray-geoip"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: xray-geoip 202406060042-1 (Wed 12 Jun 2024 05:04:51 PM MST)
mv: cannot stat '/home/eritquearcus/.cache/aura/builds/xray-geoip/xray-geoip-debug-202406060042-1-any.pkg.tar.zst': No such file or directory
aura :: Package failed to build, citing:

  Failed to move: /home/eritquearcus/.cache/aura/builds/xray-geoip/xray-geoip-debug-202406060042-1-any.pkg.tar.zst
```
but it works when I turns into `yay`.

**Comment by fosskers** [comment]
I was able to build `xray-geoip` just now without issue. Is the problem still occurring for you?

It looks like you have `debug` builds enabled. You can disable them in your `/etc/makepkg.conf` if that's not what you intended.

**Comment by Nambers** [comment]
> I was able to build `xray-geoip` just now without issue. Is the problem still occurring for you?
> 
> It looks like you have `debug` builds enabled. You can disable them in your `/etc/makepkg.conf` if that's not what you intended.

yep
![image](https://github.com/fosskers/aura/assets/35139537/6f66203f-0d3f-4ccb-8970-34231c7b9e2a)

**Comment by fosskers** [comment]
Can you navigate to `~/.cache/aura/builds/xray-geoip/` and run:
```
makepkg --packagelist
```
and then paste the output here?

**Comment by Nambers** [comment]
> Can you navigate to `~/.cache/aura/builds/xray-geoip/` and run:
> 
> ```
> makepkg --packagelist
> ```
> 
> and then paste the output here?

```
> cd ~/.cache/aura/builds/xray-geoip
> makepkg --packagelist
/home/eritquearcus/.cache/aura/builds/xray-geoip/xray-geoip-202406130042-1-any.pkg.tar.zst
/home/eritquearcus/.cache/aura/builds/xray-geoip/xray-geoip-debug-202406130042-1-any.pkg.tar.zst
> ls
geoip-202406130042.dat  LICENSE  pkg  PKGBUILD  src
```

**Comment by fosskers** [comment]
```
/home/eritquearcus/.cache/aura/builds/xray-geoip/xray-geoip-202406130042-1-any.pkg.tar.zst
/home/eritquearcus/.cache/aura/builds/xray-geoip/xray-geoip-debug-202406130042-1-any.pkg.tar.zst
```
Aura uses the output of `makepkg --packagelist` to determine which built tarballs it should copy over to its internal cache. For some reason, it's not building the `-debug` build, but `makepkg` thinks it should be outputting one (at least w.r.t. the output of `--packagelist`). 

At any rate, for now if you add `!debug` to the `OPTIONS` list in your `/etc/makepkg.conf`, this problem should go away.

**Comment by Nambers** [comment]
> At any rate, for now if you add `!debug` to the `OPTIONS` list in your `/etc/makepkg.conf`, this problem should go away.

Yes this works.

**Comment by fosskers** [comment]
Yes I need to deal with it in a more robust manner before releasing Aura 4.

**Comment by Nambers** [comment]
> Yes I need to deal with it in a more robust manner before releasing Aura 4.

also can we have tab completion in 4? :D

**Comment by fosskers** [comment]
For which commands? It should already work for the standard `pacman` commands. `-A` isn't supported yet.

**Comment by Nambers** [comment]
> For which commands? It should already work for the standard `pacman` commands. `-A` isn't supported yet.

Both `-S` and `-A` don't work in my side. I'm using `konsole` with `zsh`

**Comment by fosskers** [comment]
`-S` works for me on fish. I'm not sure of the state of the zsh completions. I suppose because Aura isn't yet officially packaged through the AUR yet, the (normally) bundled completions aren't available on your system. For fish, completions are set within fish itself, so there's nothing to do on my end.

My next task is to port over as much of the existing localisations from the old Haskell version as possible. This unfortunately won't be complete, since Aura 4 added a number of new messages. So until new volunteers can localise the new messages, those will fallback to English.

**Comment by Nambers** [comment]
> `-S` works for me on fish. I'm not sure of the state of the zsh completions. I suppose because Aura isn't yet officially packaged through the AUR yet, the (normally) bundled completions aren't available on your system. For fish, completions are set within fish itself, so there's nothing to do on my end.
> 

I had [zsh-completions](https://github.com/zsh-users/zsh-completions) plugin, idk why it doesn't work. But `pacman` and `yay` do work well.

**Comment by fosskers** [comment]
I'll make sure this works by the time I do the official release.
