### ISSUE TITLE
nvidia-utils-beta driver package not building

### ISSUE THREAD

**Issue by cyuria** [fosskers/aura#844]
Aura doesn't quite work out of the box with the nvidia beta drivers.

The `nvidia-utils-beta` package fails to build with the following errors:
```
==> ERROR: install file (nvidia-utils.install) does not exist or is not a regular file.
==> ERROR: install file (nvidia-utils.install) does not exist or is not a regular file.
==> ERROR: install file (nvidia-utils.install) does not exist or is not a regular file.
```
And the other two beta driver packages, which themselves work perfectly fine, depend on the broken package (`nvidia-beta` and `lib32-nvidia-utils-beta`).

There have supposedly been issues with using other aur helpers like yay and the nvidia beta drivers for other people, but I got it working fairly trivially with aura (on my end at least).

All I had to do was copy `~/.cache/aura/packages/nvidia-utils-beta/nvidia-utils.install` to the `~/.cache/aura/builds/nvidia-utils-beta/` directory and then aura worked fine (although I did run `makepkg` manually first).

The package can also be installed by just traditionally cloning and running `makepkg` but it would be nice if it was possible to simply run `aura -A nvidia-utils-beta`.

I thought I'd report this in case it's an easy fix on your end, it's by no means a particularly big problem or one that needs to be fixed within any sort of time frame.

I'm running a fresh install of `v4.0.0-beta04` which I got via the following
```sh
git clone https://github.com/fosskers/aura
git checkout v4.0.0-beta04
cd rust
cargo install --path aura-pm --profile release
```

**Comment by fosskers** [comment]
Thanks for the report, and thanks for trying out the Beta. 

`~/.cache/aura/packages/nvidia-utils-beta/nvidia-utils.install` <- this looks suspicious to me. Particularly that the name of the install file differs from the package name smells.

Sure enough:
```rust
    // --- Copy non-downloadable `source` files and PKGBUILD --- //
    let install_file: Option<PathBuf> = {
        let install = info
            .pkg
            .install
            .as_deref()
            .map(PathBuf::from)
            .unwrap_or_else(|| Path::new(&base).with_extension("install"));
        clone.join(&install).is_file().then_some(install)
    };
```
Notice the `Path::new(&base).with_extension("install"))`. In this case it's looking for `nvidia-utils-beta.install` and not finding it, so not copying it.

**Comment by fosskers** [comment]
I've done some digging. 

- https://wiki.archlinux.org/title/Arch_package_guidelines
- https://wiki.archlinux.org/title/Pacman
- https://wiki.archlinux.org/title/Creating_packages
- https://wiki.archlinux.org/title/PKGBUILD#install

These pages hint at what the contents of a `.install` file should be, but not its naming convention. We see mentions of a `.INSTALL` file, but we've also always known about `foo.install` files as well.

In the manpage for `PKGBUILD` we see:
```
       install
           Specifies a special install script that is to be included in the
           package. This file should reside in the same directory as the
           PKGBUILD and will be copied into the package by makepkg. It does not
           need to be included in the source array (e.g.,
           install=$pkgname.install).
```
and in the Pacman source code we see:
```c
	/* run the post-install script if it exists */
	if(alpm_pkg_has_scriptlet(newpkg)
			&& !(trans->flags & ALPM_TRANS_FLAG_NOSCRIPTLET)) {
		char *scriptlet = _alpm_local_db_pkgpath(db, newpkg, "install");
		const char *scriptlet_name = is_upgrade ? "post_upgrade" : "post_install";

		_alpm_runscriptlet(handle, scriptlet, scriptlet_name,
				newpkg->version, oldpkg ? oldpkg->version : NULL, 0);
		free(scriptlet);
	}
```
which calls
```c
/* Note: the return value must be freed by the caller */
char *_alpm_local_db_pkgpath(alpm_db_t *db, alpm_pkg_t *info,
		const char *filename)
{
	size_t len;
	char *pkgpath;
	const char *dbpath;

	dbpath = _alpm_db_path(db);
	len = strlen(dbpath) + strlen(info->name) + strlen(info->version) + 3;
	len += filename ? strlen(filename) : 0;
	MALLOC(pkgpath, len, RET_ERR(db->handle, ALPM_ERR_MEMORY, NULL));
	snprintf(pkgpath, len, "%s%s-%s/%s", dbpath, info->name, info->version,
			filename ? filename : "");
	return pkgpath;
}
```
This makes it seem like `pacman` is looking for a very specifically named file, namely `/<dbpath>/<pkgname>-<pkgver>/install`. The next thing to check would be how `makepkg` is detecting such install scripts, and whether it's doing some renaming before shoving them into the package tarball.

**Comment by fosskers** [comment]
This is the only reference to it in `makepkg`:
```bash
	# check for changelog/install files
	for i in 'changelog/.CHANGELOG' 'install/.INSTALL'; do
		IFS='/' read -r orig dest < <(printf '%s\n' "$i")

		if [[ -n ${!orig} ]]; then
			msg2 "$(gettext "Adding %s file...")" "$orig"
			if ! cp "$startdir/${!orig}" "$dest"; then
				error "$(gettext "Failed to add %s file to package.")" "$orig"
				exit $E_MISSING_FILE
			fi
			chmod 644 "$dest"
		fi
	done
```

**Comment by fosskers** [comment]
I believe I've fixed this. Expect it in the upcoming Beta 5.
