### ISSUE TITLE
Update README to talk about the rust version / put a historical note about Haskell

### ISSUE THREAD

**Issue by ultimatespirit** [fosskers/aura#861]
I'm sure you're aware of this, but now that it looks like Aura 4.0 is finally into release candidates / the `aura-git` AUR entry has been updated to track 4.0, wanted to get a tracking issue down for the inevitable task of... cleaning up the README to actually be relevant to the rust work. All too often projects will do large changes and forget to update their README, so do remember to get that updated README onto main whenever appropriate ;).

In the interim, may want to at least note the Rust version exists, beyond the Cargo tag on the README, in the readme like "The next version of Aura (4.0) will be written in Rust" or something.

**Comment by fosskers** [comment]
I could put a quite note about it in the meantime, yes. I have a massive internal TODO list, where a README overall is one of the items.
