### ISSUE TITLE
Not clear on what to do in "Post-installation" step after this major version change

### ISSUE THREAD

**Issue by kureta** [fosskers/aura#862]
I am trying this AUR helper for the first time. It appears that the package is right in the middle of a major version change. Installed it via `yay -S aura-bin`. Commands `aura check` and `aura conf --gen` do not work. What should the new Post-install steps be?

Package-set snapshot feature looks awesome and that is why I am checking this out. Great work, thanks!

**Comment by fosskers** [comment]
Funny timing; I'm releasing the updated packages today. Try again in 24 hours or so and all the advertised commands should work.

**Comment by kureta** [comment]
Good to hear! I'll definitely install from git :)

**Comment by fosskers** [comment]
Try it now, I just reworked `aura-git` to include the Info manual (so `info aura` works).
