### ISSUE TITLE
Issue with CachyOS Package for aura-git

### ISSUE THREAD

**Issue by RubenKelevra** [fosskers/aura#865]
I encountered an issue with the AUR package for aura-git. After installing, the CachyOS binary package attempts to downgrade the version back to 4.0.0rc2.

I suspect this is the reason why the CachyOS package hasn't been updated yet.

It seems that the aura-git package may need an epoch bump to be preferred.

```
❯ sudo pacman -Syu
:: Synchronizing package databases...
 cachyos-v4 is up to date
 cachyos-core-v4 is up to date
 cachyos-extra-v4 is up to date
 cachyos is up to date
 core is up to date
 extra is up to date
 multilib is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Package (1)       Old Version           New Version               Net Change  Download Size

cachyos/aura-git  4.0.0.r0.geaac6297-3  4.0.0.rc2.r1.g8cb24082-1    0.04 MiB       0.98 MiB

Total Download Size:   0.98 MiB
Total Installed Size:  3.00 MiB
Net Upgrade Size:      0.04 MiB

:: Proceed with installation? [Y/n] 
```

**Comment by fosskers** [comment]
Thanks for the report.

It must be how the version was auto-generated within the PKGBUILD. Rather than curse this package's version with a `1:` prefix for all time, I'm tempted to wait until I release an inevitable `4.0.1`, which should trigger the upgrade within Cachy.

**Comment by RubenKelevra** [comment]
> It must be how the version was auto-generated within the PKGBUILD. Rather than curse this package's version with a 1: prefix for all time, I'm tempted to wait until I release an inevitable 4.0.1, which should trigger the upgrade within Cachy.

Not entirely. The main issue is the dash between the version number and the "rcX" part.

```bash
$ git describe --long --tags --abbrev=7 v4.0.0-rc2
v4.0.0-rc2-0-g52a05c5
```

```bash
$ echo "v4.0.0-rc2-0-g52a05c5" | sed 's/\([^-]*-g\)/r\1/;s/-/./g' | cut -c2-48
4.0.0.rc2.r0.g52a05c5
```

Meaning it results in a dot between 4.0.0 and rc2.

If you instead use 4.0.0rc2 in your tag:

```bash
$ git tag v4.0.0rc2
$ git describe --long --tags --abbrev=7 v4.0.0rc2
v4.0.0rc2-0-g3fd459b
```

Which is converted to:

```
$ echo "v4.0.0rc2-0-g3fd459b" | sed 's/\([^-]*-g\)/r\1/;s/-/./g' | cut -c2-48
4.0.0rc2.r0.g3fd459b
```

So Pacman prefers the 4.0.0.rc2 instead of 4.0.0.r0, because `c` is higher than `0`.

```bash
$ vercmp 4.0.0.r0.geaac6297-1 4.0.0.rc2.r1.g8cb24082-1
-1
```

But 4.0.0rc2 is lower than 4.0.0:

```bash
$ vercmp 4.0.0.r0.geaac6297-1 4.0.0rc2.r0.g52a05c5
1
```

So in summary you just need to create the rc/beta/alpha versions in the future without a dash, or adapt your PKGBUILD to remove the dash of the tags git provides:

```
$ echo "v4.0.0-rc2-0-g52a05c5" | sed -E 's/([0-9]+\.[0-9]+\.[0-9]+)-([a-z]+[0-9]*)(.*)/\1\2\3/'
v4.0.0rc2-0-g52a05c5
```
Btw: You're missing a `--abbrev=7` in your PKGBUILD according to [the wiki](https://wiki.archlinux.org/title/VCS_package_guidelines#Git) that should be used. But it's not related to the issue. :)

**Comment by fosskers** [comment]
I've altered `pkgver()` slightly and it will be reflected in the next release. Thanks for the tips.

**Comment by RubenKelevra** [comment]
Btw I think you can force a rebuild by writing a version like 4.0.0.rc4 in the git repo. I don't think CachyOS is doing the comparison based on the git repo of aura, just based on the PKGBUILD in the AUR repo itself. The wrong version will be discarded as soon as the package is being build. :)

**Comment by fosskers** [comment]
With the amount of bug reports I'm getting already, there will be a new release soon enough.

**Comment by fosskers** [comment]
I've released `4.0.1`, so let's consider this solved. Thanks again for reporting it.

**Comment by RubenKelevra** [comment]
At the moment it's not yet fixed. But I'll let you know when that changes:

```
❯ paru -Sy --repo aura-git
:: Synchronizing package databases...
 cachyos-v4 is up to date
 cachyos-core-v4 is up to date
 cachyos-extra-v4 is up to date
 cachyos is up to date
 core is up to date
 extra is up to date
 multilib is up to date
 aur is up to date
resolving dependencies...
looking for conflicting packages...

Package (1)       Old Version         New Version               Net Change

cachyos/aura-git  4.0.r0.geaac6297-1  4.0.0.rc2.r1.g8cb24082-1    0.04 MiB
```

**Comment by ptr1337** [comment]
Git packages get compiled at us once a week, every monday at around 15:00.
Checking the version rn:
```
cachyos/aura-git 4.0.1.r0.g884e787-1
    A package manager for Arch Linux and its AUR
```

**Comment by fosskers** [comment]
The current version on the AUR is `4.0.3.r0.g3aae462-1`.
