### ISSUE TITLE
Feature Request: Support for `--asdeps` for AUR packages

### ISSUE THREAD

**Issue by RubenKelevra** [fosskers/aura#870]
I'm currently using Aura 4.0.0. I noticed that Aura does not support `--asdeps`, which is kinda necessary if you want to install optional dependencies from the AUR and have pacman clean them up properly on deinstall.

```
$ aura -A --asdeps python-libnacl
error: unexpected argument '--asdeps' found

  tip: to pass '--asdeps' as a value, use '-- --asdeps'

Usage: aura {aur|--aursync|-A} [OPTIONS] [PACKAGES]...

For more information, try '--help'.
```

**Comment by fosskers** [comment]
This must be an oversight, something lost during the port. I'll fix it.

**Comment by RubenKelevra** [comment]
Thanks for the fast fix! :)
