### ISSUE TITLE
Failed to parse .SRCINFO

### ISSUE THREAD

**Issue by stef204** [fosskers/aura#871]
```
% /aura --version        
aura-pm 4.0.0-beta04
```
trying to run:

```
~/.cargo/bin % ./aura -Akuax -- --debug
aura :: Fetching package information...
aura :: Unknown package: num
[insert long list of packages here]
```
gives me a really long list of `foreign` packages which then ends with error message:
`Failed to parse .SRCINFO aura/packages/genwipe.sh/.SRCINFO`

**Comment by fosskers** [comment]
Thanks for the report. Separate from that, Aura 4 is properly released now, so do install the main https://aur.archlinux.org/packages/aura package.

**Comment by stef204** [comment]
ooops, didn't notice the release. I've uninstalled the beta version and installed the "official" `AUR` package.
I'll need to get familiar with the new config options, etc.
For now, I am still getting the same error, and on more than one package:
`aura :: Failed to parse .SRCINFO: $HOME/.cache/aura/packages/genwipe.sh/.SRCINFO`
It's in `cache` so I could just nuke `$HOME/.cache/aura/` to start fresh, and take if from there.

**Comment by fosskers** [comment]
Clearing out just `packages/genwipe.sh/` might also suffice.

**Comment by fosskers** [comment]
Are you able to successfully do `aura -Ap genwipe.sh`? I am not. An `-Aw` also pulls an entirely blank repository.

**Comment by fosskers** [comment]
```rust
/// Clone a package's AUR repository and return the full path to the clone.
pub fn clone_aur_repo(root: Option<&Path>, package: &str) -> Result<PathBuf, crate::git::Error> {
    let mut url: PathBuf = [AUR_BASE_URL, package].iter().collect();
    url.set_extension("git");

    let clone_path: PathBuf = match root {
        None => PathBuf::from(package),
        Some(r) => r.join(package),
    };

    crate::git::shallow_clone(&url, &clone_path).map(|_| clone_path)
}
```
`set_extension`

**Comment by fosskers** [comment]
Fixed in https://github.com/fosskers/aura/commit/a1ad55530099673a2f247e10b56b67dd67043a99 .
