### ISSUE TITLE
aura :: Failed to parse .SRCINFO

### ISSUE THREAD

**Issue by stef204** [fosskers/aura#872]
version 4.0.0 (latest release)

Still getting this error:

```
% aura -Au --log-level=debug
aura :: Failed to parse .SRCINFO: $HOME/.cache/aura/packages/openssl-1.0/.SRCINFO
```
I can `--ignore` that package but it then gives me another identical error with a different package.

**Comment by fosskers** [comment]
Have you installed `aura` or `aura-git`? The fix would only be available in `aura-git` at the moment. I'll release an official `4.0.1` on the weekend.

**Comment by stef204** [comment]
Still on `aura` stable version, let me switch to the `git` version, probably a good idea to do so.

**Comment by fosskers** [comment]
If you want to go nuclear, you could delete everything in `.cache/aura/packages/`. Basically everything in there that has an extension-like piece to it will need to be recloned.

**Comment by stef204** [comment]
sure, why not ;) 
Let me do that and report here.

**Comment by fosskers** [comment]
What's the output of:
```
aura -Qm
```
for you?

**Comment by stef204** [comment]
```
% aura -Qm | wc -l 
558
```

**Comment by fosskers** [comment]
Sweet christ, alright. Then you're a good test case actually. That's only `34` for me. Perhaps certain lookups / clone attempts get flakey with such a high count.

**Comment by stef204** [comment]
One question:  there is a LONG list of packages which `aura` doesn't recognize -- I don't understand why.  Yes I have packages installed from the `AUR` early on which I have not used nor updated for a long time (which at some point I should remove) but the fact that `aura -Au` produces such a long list of "unknown packages" (and apparently ignores the packages in that list, is hard to understand for me.)

**Comment by stef204** [comment]
> Another pro hack: `aura -Aw <whatever>` _inside_ of `~/.cache/aura/packages/`. That'll guarantee you've got the right thing (provided it didn't exist already), if there seem to be packages giving you trouble.

```
% cd .cache/aura/packages
aura -Aw sent       
aura :: Cloning sent...
aura :: A git clone failed: https://aur.archlinux.org/sent.git
```

**Comment by stef204** [comment]
NOTE: AUR seems to be down right now, at least for me

**Comment by stef204** [comment]
OK, I restarted troubleshooting.

```
% aura -Au --log-level=debug
[snpi]
aura :: Comparing package versions...
19:01:54 [INFO] Reading .SRCINFO files...
19:01:54 [ERROR] key 'optdepends' requires a value: Line 8: optdepends =
aura :: Failed to parse .SRCINFO: /home/stef/.cache/aura/packages/batstat-git/.SRCINFO
```

**Comment by fosskers** [comment]
> the fact that aura -Au produces such a long list of "unknown packages" (and apparently ignores the packages in that list, is hard to understand for me.

Those warnings are for people to notice when a package has been deleted from the AUR (sometimes by being moved to official repos). I hadn't considered the case where many many such packages would exist on the system. And yes they're otherwise ignored.

> my IP got temporarily banned for too many requests

Aura doesn't call the AUR RPC at all anymore, but perhaps it got mad at you for attempting to many internal `git clone`s.

> `batstat`

Looking at the PKGBUILD:

```
optdepends=('')
```
This is a mistake and the maintainer of the package should be notified. It may also be that a bug report to https://github.com/morganamilo/srcinfo.rs could be filed to account for this edge case.

**Comment by SinnerK0N** [comment]
I have the same issue, the directory in which its trying to read .SRCINFO contains only a `.git` folder and nothing else.

Here is the output of the log:
```
$ aura -Au --log-level=debug
aura :: Comparing package versions...
10:59:35 [INFO] Reading .SRCINFO files...
10:59:35 [ERROR] No such file or directory (os error 2)
aura :: Failed to parse .SRCINFO: /home/sinner/.cache/aura/packages/openssl-1.0/.SRCINFO

$
```

And listing of the directory:
```
$ ls -lA /home/sinner/.cache/aura/packages/openssl-1.0
total 0
drwxr-xr-x 1 sinner sinner 98 srp  3 09:48 .git

$
```

**Comment by fosskers** [comment]
This is fixed in `master` and will be included in a release I make tomorrow. You'll also have to manually delete the `~/.cache/aura/packages/foo` directory that is causing the issue.

Note to self: a new `aura check` condition should be added that searches the `packages/` directory for empty directories.

**Comment by stef204** [comment]
> Since failure to parse a `.SRCINFO` is a critical error, the only way around this at the moment is to delete the package or create a custom build of it for yourself.

That's fine. But shouldn't `aura` give some kind of error message or warning and then move on to the next package Instead of exiting with error?

**Comment by stef204** [comment]
I've deleted the `batstat-git` package. `aura` now proceeds, showing me a list of 7 or 8 candidate packages for upgrade.

```
aura :: AUR packages:
[insert list of packages]
```

However, I do not like this behavior.
I might not want to upgrade one or two of these intentionally.

Yes, I could `--ignore` them or add them to `pacman.conf`.

But I do not like that approach for the `AUR`.

I would suggest behavior like `trizen` which shows you the list (it's a numbered list) and asks you to confirm default (`All`) or type in the number corresponding to the packages you do want to upgrade, as a comma separated list.

Example:
`1,3,4,6`

then press <enter> and upgrade those.

EDIT: I tried to add them to `pacman.conf` but `aura` doesn't seem to read the `IgnorePkg` section of `pacman.conf`.

This likely requires another new issue as we are starting to get off the original topic here. But it should be addressed.

**Comment by fosskers** [comment]
Have you set up a config file yet?
```
aura conf --gen > ~/.config/aura/config.toml
```
Then you can set the `ignores` list there. More information here: https://fosskers.github.io/aura/configuration.html

**Comment by stef204** [comment]
@fosskers 
Sorry, I still have to get used to the new version.
The config file section `ignores` does not seem to work; or be taken into consideration.
No matter what I put there, `aura` wants to update it anyway.
What is the proper format for the list? Inside the `[]`? Separated by `,` or a space, etc.?

**Comment by fosskers** [comment]
Within the `[aur]` block, mine looks like:
```
ignores = ["anki", "aseprite", "clasp-cl", "tic-80-git"]
```
And it does successfully ignore those packages during `-Au`.
