### ISSUE TITLE
aura 4.0 does not de-escalate sudo / warn about it

### ISSUE THREAD

**Issue by ultimatespirit** [fosskers/aura#873]
With `aura` 4.0 it is no longer necessary to prepend `sudo` to an `aura` invocation, as it was before.  Instead `aura` detects when it should or should not use `sudo`, according to the manual.

Unfortunately, it appears this does not extend to `aura` detecting if it _was_ used with `sudo`, for example by someone used to the prior versions or otherwise used to `sudo pacman -S`. Instead it goes ahead and it seems uses `makepkg` as root, or at least some configuration steps, as I had packages failing to build from attempting to access paths that it clearly should not have been (like thinking its `$HOME` was `/`).

Probably `aura` should now just refuse to run with `sudo` (maybe have an override option), or intelligently de-escalate the sudo immediately.

**Comment by fosskers** [comment]
Thanks for the report, I will think about this.

**Comment by fosskers** [comment]
This is now a priority.

**Comment by ultimatespirit** [comment]
Thanks for fixing it! Though, looking at the commit seems you went with the "just don't let it be run with `sudo`" option, and going off the latest issues in the tracker seems you're getting the good ole [xkcd 1172](https://xkcd.com/1172/). Best of luck with that one haha :)
