### ISSUE TITLE
`aura check` does not check `$XDG_CONFIG_HOME`/pacman/makepkg.conf

### ISSUE THREAD

**Issue by ultimatespirit** [fosskers/aura#874]
The `aura check` command has a section referring to the configuration of `/etc/makepkg.conf` for the `PACKAGER` variable. This section erroneously does not consult `$XDG_CONFIG_HOME/pacman/makepkg.conf` it looks like, and therefore will mark that section as uncompleted even if the variable is set in the local configuration. I'm not sure if it checks anything else / is potentially missing any other checks on that file.

**Comment by fosskers** [comment]
Thanks, this is an oversight. I'll add that as a legal location for `makepkg.conf`.

**Comment by fosskers** [comment]
Fixed on `master`.
