### ISSUE TITLE
aura conf-gen should generate directory

### ISSUE THREAD

**Issue by ptr1337** [fosskers/aura#875]
Currently when using aura conf-gen it does not generates the directory and therefore it fails:

```
aura conf --gen > ~/.config/aura/config.toml
warning: An error occurred while redirecting file '/home/ptr1337/.config/aura/config.toml'
warning: Path '/home/ptr1337/.config/aura' does not exist
``` 

This should be maybe automatically done.
Using 4.0 release.

**Comment by fosskers** [comment]
He there, this is already solved on `master`. I will be making a new release tomorrow.
