### ISSUE TITLE
Suppress List of Foreign or Unavailable Packages

### ISSUE THREAD

**Issue by stef204** [fosskers/aura#877]
`aura` shows a really long list of `foreign packages` like `aura :: Unknown package: inxi-git` (or packages which have been dropped form the ~AUR`) every time I use `aura -Au`.

The list is quite long and I really would like to suppress it so it does not show up each time I use `aura` to update.
I would suggest adding either flag or even better a config option to suppress this list from showing up.

**Comment by fosskers** [comment]
Thanks for another good suggestion. It's done.
