### ISSUE TITLE
Aura 4.x doesn't seem to pass `--noconfirm` over to `pacman -U` call

### ISSUE THREAD

**Issue by mintsuki** [fosskers/aura#882]
As per title.

**Comment by fosskers** [comment]
Thanks for the report. What specifically were you attempting when you saw this?

**Comment by mintsuki** [comment]
I was trying to install a package using `aura -Aax --noconfirm`, and, while aura did not ask for any prompts, the `pacman -U` call did.

**Comment by fosskers** [comment]
Thanks, I'll fix that.

**Comment by fosskers** [comment]
By the way, `-x` is no longer necessary.

**Comment by mintsuki** [comment]
Yeah, I am aware, but this was from a script, so...

**Comment by fosskers** [comment]
For just such cases I left `-x` in to preserve people's older use-cases.

**Comment by pushcx** [comment]
Similarly, running `aura -Cc 1 --noconfirm` has started erroring out, saying `error: unexpected argument '--noconfirm' found` from a script. But leaving it out leads to an interactive prompt about whether to proceed.

**Comment by fosskers** [comment]
Thanks, must have been an oversight. I'll add it back.

**Comment by fosskers** [comment]
Done. You'll see this in the next release in a few days. Otherwise you can switch to `aura-git` if you need the fix immediately. Cheers.
