### ISSUE TITLE
Temporary installations of packages 

### ISSUE THREAD

**Issue by RubenKelevra** [fosskers/aura#883]
I know this may sound weird, but I often find myself wondering why I installed certain packages - especially on very old Arch Installations - as I look through the to-be-updated.

So I test some software or need a library for some project and then just forget to remove them afterwards.

I was wondering if there's a chance that I'm not alone with that, and if Aura could get a function to store that certain packages, while explicit, shall be removed again after a time interval have passed.

Something like `aura -S --temporary=30d firefox`, and after 30 days a warning will be shown on every update, that you wanted to remove the package firefox again.

And running `aura -Rs --temporary` or something like that, will remove all packages which reached the end of the installation period.

While a simple `aura -S firefox --needed` will remove the mark, that it's just temporary.

Hope this makes sense and is useful for others :)

**Comment by RubenKelevra** [comment]
Well, technically it wouldn't change anything about Aura behaving like Pacman. It would just add a timestamp of when to show a warning in it's own database.

Since it's a user choice to use this flag, it wouldn't change how Aura behaves unless the user choose to divert from just using Pacman commands, like -A does as well.

On updates this could act like an additional Pacman hook, meaning it would show up on Pacman updates as well as warning, after running the update and thus don't divert from Pacman's behavior.

The remove command would just look through the database and add all outdated packages instead of the keyword.

**Comment by RubenKelevra** [comment]
If you're not comfortable extending the command itself, this could also be accomplished by using an environment variable, like

```
AURA_TEMPORARY_INSTALL='30d' aura -S firefox
```

In this case a pacman hook could also do the storing of the info.

But this feels kinda clumsy

**Comment by fosskers** [comment]
Now that I think, this is probably a suggestion best made upstream to Pacman itself: https://gitlab.archlinux.org/pacman/pacman/
You may need to ask on the mailing list instead of that repo.

Either way, I think it's best that this feature be left out of Aura. Thanks as always for your suggestions and bug reports.

**Comment by RubenKelevra** [comment]
Pacman maintainers are from my experience not open for feature suggestions - so I won't even waste my time writing a feature request there.

Sad. Would be very helpful IMHO. But okay.

**Comment by fosskers** [comment]
Thanks for understanding.
