### ISSUE TITLE
Auto-generate "cache" and "hashes" folders inside ~/.cache/aura/

### ISSUE THREAD

**Issue by PickMeNow** [fosskers/aura#884]
Started using this package manager today, congratz on 4.0.1 version!!

I detected that "cache" and "hashes" folder don´t automatically generate if they are deleted from .cache/aura/ generating errors in installing/updating packages. 

You might be wondering why were these folders deleted, I noticed BleachBit automatically deletes these folders as part of their cleaning process.

The errors only disappear once I manually create them again, is it possible to auto-generate them if they are missing?

**Comment by fosskers** [comment]
> The errors only disappear once I manually create them again, is it possible to auto-generate them if they are missing?

They are always auto-generated if they don't exist, for instance:

```rust
/// The full path to the Aura-specific tarball cache.
///
/// Creates the directory if it doesn't exist.
pub(crate) fn tarballs() -> Result<PathBuf, Error> {
    let path = aura_xdg_cache()?.join("cache");

    if path.is_dir().not() {
        std::fs::create_dir_all(&path).map_err(|e| Error::Mkdir(path.clone(), e))?;
    }

    Ok(path)
}
```
Why would another program being going through `~/.cache/` and clearing out things that don't concern it?

**Comment by PickMeNow** [comment]
BleachBit is a program to clean the system and free space, so far I didn't have any issues that I can recall with other packages.

My assumption might be wrong,  but if I would completely delete the insides of the .cache folder, it shouldn't cause issues for the packages installed aside from requesting new logins or taking more time to load, kinda like the .config folder, I can wipe out the contents completely to reset settings - It would recreate the normal settings/structure .cache/aura and all their insides cache, hashes etc once I rerun these packages.

**Comment by fosskers** [comment]
It's technically fine to have an empty `~/.cache/aura/`, but it will slow Aura down overall. Pre-cloning all the packages you care about greatly speeds up dependency resolution, and Aura's own built package cache lives at `~/.cache/aura/cache/`.

**Comment by PickMeNow** [comment]
I will provide some screenshots of the problem I am experiencing to explain:

after executing BleachBit
![image](https://github.com/user-attachments/assets/229dada2-c626-4258-bea1-0e685ee9c913)

When I try to reinstall an app in official packages it works well:

![image](https://github.com/user-attachments/assets/f3c22be5-01cf-4eaa-8d3b-a56eeca3ccce)

When I try an package from AUR results into an error:

![image](https://github.com/user-attachments/assets/03cc3a70-ff40-41f3-925c-0379fc744efa)

So at the end I need to recreate aura folder structure on .cache

Hope the screenshots help

**Comment by fosskers** [comment]
> Regarding the cache structure I saw another request to perhaps put the AUR packages in another folder [custom], this could be the solution without using the .cache structure.

This is actually already what happens. You can customise the cache location too, see: https://fosskers.github.io/aura/configuration.html#aur-package-building

**Comment by PickMeNow** [comment]
That works!!!

Thank you!

**Comment by fosskers** [comment]
Shall we close this then?

**Comment by PickMeNow** [comment]
Yes, thank you once again!
