### ISSUE TITLE
One command to update all official and AUR packages

### ISSUE THREAD

**Issue by PickMeNow** [fosskers/aura#885]
Maybe I am just to used to paru and yay, but I noticed both package managers once you enter "paru" or "yay" in the terminal they update both official packages and AUR packages.

Would be nice to have this is aura as well so when we enter a simple command or just simply "aura" in the terminal it would update the official packages and then AUR packages. Could be improved by adding this option to config.toml.

**Comment by fosskers** [comment]
Thanks for the suggestion. It has been Aura's stance since the beginning that `-S`and `-A`are completely separate. 

See https://github.com/fosskers/aura?tab=readme-ov-file#arch-is-arch---aur-is-aur .

If you'd like `-Au` to run after `-Su`, you could create a shell alias.
