### ISSUE TITLE
`aura deps` fails 

### ISSUE THREAD

**Issue by abdeoliveira** [fosskers/aura#886]
Successfully installed `aura` and passed in all `aura check` items. 

Casting `aura deps` or the example `aura deps gcc --reverse --optional --limit=3 --open`  results in `aura :: Failed to generate the dependency image.` 

Perhaps missing some needed software in my system?

**Comment by fosskers** [comment]
Thanks for reporting this. 

Check `man aura` and look at the initial description of the `deps` command. It contains instructions for setting the program that's used to open image files via `xdg-open`.

**Comment by abdeoliveira** [comment]
Thanks for the superfast reply. 

My `~/.config/mimeapps.list` is well-configured and `exo-open` works as intended. I feel like aura needs some package responsible for generating the image which is missing in my system. How can I check that?

**Comment by abdeoliveira** [comment]
Thank you for your superfast reply. Still no luck. 

I do have `~/.config/mimeapps.list` file well-configured. Both `exo-open` and `xdg-open` work as expected. 

Which programa `uses` to generate the `.png` file? Perhaps it is missing in my system?

**Comment by fosskers** [comment]
Ahh of course:
```
   let mut child = Command::new("dot")
        .arg("-Tpng")
        .arg("-o")
        .arg(&path)
        .stdin(Stdio::piped())
        .spawn()
        .map_err(Error::Io)?;
```
It's `dot`, which:
```
> aura -Qo dot
/usr/bin/dot is owned by graphviz 12.0.0-1
```
I will add an entry for `dot` within `check`, as well as an optional dependency in the PKGBUILD for `graphviz`.

**Comment by abdeoliveira** [comment]
Perfect! It is working now. Thanks!

**Comment by abdeoliveira** [comment]
P.S. -- How beautiful is this `deps` functionality. It is really clever :-)

**Comment by fosskers** [comment]
Thanks! Yeah I use it all the time too.

**Comment by amigthea** [comment]
I'm trying aura for the first time and just stumbled on this exact problem; I used `check` but I did not see any unmet dependencies, so I got there =)
I was in awe for this package manager and see you so responsive with the community brought me a smile. Keep it up with this awesome project!
