### ISSUE TITLE
"No usable snapshots found." when running aura -Br

### ISSUE THREAD

**Issue by ClangPan** [fosskers/aura#887]
Hello,

I wanted to try out this package for the ability to create snapshots of the currently installed packages, but while ``aura -B`` manages to save the current state properly, trying to restore it with ``aura -Br`` gets me the error ``No usable snapshots found.``
![image](https://github.com/user-attachments/assets/8919946d-69f7-4f80-8195-462a00486bc8)

As you can see the files are properly created 
![image](https://github.com/user-attachments/assets/0e207463-0517-4b74-9443-a4adb3902efa)

I did try to add/remove/update packages to see if it changed anything, but it did not

Do you have any idea what might be causing this?

**Comment by fosskers** [comment]
Thanks for the report. Try `aura check` and see what it tells you regarding your Package States. It might be that you're missing tarballs.

**Comment by ClangPan** [comment]
Ah indeed there aren't any tarball generated
![image](https://github.com/user-attachments/assets/7abcf09b-114a-40b4-b07b-98b667b82aa1)
![image](https://github.com/user-attachments/assets/07369466-2651-4212-9934-af1caa74840b)

Tho it doesn't let me proceed due to dependencies
![image](https://github.com/user-attachments/assets/5c6c4d81-1749-4df9-b553-38506cf2d721)

**Comment by fosskers** [comment]
Looks like you should do an `-Syu` first eh.

**Comment by ClangPan** [comment]
Yes, indeed, due to the message it gave me I thought it was gonna update my system, which, as you can tell by my need of aura -B, isn't really what I want ^^

It managed to cache the Official packages, but the AUR ones are gonna take a while (I wonder why you can only cache them manually?), so I'll come back to you in a bit

**Comment by fosskers** [comment]
To anyone coming here from the future: Aura is not like Guix / Nix in the sense that Aura can't retrieve copies of past packages from the internet. The rollbacks enabled by `-B` are only possible if you have copies of the target packages on your machine already.

**Comment by fosskers** [comment]
"No usable shapshots found" will be printed if, for each snapshot saved, there is _some_ tarball missing from it.

**Comment by ClangPan** [comment]
Alright, after properly reinstalling all my AUR packages, it indeed fixed the issue, and I was able to restore a backup!

Would be nice if this message could be updated to inform the user of the issue ^^

**Comment by fosskers** [comment]
Thanks for going through all that effort! Good to know that it works. I'm going to close this for now.
