### ISSUE TITLE
--download-only / -w option expects parameters

### ISSUE THREAD

**Issue by cfinnberg** [fosskers/aura#888]
The option to only download the packages (`--download-only` or `-w`) expects some parameter:
```
> aura -Syuw
error: a value is required for '--downloadonly <packages>...' but none was supplied
```

`pacman` works fine with this.

```
> aura -V
aura 4.0.1
```

**Comment by fosskers** [comment]
Verified locally: `sudo pacman -Syuw` works but the same in Aura does not. This is an easy fix.
