### ISSUE TITLE
-k option doesn't work

### ISSUE THREAD

**Issue by cfinnberg** [fosskers/aura#889]
I just did:
```
> aura -Auk thunderbird-beta-bin
```

but no diff of the PKGBUILD was presented to me (nor I was asked if I wanted to see it)

aura 4.0.1

**Comment by fosskers** [comment]
It would only produce such a diff if you had built the packages using Aura once before.

**Comment by cfinnberg** [comment]
Makes sense. Didn't think of that. Thanks for the answer!
