### ISSUE TITLE
Aura 4.x unable to find package libstdc++5

### ISSUE THREAD

**Issue by Crouze** [fosskers/aura#891]
Install or update of AUR package _libstdc++5_ fails:

<code>$ aura -A libstdc++5
aura :: Determining dependencies...
aura :: The package libstdc++5 does not exist.
</code>

<code>$ aura -U libstdc++5
loading packages...
error: 'libstdc++5': could not find or read package
aura :: A call to pacman gave a non-zero exit code.
</code>

A previous version of libstdc++5 exists on the system, installed with Aura 3.x.
The package does exist in the AUR (<url>https://aur.archlinux.org/packages/libstdc++5</url>).
Arch Linux x86_64.

I suspect the + or ++ in the package name to be the cause?

**Comment by fosskers** [comment]
Thanks for reporting.
