### ISSUE TITLE
Weird "git clone failed" transient (?) error, while manual cloning isn't an issue

### ISSUE THREAD

**Issue by RubenKelevra** [fosskers/aura#894]
I've updated to Aura 4.0.1 and the first time I tried updating my AUR packages I got this error. I thought it's a transient server issue, and repeated it. Still didn't worked. So I tried it manually, which worked, but trying again with Aura failed again.

Weirdest thing, it worked 5 minutes later with Aura.

Not sure if that's a bug or a server issue, but I actually never encountered issues like this with the AUR even once in all the years using ArchLinux. 🤔

Anyway, some more info would be nice here, if you can spare some dev time.

Btw: Also having `--verbose` work would be nice. I only later found in a different bug report `--log-level=debug`. Maybe you could make the more Unix standard `--verbose` an alias for that? 

```
$ aura -Ayu
aura :: Fetching package information...
aura :: A git clone failed: https://aur.archlinux.org/clion-eap.git
$ aura -Ayu
aura :: Fetching package information...
aura :: A git clone failed: https://aur.archlinux.org/clion-eap.git
$ git clone https://aur.archlinux.org/clion-eap.git
Cloning into 'clion-eap'...
remote: Enumerating objects: 1411, done.
remote: Counting objects: 100% (1411/1411), done.
remote: Compressing objects: 100% (812/812), done.
remote: Total 1411 (delta 602), reused 1407 (delta 599), pack-reused 0 (from 0)
Receiving objects: 100% (1411/1411), 272.21 KiB | 274.00 KiB/s, done.
Resolving deltas: 100% (602/602), done.
$ aura -Ayu
aura :: Fetching package information...
aura :: A git clone failed: https://aur.archlinux.org/clion-eap.git
```

5 minutes later:

```
$ aura -Ayu 
aura :: Fetching package information...
aura :: Comparing package versions...
aura :: AUR packages to upgrade:
 pip2pkgbuild        :: 0.5.0-1       -> 0.5.0-2
 reshade-shaders-git :: r79.87a9e51-1 -> r80.eed46c2-1
 tor-browser-bin     :: 13.5-1        -> 13.5.2-1
aura :: Determining dependencies...
aura :: Repository dependencies:
 python-build
 python-installer
 python-pyproject-hooks
aura :: AUR packages:
 pip2pkgbuild
 reshade-shaders-git
 tor-browser-bin
aura :: Proceed? [Y/n] ^C⏎
```

**Comment by fosskers** [comment]
To perform those `git clone`s Aura is just calling `git` via the shell. Did the `--log-level=debug` output tell you why it was failing?

**Comment by RubenKelevra** [comment]
No, because I found that option only after it started working again. I tried `--verbose` but that option doesn't exist. While consulting the man page the issue went away. :/

**Comment by fosskers** [comment]
Ghosts in the tubes on the internet. Let's close this issue for now, but please reopen if you notice similar effects in the future.
