### ISSUE TITLE
Aura fails to notice a package update from AUR

### ISSUE THREAD

**Issue by cfinnberg** [fosskers/aura#898]
A package I use from AUR was updated but Aura does not notice it
```
> aura -Qi thunderbird-beta-i18n-fi
Name            : thunderbird-beta-i18n-fi
Version         : 129.0b6-1
Description     : Finnish language pack for Thunderbird Beta
Architecture    : any
URL             : http://www.mozilla.com/
Licenses        : MPL-2.0  GPL-2.0-only  LGPL-2.1-only
Groups          : None
Provides        : None
Depends On      : thunderbird>=129.0b0
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 700.73 KiB
Packager        : Unknown Packager
Build Date      : Tue Jul 30 14:40:02 2024
Install Date    : Tue Jul 30 14:43:40 2024
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None


> aura -Ai thunderbird-beta-i18n-fi
Repository    : aur
Name          : thunderbird-beta-i18n-fi (thunderbird-beta-i18n)
Version       : 130.0b1-1
AUR Status    : Up to Date
Maintainer    : yurikoles
Project URL   : http://www.mozilla.com/
AUR URL       : https://aur.archlinux.org/packages/thunderbird-beta-i18n-fi
License       : GPL-2.0-only LGPL-2.1-only MPL-2.0
Groups        : 
Provides      : 
Depends On    : thunderbird>=130.0b0
Make Deps     : 
Optional Deps : 
Check Deps    : 
Votes         : 3
Popularity    : 0.00
Description   : Finnish language pack for Thunderbird Beta
Keywords      : beta gecko i18n thunderbird
Submitted     : 2019-01-14
Updated       : 2024-08-09


> aura -Ayu
aura :: Fetching package information...
aura :: Comparing package versions...
aura :: No AUR package upgrades necessary.

> aura -V
aura 4.0.2
```

Other AUR managers like `yay` or `pamac` correctly find the update.

**Comment by cfinnberg** [comment]
I noticed that aura asks your database for the package `thunderbird-beta-i18n` (that is the package base) instead of the split package `thunderbird-beta-i18n-fi`. I am not sure if this is correct. At least asking for the right package works: https://faur.fosskers.ca/packages?names=thunderbird-beta-i18n-fi

**Comment by fosskers** [comment]
Thanks for the report, I will debug this.

**Comment by fosskers** [comment]
I was able to build it just now without issue - could you attempt the upgrade again with `--log-level=debug` and paste the output here?

**Comment by cfinnberg** [comment]
I had already updated with other package manager. But I will inform you if it happens again.

Notice however that the problem was not the building of a package, but aura don't noticing the existence of an update for that package. I have to admit that I didn't try to build directly the package (at least as far I can remember)

**Comment by fosskers** [comment]
Thanks. Let's close this for now then, but please feel free to reopen if it happens again.
