### ISSUE TITLE
Unknown package: cosmic-session-git-debug

### ISSUE THREAD

**Issue by utrumo** [fosskers/aura#899]
After I install 
`aura -A cosmic-session-git`, 
a warning appeared when running the aura -Au command:

`aura :: Unknown package: cosmic-session-git-debug`

Why did the warning appear and what does the postfix `-debug` mean?

**Comment by aquova** [comment]
This isn't necessarily an aura thing, it's a fairly recent addition to `makepkg` where it will build a second package that maintains the debug variables. If you want to completely disable this behavior, you can edit your `makepkg.conf` to disallow it, see here: https://man.archlinux.org/man/makepkg.conf.5#OPTIONS (change debug to !debug in the OPTIONS setting)

**Comment by fosskers** [comment]
Thank you @aquova . Regardless, when performing `-Au` Aura should ignore any installed entries that end in `-debug`.

**Comment by aquova** [comment]
Annoyingly, there are some legitimate AUR packages that end in `-debug`, https://aur.archlinux.org/packages?O=0&K=-debug

**Comment by fosskers** [comment]
That had occurred to me, so the condition would be that both the `foo` and `foo-debug` packages appear to be installed.

**Comment by fosskers** [comment]
Thanks again for reporting this.

**Comment by utrumo** [comment]
Thanks.
I added ! to debug flag in `/etc/makepkg.conf` and this solved the problem:
```
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge debug lto)
```
to
```
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)
```

**Comment by mims-github** [comment]
Thanks for the quick fix. @fosskers :clap:
