### ISSUE TITLE
Aura AUR search does not show all possible results

### ISSUE THREAD

**Issue by cfinnberg** [fosskers/aura#906]
if I search for `thunderbird`:
```
aura -As thunderbird
```

aura does not show a result for `thunderbird-localized-beta-bin`

Edit: Results seems to be capped to 50.

**Comment by fosskers** [comment]
Correct, the results are capped by design. More details on Aura's search behaviour can be found here: https://fosskers.github.io/aura/search.html

**Comment by cfinnberg** [comment]
Thanks. I tried the `--help` and the man page, but there is nothing there about this. Would it be a good idea to be able to overpass this? I tried with the `--limit` option, but it probably limits under 50 results, not beyond it.

**Comment by fosskers** [comment]
It's a limit imposed on the side of [the metadata server](https://github.com/fosskers/faur). I could boost it back up to 100 for now. It needs _some_ cap, because some search terms yields thousands of initial results.

**Comment by cfinnberg** [comment]
> As mentioned in the Guide I linked previously, users are encourage to pass multiple search terms to narrow down the results.

Yeah, I agree, but sometimes one has to go with just one term.

No need on my part to change anything on the server now that I now this, but at least I would put the info in the man page, on the search or the limit part.

Thanks for the help anyway!

**Comment by fosskers** [comment]
The info about the Search behaviour is also available in the Info page: `info aura`.
