### ISSUE TITLE
AUR Package fails to install if built tarball is not compressed

### ISSUE THREAD

**Issue by csutcliff** [fosskers/aura#908]
Hi,

I have `PKGEXT='.pkg.tar'` in my makepkg.conf to disable compression of built packages. With this in place packages installed with `aura -A <pkgname>` build correctly but then don't get passed through to the `pacman -U` command

```
error: no targets specified (use -h for help)
aura :: A call to pacman -U failed.
```

Reverting to `PKGEXT='.pkg.tar.zst'` does install the built package.

**Comment by fosskers** [comment]
Thanks for finding this edge case. Indeed the compressed forms are hard-coded as the extension to look for. I'll fix this.

**Comment by mims-github** [comment]
Can confirm, same for me.

FYI:
My motivation to disable compression was this: https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/issues/23#note_173670

**Comment by fosskers** [comment]
Actually I had forgotten that I no longer hard-code the extension to copy by. Could you try this:

1. Go to the `~/.cache/aura/builds/<some-package>/` of a package that is failing to install.
2. Run `makepkg --packagelist`.
3. Paste the output here.

It's the output of `--packagelist` that Aura attempts to copy as-is to the cache and then install.

**Comment by fosskers** [comment]
Actually I've tried this myself as was able to reproduce.

**Comment by fosskers** [comment]
Fixed. Thanks for reporting.
