### ISSUE TITLE
 When delmakedeps = true base-devel package not removing

### ISSUE THREAD

**Issue by utrumo** [fosskers/aura#910]
I set delmakedeps = true in ~/.config/aura/config.toml

After building and installing the package from aur, aura asks me to remove all make dependencies, but skips base-devel

**Comment by fosskers** [comment]
This is by design. `base-devel` is automatically added if missing, and according to AUR policy is always assumed to be installed when building AUR packages.

**Comment by utrumo** [comment]
It's a pity, I expected from this flag that it would completely clean up all dev dependencies.
But at the same time, aura -Oj removes this package.

**Comment by fosskers** [comment]
What would the advantage be to removing it and readding it each time you do an install?

**Comment by fosskers** [comment]
Any thoughts on this?

**Comment by fosskers** [comment]
I'm going to close this for now. Please feel free to reopen it if there's anything further regarding this that you'd like to discuss.
