### ISSUE TITLE
Switch for -k|--diff doesn't seem to work

### ISSUE THREAD

**Issue by dino-** [fosskers/aura#916]
Maybe I'm doing it wrong but my workflow with aura for years has been to do `-Ak PKG` and inspect the PKGBUILD diffs. Since the 4.x versions (I think) I haven't seen this switch do anything, just quietly shows the pending new package version and asks for confirmation. The only way to see AUR PKGBUILD files any longer is to use `-Ap` which doesn't show diffs with the prior installation.

**Comment by fosskers** [comment]
Hi, have I mistaken the timing of when the `-k` results fire? Here's a screenshot:
![Auk](https://github.com/user-attachments/assets/13c8ae3d-b0c7-4ddd-b3da-6c5a6278d8bf)

Here we see confirmation for the initial acceptance of the updates, then a prompt to view the diffs, then another prompt to continue after the diff has been approved. 

Although now I see that you mean just `-Ak`, not with `-u`? Was your old experience that with just `-Ak`, it would print the diffs and then exit, without attempting to install?

**Comment by dino-** [comment]
Can you post what command you used to get that output above? I don't see anything like that. I just tested by installing an AUR package one version back (using manual build with git clone and makepkg of the AUR repo) and then used `aura -Ak PACKAGENAME` to update it to the latest. Never saw the PKGBUILD diff throughout the entire process from downloading to building to installation.

**Comment by dino-** [comment]
Yes, I used to do `aura -Ak PKG1 PKG2 ...` and see one or more of them before anything was built, so I could bail out on it. I guess this was never really the intended use of -k

**Comment by fosskers** [comment]
I ran `aura -Auk` to produce the above.

> I just tested by installing an AUR package one version back (using manual build with git clone and makepkg of the AUR repo) 

That's what would do it. In order to produce the diff, Aura has to know from which commit it's to produce the diff _from_. It does this by saving a git hash to `~/.cache/aura/hashes/` after every build. When `-k` is used, it checks the commit of the current `git pull` vs what it previously stored in `hashes/` and then calls `git diff` based on those.

**Comment by fosskers** [comment]
I have confirmed that `-Ak` works, even without `-u`. Shall we close this issue?

**Comment by fosskers** [comment]
Hi again, I'm going to close this. Feel free to reopen if you experience other issues with `k`.
