### ISSUE TITLE
Aura 4: -Qtt not supported

### ISSUE THREAD

**Issue by Chalice** [fosskers/aura#919]
Greetings!

Aura does not seem to support the second -t / --unrequired argument to -Q.

According to the Pacman manpage, specifying -t a second time includes packages 'which are optionally, but not directly, required'.

Aura outputs the following on using -Qtt:

`error: the argument '--unrequired' cannot be used multiple times

Usage: aura {query|--query|-Q} [OPTIONS] [PACKAGES]...

For more information, try '--help'`

**Comment by fosskers** [comment]
Thanks for reporting, this is an easy fix.
