### ISSUE TITLE
Enhancement: Support paccache's -u switch

### ISSUE THREAD

**Issue by Chalice** [fosskers/aura#920]
Greetings!

Aura's "-Cc X" switch combination allows it to currently mimic paccache -rk X, where X is the amount of last versions of packages to be kept in the package cache.

It would be neat if aura would also gain compatibility with paccache's -u option, where only non-installed package archives are checked and removed. (i.e. paccache -ruk 0 removes all archives of currently not installed packages).

Example:

aura -Cuc 0 = remove all versions of currently not installed packages from the cache.

**Comment by fosskers** [comment]
Hi, can you check the `-n` suboption for `-Cc` and see if that would suffice?

**Comment by Chalice** [comment]
Heya!

-Cn is not a good replacement, because without manually creating a package record, it just purges your entire cache.
I just tested it. :p

**Comment by fosskers** [comment]
Sorry, I had assumed you'd have an auto-saved package state so that that wouldn't happen.

**Comment by fosskers** [comment]
Hi there, any thoughts on those other options I linked?

**Comment by Chalice** [comment]
Greetings!
Sorry, I saw the links late.
-Sc has the problem that it only keeps the archives of the currently installed versions - it does not allow you to keep, say, the last 2 versions instead, which is what aura -Cc 2 does.
But -Cc also keeps the archives of non-installed packages, and we're back to square one :)

**Comment by fosskers** [comment]
Thanks I'll consider this.
