### ISSUE TITLE
Aura throws an error message instead of returning with no results on search

### ISSUE THREAD

**Issue by RubenKelevra** [fosskers/aura#922]
If I call Aura 4.0.3 it will throw an error message, that pacman returned a non-zero exit code, if there's no search result for a search query.

That's somewhat unexpected.

```
$ aura -Ss package-which-doesnt-exist
aura :: A call to pacman gave a non-zero exit code.
```

Pacman will just return nothing.

```
$ pacman -Ss package-which-doesnt-exist

```

**Comment by fosskers** [comment]
Indeed there are certain passthrough commands for which this error message is jarring. I'll fix it.

**Comment by fosskers** [comment]
Thanks again.

**Comment by RubenKelevra** [comment]
You're welcome :)
