### ISSUE TITLE
Aura fails building teams-for-linux because it tries to create a cache directory at root level

### ISSUE THREAD

**Issue by apirogov** [fosskers/aura#925]
I think there is a bug in aura:

```
aura :: AUR packages to upgrade:
 teams-for-linux :: 1.8.0-1 -> 1.9.6-1
aura :: Determining dependencies...
aura :: AUR packages:
 teams-for-linux
aura :: Proceed? [Y/n] 
aura :: Saved package state.
aura :: Preparing build directories...
aura :: Building teams-for-linux...
==> Making package: teams-for-linux 1.10.0-1 (Thu 05 Sep 2024 01:27:16 PM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading teams-for-linux-1.10.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 11.8M  100 11.8M    0     0  14.1M      0 --:--:-- --:--:-- --:--:-- 20.9M
  -> Found teams-for-linux.desktop
==> Validating source files with sha256sums...
    teams-for-linux-1.10.0.tar.gz ... Passed
    teams-for-linux.desktop ... Passed
==> Extracting sources...
  -> Extracting teams-for-linux-1.10.0.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm error code 1
npm error path /tmp/aura/builds/teams-for-linux/src/teams-for-linux-1.10.0/node_modules/electron
npm error command failed
npm error command sh -c node install.js
npm error Error: EACCES: permission denied, mkdir '/.cache'
npm error A complete log of this run can be found in: /tmp/aura/builds/teams-for-linux/src/package-cache/_logs/2024-09-05T11_27_17_675Z-debug-0.log
==> ERROR: A failure occurred in build().
    Aborting...
aura :: Package failed to build, citing:

  makepkg failed.

aura :: Action cancelled.
```

If I build the package manually with `makepkg`, it works.

**Comment by fosskers** [comment]
Thanks for reporting. What was the exact command you used to run Aura? Did it include `sudo`? Or, are you running as the root user?

**Comment by apirogov** [comment]
Yes, I use `sudo`, so I get this with `sudo aura -A teams-for-linux`. The same thing happens on two different machines where I use Arch with aura.

**Comment by fosskers** [comment]
Assuming you're using Aura 4, please avoid using `sudo` in the future. It's no longer necessary, and as you can see currently causes problems.

**Comment by fosskers** [comment]
Shall we close this?

**Comment by apirogov** [comment]
Well, there are different things that could be done here:

* aura could warn / refuse to work with sudo to avoid this kind of issue
* aura could still be fixed so it can still work with sudo, even if it is discouraged

I have no strong opinion what would be the best thing here, but I think that it should be communicated by the tool somehow. I was using aura for years, long before it was ported to Rust, and never once I checked whether anything changed (as I assume most people do).

If certain things are now deprecated / discouraged, I believe that it should be something shown as a warning or error message.

In any case, thanks a lot for creating and maintaining aura! This is the first time ever that I had any "issue" with it, that's pretty rock solid :)

**Comment by fosskers** [comment]
> I think that it should be communicated by the tool somehow

This is fair. In that case, we can close this in favour of #873 . I will fix this as it seems like "old habits die hard". I tried to communicate the `sudo` change as best I could but if two people have reported this than at least 20 have suffered by it.

> In any case, thanks a lot for creating and maintaining aura! This is the first time ever that I had any "issue" with it, that's pretty rock solid :)

Thank you! I'm always glad to hear from long-time users.
