### ISSUE TITLE
Updating aura fails due to changelog does not exist

### ISSUE THREAD

**Issue by PickMeNow** [fosskers/aura#928]
Hi,

Tried to update aura recently and while building I get the following error:

$ aura -A aura
aura :: Determining dependencies...
aura :: AUR packages:
 aura
aura :: Proceed? [Y/n] y
aura :: Preparing build directories...
aura :: Building aura...
==> ERROR: changelog file (CHANGELOG.md) does not exist or is not a regular file.
aura :: Package failed to build, citing:

  makepkg failed.

aura :: Action cancelled.

**Comment by fosskers** [comment]
Apologies, it should be fixed now. Thanks for reporting this.
