### ISSUE TITLE
Aura not downloading patch files?

### ISSUE THREAD

**Issue by FlynnD273** [fosskers/aura#929]
Trying tp upgrade the [extension-manager](https://aur.archlinux.org/packages/extension-manager) package for GNOME. It worked for 0.5.1-4, but not the most recent version 0.5.1-5. Here's the output from Aura:
```
~ ❱ aura -A extension-manager
aura :: Determining dependencies...
aura :: AUR packages:
 extension-manager
aura :: Proceed? [Y/n]
aura :: Preparing build directories...
aura :: Building extension-manager...
==> Making package: extension-manager 0.5.1-5 (Mon 09 Sep 2024 03:56:57 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found extension-manager-0.5.1.tar.gz
==> ERROR: backtrace.patch was not found in the build directory and is not a URL.
aura :: Package failed to build, citing:

  makepkg failed.

aura :: Action cancelled.
```

I'm not entirely sure how Aura works under the hood, but it seems like it's only downloading the tarball from the URL in the PKGBUILD, and not the other files in the AUR entry? When I look in the `~/.cache/aura/builds/extension-manager` directory I only see the PKGBUILD file, not *.patch files. The patch files are present if I clone/download the package directly from the AUR page though. Is this expected behaviour? I see no mention of it in the documentation so I'm a wee bit confused.

**Comment by fosskers** [comment]
Can you check the difference in folder contents of `~/.cache/aura/packages/extension-manager/` and `~/.cache/aura/builds/extension-manager/`?

**Comment by FlynnD273** [comment]
The `packages` folder has all the expected files, the `builds` does not. It successfully built and installed after I copied the patch files from `packages` to `builds`

**Comment by fosskers** [comment]
There must be a problem with copying over the `.patch` files. I'll take a look. Thanks for reporting ths.

**Comment by fosskers** [comment]
I have investigated the issue, and I believe this is a case of the package being improperly packaged. See https://aur.archlinux.org/packages/extension-manager#comment-990684 .
