### ISSUE TITLE
Error libalpm.so.14 cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by PickMeNow** [fosskers/aura#931]
Hi,

I getting the following error after upgrade (-Syu) packages in archlinux:

$ aura
aura: error while loading shared libraries: libalpm.so.14: cannot open shared object file: No such file or directory

**Comment by fosskers** [comment]
What's the output of:
```
pacman -Qi pacman
```
?

**Comment by PickMeNow** [comment]
Seems that other aur helpers are also experiencing this problem, something to do with alpm


Here is the output:
Name            : pacman
Version         : 7.0.0.r3.g7736133-1
Description     : A library-based package manager with dependency support
Architecture    : x86_64
URL             : https://www.archlinux.org/pacman/
Licenses        : GPL-2.0-or-later
Groups          : None
Provides        : libalpm.so=15-64
Depends On      : bash  coreutils  curl  gawk  gettext  glibc  gnupg  gpgme  grep  libarchive  pacman-mirrorlist  systemd
Optional Deps   : base-devel: required to use makepkg [installed]
                  perl-locale-gettext: translation support in makepkg-template
Required By     : archlinux-keyring  base  base-devel  pacman-contrib  pacutils  pkgstats
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 4.82 MiB
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : Mon 09 Sep 2024 05:50:39 PM WEST
Install Date    : Sat 14 Sep 2024 12:43:02 PM WEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

I tried also to remove and reinstall 'aura' but getting an error, building with rust, with 'aura-bin' I am able to install it
error: failed to run custom build command for `alpm v3.0.5'

**Comment by fosskers** [comment]
Ah you're on a git-version of Pacman then? libalpm has also had its version bumped recently. The `alpm` Rust package has already accounted for this, but since v7 of Pacman hasn't been officially released yet, I can't yet upgrade.

**Comment by PickMeNow** [comment]
No, using normal pacman, I believe it was just updated now according to archlinux news:
This might be the reason > https://archlinux.org/news/manual-intervention-for-pacman-700-and-local-repositories-required/

**Comment by xukashi** [comment]
Pacman v7.0.0 - libalpm v15.0.0 is out now.

**Comment by xukashi** [comment]
> I managed to work around the problem by using:
> 
> ```shell
> sudo ln -s /usr/lib/libalpm.so.15.0.0 /usr/lib/libalpm.so.14
> ```

Don't symlink different SO libraries for something that handles your system files, a package manager is the last thing you want to break on undefined behavior, the SO bump happened for a reason.

**Comment by tieje** [comment]
same issue as author

**Comment by tianyu** [comment]
I'm getting the same behavior as well

**Comment by fosskers** [comment]
Yup, thanks guys. Upgrading now.
