### ISSUE TITLE
Clean the build directory

### ISSUE THREAD

**Issue by Digitalone1** [fosskers/aura#932]
Hello, thanks for this project, it's very useful.

Sorry if the question has been already asked, but I didn't find a similar one. Is there an easy way to clean the build folder?

I see there are commands to clean the cache, but what about the build folder? I don't see a reason to keep the build files.

**Comment by fosskers** [comment]
Hi there. Check out the `-c` switch, shown on `aura -Ah`.

**Comment by Digitalone1** [comment]
@fosskers Thank you.
