### ISSUE TITLE
Cannot use as root anymore

### ISSUE THREAD

**Issue by mintsuki** [fosskers/aura#935]
Hi. Let me preface this by saying that I am fully aware of the dangers of running unnecessary builds or other code as root, that said, the Aura "feature" that I loved the most was the ability to run it as root, which I found very useful for my particular use cases.

Could it be possible to bring this back, perhaps behind a flag to enable it? (I am okay with making it harder for novices to run Aura as root, as long as I can still do so if i so choose).

Thanks in advance.

**Comment by fosskers** [comment]
Apologies if that feature was broken - that wasn't my intention. What command were you running, and under what user?

**Comment by mintsuki** [comment]
I have an `aura` command within a script, and the script is meant to be run as root (so I run it with `sudo` within this context). It is not about running `sudo aura` directly in this case, but it breaks my script.

**Comment by fosskers** [comment]
Ah so the wrapping script is being invoked with `sudo`, but Aura itself within the script is just being called "normally", thereby running as root.

**Comment by mintsuki** [comment]
> Ah so the wrapping script is being invoked with `sudo`, but Aura itself within the script is just being called "normally", thereby running as root.

Correct. Apologies if my original description wasn't quite accurate.

**Comment by fosskers** [comment]
In that case we'd expect it to work. I will test this.

**Comment by thorio** [comment]
I'm running into a similar issue with ansible.
Using ansible's built-in `become` option (which uses sudo by default) provokes the same "Running Aura with sudo is not necessary." message, and running without become and prompting for a password obviously doesn't work in a non-interactive context.

When running without become/sudo, aura spits out

<details>
<summary>stdout</summary>

```text
aura :: Determining dependencies...
aura :: AUR packages:
 osu-lazer-bin
 osu-mime
aura :: Preparing build directories...
aura :: Building osu-mime...
aura :: Package failed to build, citing:
aura :: Preparing build directories...
aura :: Building osu-lazer-bin...
aura :: Package failed to build, citing:
aura :: Done.
```
</details>

<details>
<summary>stderr</summary>

```text
chown: changing ownership of '/home/thorou/.cache/aura/builds/osu-mime/PKGBUILD': Operation not permitted
chown: changing ownership of '/home/thorou/.cache/aura/builds/osu-mime/osu-mime.install': Operation not permitted
chown: changing ownership of '/home/thorou/.cache/aura/builds/osu-mime/osu-file-extensions.xml': Operation not permitted
chown: changing ownership of '/home/thorou/.cache/aura/builds/osu-mime': Operation not permitted

  Failed to set file permissions for: /home/thorou/.cache/aura/builds/osu-mime

chown: changing ownership of '/home/thorou/.cache/aura/builds/osu-lazer-bin/icon.png': Operation not permitted
chown: changing ownership of '/home/thorou/.cache/aura/builds/osu-lazer-bin/osu-lazer': Operation not permitted
chown: changing ownership of '/home/thorou/.cache/aura/builds/osu-lazer-bin/osu-lazer-uri-handler.desktop': Operation not permitted
chown: changing ownership of '/home/thorou/.cache/aura/builds/osu-lazer-bin/PKGBUILD': Operation not permitted
chown: changing ownership of '/home/thorou/.cache/aura/builds/osu-lazer-bin/osu-lazer.desktop': Operation not permitted
chown: changing ownership of '/home/thorou/.cache/aura/builds/osu-lazer-bin': Operation not permitted

  Failed to set file permissions for: /home/thorou/.cache/aura/builds/osu-lazer-bin
```
</details>

and exits with 0, which I also thought was strange.

Since I can't easily roll aura back due to a library mismatch, I'm effectively stuck with a bunch of broken ansible playbooks.

Is there some workaround I can use until there is a proper fix for this?

**Comment by fosskers** [comment]
Thanks for the additional report. I will fix this.

**Comment by fosskers** [comment]
Thanks for the additional report. I will fix this.·
