### ISSUE TITLE
Using relative path for cache and others

### ISSUE THREAD

**Issue by SanchayanMaity** [fosskers/aura#937]
Is it possible to use relative paths for `cache` and others on the lines of `~/.aura/cache`?

```bash
# ~ → .aura λ: ls
builds/  cache/  hashes/  packages/  snapshots/
```
These directories are in path `~/.aura`.

Snippet of aura configuration for the directories.

```
[aur]
build         = "~/.aura/builds"
cache         = "~/.aura/cache"
clones        = "~/.aura/packages"
hashes        = "~/.aura/hashes"
```

Snippet from the output of `aura check`.

```bash
aura :: Package Tarball Caches
  [✕] All specified caches exist? (1/2)
      └─ ~/.aura/cache
```

Trying to use the above makes `aura check` complain that the cache path does not exist. If I change the configuration to use absolute paths like `/home/user/.aura/cache` and not with `~`, `aura check` does not complain.

```
[aur]
build         = "/home/user/.aura/builds"
cache         = "/home/user/.aura/cache"
clones        = "/home/user/.aura/packages"
hashes        = "/home/user/.aura/hashes"
```

```bash
aura :: Package Tarball Caches
  [✓] All specified caches exist? (2/2)
```

I tried checking in the user guide but unless I missed something, this seems not possible or am I misinterpreting something here?

Thank you for your work on this.

**Comment by SanchayanMaity** [comment]
> > Trying to use the above makes aura check complain that the path does not exist while the directory has been created.
> 
> I don't quite understand this. Can you elaborate? Are you running `aura check` and seeing something strange?

Sorry for not being clear. Updated the issue description.

**Comment by AlexAegis** [comment]
![image](https://github.com/user-attachments/assets/6f17b84d-70f3-439f-af73-7544b3d220b1)

To add more context, I use a dotfiles repo and configs like this I like to keep under version control, but for that to make sense I don't want to tie to a specific username. Using env variables here would be nice

**Comment by SanchayanMaity** [comment]
> ![image](https://private-user-images.githubusercontent.com/16900547/368663953-6f17b84d-70f3-439f-af73-7544b3d220b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2ODY2NDEsIm5iZiI6MTcyNjY4NjM0MSwicGF0aCI6Ii8xNjkwMDU0Ny8zNjg2NjM5NTMtNmYxN2I4NGQtNzBmMy00MzlmLWFmNzMtNzU0NGIzZDIyMGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDE5MDU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMjRiN2Y3ZjQ3MGQ3Nzk5OTZiYzI2ODdmNmNkYTc2OGU5OTA1YTM0YWRlY2JlMjA1NzJlYTlhNTQ5MGNkMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YjG9igie3lCeLZSK1k4bHxVyu_B0uhnL_N1h3WZmu40)
> 
> To add more context, I use a dotfiles repo and configs like this I like to keep under version control, but for that to make sense I don't want to tie to a specific username. Using env variables here would be nice
> 
> (I'm happy with the defaults so for now I just removed these variables once I realized this doesn't work)

Yes, need this for the exact same use case.

**Comment by fosskers** [comment]
> I'm happy with the defaults so for now I just removed these variables once I realized this doesn't work

This is the fastest way around it. If those variables are missing from config, Aura will look for those folders under `XDG_CACHE_HOME`.

**Comment by fosskers** [comment]
The following:
```rust
use std::path::Path;

fn main() {
    let p = Path::new("~/.cache/aura/cache");
    println!("{}", p.is_dir());

    let p = Path::new("/home/colin/.cache/aura/cache");
    println!("{}", p.is_dir());

}
```
yields
```
false
true
```
which I did not expect.

**Comment by AlexAegis** [comment]
It makes sense, there's nothing there to resolve what ~ means so it is used literally as ./~/foo/bar

**Comment by fosskers** [comment]
Since it's supposed to be all POSIX underneath I assumed it would "just work" but that doesn't seem to be the case. Further, calling `std::fs::canonicalize` on such a `Path` panics. So for this issue in particular, I'm going to say that relative paths within `config.toml` are not permitted.
