### ISSUE TITLE
`aura -Aa --asdeps <packages>` will immediately remove its "explicit" packages

### ISSUE THREAD

**Issue by ultimatespirit** [fosskers/aura#942]
Bit of a funny edge case here. Pretty sure `makepkg` does not have this behaviour on its own.

Running `aura -Aa --asdeps foo` seems to mark `foo` as a dependency before figuring out the list of dependencies to remove, thereby leading to it deciding that `foo` is, itself, a dependency of the `foo` transaction and warrants removal. So... `aura -Aa --asdeps foo` essentially ends up almost a no-op, granted it does at least populate your cache.

Workaround: I've been running `aura -Aa foo` and then `sudo pacman -D --asdeps foo`

**Comment by fosskers** [comment]
Hah that's a funny case and definitely not intended. Thanks for reporting.
