### ISSUE TITLE
How do I run aura as a root user?

### ISSUE THREAD

**Issue by flajann2** [fosskers/aura#943]
Running aura as root is a part of my normal workflow when I am configuring my system at the root level, because many other commands that I might run will only run as root, and typing "sudo" at the beginning of every commands gets old quickly.

I went splunking through your source code and did not see anything obvious.

So how do I reenable this functionality?

**Comment by fosskers** [comment]
`sudo` is not necessary - you should be able to run Aura as root and build packages normally with just `aura -A foo`.

**Comment by flajann2** [comment]
It won't let me. When I am logged in as root (not using sudo), it gives me the same "sudo no longer required" and refuses to run. I have to get out of root and go back to my user account just to run aura.

**Comment by flajann2** [comment]
So you have no intentions on giving me an option or configuration at least? Wow.

**Comment by fosskers** [comment]
The issue was closed by a commit fixing the issue. You should be able to run Aura as root without issue now.

**Comment by flajann2** [comment]
Thank you.
