### ISSUE TITLE
PKGBUILD and packageinformation differ

### ISSUE THREAD

**Issue by tristanRW** [fosskers/aura#947]
Hi, I noticed a weird asynchronity between `aura -Ai` and `aura -Ap` today.

I checked for the remnote AUR package using the `aura -Ai remnote` and got info on the package that reflects the package will be up to date with the state of the AUR (changed a few hours ago).
Yet when I check the PKGBUILD using `aura -Ap` I get the old PKGBUILD from before the last update.
Please find the relevant terminal output attached. [aura.log](https://github.com/user-attachments/files/17228958/aura.log)

I honestly have no clue how to fix it though.

**Comment by fosskers** [comment]
Hi, thanks for the report. Try `-Ay` once and then `-Ap` again, and see what happens.

**Comment by tristanRW** [comment]
Hi, tried that and it worked perfectly. Thank you alot.
`-Ay` fetches the newest PKGBUILD. Even if it was updated more recently than the last FAUR-sync. I like it so much. 🤩🤩
One thing I noticed is that using `-Ay`, it is possible to have a PKGBUILD newer than the info displayed using `-Ai`. (Probably because `-Ay` gets the newest PKGBUILD and `-Ai` displays the one in FAUR? )

**Comment by fosskers** [comment]
Yup you're correct. Specifically, `-Ay` forces a `git pull` of all the package clones you currently have in your `~/.cache/aura/packages/`, and the PKGBUILD is one piece of that.

Shall we close this?

**Comment by tristanRW** [comment]
Thank you for explaining.
Let's close this, since the issue is resolved.

**Comment by fosskers** [comment]
Great, let me know if you have any other issues.
